# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

sources:
  default-aws:
    environment: default
    zone: aws
    url: https://gateway.com/admin-api
    tokenUrl: https://idp.com/auth/realms/rover
    clientId: rover
    clientSecret: topsecret