# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-role
rules:
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - apiexposures
  - apis
  - apisubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - organization.cp.ei.telekom.de
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rover.cp.ei.telekom.de
  resources:
  - apispecifications
  - rovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
