# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admin.cp.ei.telekom.de/v1
kind: Zone
metadata:
  labels:
    app.kubernetes.io/name: dataplane2
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: controlplane
  name: dataplane2
  namespace: controlplane
spec:
  visibility: Enterprise
  identityProviders:
    - name: primary
      url: https://my-idp.example.com/
      issuerHostname: my-idp.example.com
      admin:
        clientId: admin-cli
        userName: admin
        password: somePassword
  gateways:
    - name: standard
      admin:
        identityProviderRef: primary
        url: https://my-gateway-admin.example.com/admin-api
        clientId: gateway-admin
  presets:
    - name: default
      type: API
      default: true
      gatewayRef: standard
      identityProviderRef: primary
      urls:
        - hostname: my-gateway.example.com
          basePath: /
  redis:
    host: my-redis-host
    port: 6379
    password: somePassword
