# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rover.cp.ei.telekom.de/v1
kind: ApiSpecification
metadata:
  name: eni-foo-v2
spec:
  specification: |
    openapi: "3.0.0"
    info:
      version: "1.0.0"
      title: "Test API"
      x-category: "test"
    servers:
      - url: "https://example.com/eni/foo/v2"
    security:
      - oauth2:
          - read
          - write
