# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rover.cp.ei.telekom.de/v1
kind: Rover
metadata:
  name: rover-echo-v1
spec:
  zone: dataplane1
  clientSecret: someSecret
  exposures:
    - api:
        basePath: /phoenix/echo/v1
        upstreams:
          - url: https://httpbin.org/anything
            weight: 50
          - url: https://httpbin.org/anything/balancing-the-load
            weight: 50
        visibility: World
        approval:
          strategy: Auto
        security:
          m2m:
            scopes:
              - read
  subscriptions:
    - api:
        basePath: /phoenix/echo/v1
        security:
          m2m:
            scopes:
              - read
              - write
---
apiVersion: rover.cp.ei.telekom.de/v1
kind: Rover
metadata:
  name: rover-echo-consumer
spec:
  zone: dataplane1
  clientSecret: someSecret
  subscriptions:
    - api:
        basePath: /phoenix/echo/v1
