# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: tcp.ei.telekom.de/v1
kind: Rover
metadata:
  name: test-rover
spec:
  zone: dataplane1
  exposures:
  - basePath: /eni/e2e-test/this-is-a-superlong-path-to-test-the-handling-of-long-urls-in-the-system/it-actually-keeps-going-and-going-and-going/v1
    visibility: ENTERPRISE
    approval: AUTO
    upstream: http://test-service:8080
  subscriptions:
  - basePath: /eni/e2e-test/this-is-a-superlong-path-to-test-the-handling-of-long-urls-in-the-system/it-actually-keeps-going-and-going-and-going/v1
    security:
      oauth2:
        username: test-user
        password: test-password