# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

version: 2

before:
  hooks: []

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

snapshot:
  version_template: "SNAPSHOT-{{.ShortCommit}}"

builds:
  - id: common-server
    dir: common-server
    main: cmd/server/server.go
    binary: common-server
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: secret-manager
    dir: secret-manager
    main: cmd/server/server.go
    binary: secret-manager
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: approval
    dir: approval
    main: cmd/main.go
    binary: approval
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: gateway
    dir: gateway
    main: cmd/main.go
    binary: gateway
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: identity
    dir: identity
    main: cmd/main.go
    binary: identity
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: organization
    dir: organization
    main: cmd/main.go
    binary: organization
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: admin
    dir: admin
    main: cmd/main.go
    binary: admin
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: application
    dir: application
    main: cmd/main.go
    binary: application
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: api
    dir: api
    main: cmd/main.go
    binary: api
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: rover
    dir: rover
    main: cmd/main.go
    binary: rover
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*
      - CHANGELOG.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  header: >-
    # 🚀 Release {{ .Version }}
  footer: >-

    ---

    ✨🎉

sboms:
  - artifacts: archive

kos: 
  - id: common-server
    build: common-server
    main: .
    working_dir: common-server/cmd/server
    repositories:
      - ghcr.io/telekom/controlplane/common-server
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    base_image: gcr.io/distroless/static:nonroot
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: secret-manager
    build: secret-manager
    main: .
    working_dir: secret-manager/cmd/server
    repositories:
      - ghcr.io/telekom/controlplane/secret-manager
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    base_image: gcr.io/distroless/static:nonroot
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: approval
    build: approval
    main: .
    working_dir: approval/cmd
    repositories:
      - ghcr.io/telekom/controlplane/approval
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: gateway
    build: gateway
    main: .
    working_dir: gateway/cmd
    repositories:
      - ghcr.io/telekom/controlplane/gateway
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: identity
    build: identity
    main: .
    working_dir: identity/cmd
    repositories:
      - ghcr.io/telekom/controlplane/identity
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: organization
    build: organization
    main: .
    working_dir: organization/cmd
    repositories:
      - ghcr.io/telekom/controlplane/organization
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: admin
    build: admin
    main: .
    working_dir: admin/cmd
    repositories:
      - ghcr.io/telekom/controlplane/admin
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: application
    build: application
    main: .
    working_dir: application/cmd
    repositories:
      - ghcr.io/telekom/controlplane/application
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: api
    build: api
    main: .
    working_dir: api/cmd
    repositories:
      - ghcr.io/telekom/controlplane/api
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
  - id: rover
    build: rover
    main: .
    working_dir: rover/cmd
    repositories:
      - ghcr.io/telekom/controlplane/rover
    labels:
      org.opencontainers.image.authors: "Deutsche Telekom IT GmbH <opensource@telekom.de>"
      org.opencontainers.image.url: "https://developer.telekom.de/"
      org.opencontainers.image.source: https://github.com/telekom/controlplane
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.licenses: "Apache-2.0"
    user: 65532:65532
    tags:
      - latest
      - "{{.Tag}}"
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true