openapi: 3.0.3
info:
  title: Organization Api
  description: >-
    API of the TARDIS control plane. With this API, you can manage your Hubs and Teams.
  contact:
    name: TARDIS
    url: https://developer.telekom.de/docs/src/tardis_customer_handbook/support/
    email: FMB_TARDIS_Support@telekom.de
  version: 1.0.0
  x-api-category: Infrastructure
servers:
  - url: https://api.telekom.de/organization/v1
security:
  - OAuth2:
      - tardis:admin:all
tags:
  - name: Hub
    description: Manage Hubs
  - name: Team
    description: Manage Teams
  - name: Resources
    description: Overview of a Teams resources
  - name: Observer
    description: Manage the TeamObservers
paths:
  /hubs:
    get:
      tags:
        - Hub
      summary: Find all Hubs
      description: Find all Hubs
      operationId: getAllHubs
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
    post:
      tags:
        - Hub
      summary: Create a Hub
      description: >-
        Create a new and empty Hub with the specified name, displayName (this will be used in MissionControl),
        email and description.
      operationId: createHub
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
  /hubs/{hubName}:
    get:
      tags:
        - Hub
      summary: Find an existing Hub
      description: Find an existing Hub
      operationId: getHub
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
    put:
      tags:
        - Hub
      summary: Update an existing Hub
      description: Update an existing Hub.
      operationId: updateHub
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
    delete:
      tags:
        - Hub
      summary: Delete a Hub
      description: Delete Hub - all teams needs to be deleted before a Hub can be deleted.
      operationId: deleteHub
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
  /hubs/{hubName}/teams:
    get:
      tags:
        - Team
      summary: Find all Teams
      description: Find all Teams in the specified Hub
      operationId: getAllTeams
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
            - tardis:team:read
            - tardis:team:all
    post:
      tags:
        - Team
      summary: Create a Team
      description: >-
        Create a new and Team with the specified name, displayName (this will be used in MissionControl),
        email and description. Also adds all specified team members
      operationId: createTeam
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
            - tardis:team:all
  /hubs/{hubName}/teams/{teamName}:
    get:
      tags:
        - Team
      summary: Find an existing Team
      description: Find an existing Team
      operationId: getTeam
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
            - tardis:team:read
            - tardis:team:all
    put:
      tags:
        - Team
      summary: Update an existing Team
      description: Update an existing Team.
      operationId: updateTeam
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
            - tardis:team:all
    delete:
      tags:
        - Team
      summary: Delete a Team
      description: >-
        Delete Team - all Team resources need to be deleted before a Team can be deleted.
        You can use the /hubs/{hubName}/teams/{teamName}/resources endpoint to see the names
        of the Rover resources registered with this team.
        
        
        **WARNING !!!** - this operation cannot be reversed. Please use this endpoint only if you are 
        absolutely sure this team can be deleted.
      operationId: deleteTeam
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
            - tardis:team:all

  /hubs/{hubName}/teams/{teamName}/observer:
    get:
      tags:
        - Observer
      summary: Get the currently configured observer for this team
      description: >-
        If this team has a observer configured, return it. An observer is defined
        in the Raccoon domain and is used to provision a Grafana instance of this team.
      operationId: getTeamObserver
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
            - tardis:team:read
            - tardis:team:all
    put:
      tags:
        - Observer
      summary: Create or update the observer for this team
      description: >-
        Create or update the observer for this team. This will create a new resource
        in the Raccoon domain and is used to provision a Grafana instance of this team.
      operationId: updateTeamObserver
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
            - tardis:team:all
    delete:
      tags:
        - Observer
      summary: Delete the observer for this team
      description: >-
        Delete the observer for this team.
      operationId: deleteTeamObserver
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
            - tardis:team:all
  /hubs/{hubName}/teams/{teamName}/resources:
    get:
      tags:
        - Resources
      summary: Find all Resources that belong to this Team
      description: >-
        Find all Resources that belong to the specified Team in the specified Hub. The response includes references to 
        Rovers, ApiSpecifications, EventSpecifications and FileSpecifications. This is useful as an
        overview of what resources this Team has registered in the system. To get more details about
        individual resources, please use the Rover API.
      operationId: getAllTeamResources
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
            - tardis:team:read
            - tardis:team:all
  /hubs/{hubName}/teams/{teamName}/teamtoken:
    patch:
      tags:
        - TeamToken
      summary: Reset the team token for this Team
      description: >-
        Reset the team token for this Team
      operationId: resetTeamToken
      security:
        - OAuth2:
            - tardis:admin:all
            - tardis:hub:all
            - tardis:team:all
  /hubs/{hubName}/status:
    get:
      tags:
        - Hub
      summary: Find an existing Hub and return its status
      description: Find an existing Hub and return its status
      operationId: getHubStatus
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
  /hubs/{hubName}/teams/{teamName}/status:
    get:
      tags:
        - Team
      summary: Find an existing Team and return its status
      description: Find an existing Team and return its status
      operationId: getTeamStatus
      security:
        - OAuth2:
            - tardis:admin:obfuscated
            - tardis:admin:read
            - tardis:admin:all
            - tardis:hub:obfuscated
            - tardis:hub:read
            - tardis:hub:all
            - tardis:team:read
            - tardis:team:all
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth2 client_credentials flow
      flows:
        clientCredentials:
          tokenUrl: https://example.com/auth/realms/realm//protocol/openid-connect/token
          scopes:
            tardis:admin:obfuscated: all resources are accessible, but sensitive information are omitted
            tardis:admin:read: all resources are accessible, sensitive information are visible
            tardis:admin:all: full rights to all endpoints and operations
            tardis:hub:obfuscated: all hub related resources are accessible, but sensitive information are omitted
            tardis:hub:read: all hub related resources are accessible, sensitive information are visible
            tardis:hub:all: full rights to all hub related endpoints and operations
            tardis:team:obfuscated: all team related resources are accessible, but sensitive information are omitted
            tardis:team:read: all team related resources are accessible, sensitive information are visible
            tardis:team:all: full rights to all team related endpoints and operations