# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: organization.cp.ei.telekom.de/v1
kind: Team
metadata:
  name: phoenix--firebirds
spec:
  name: firebirds
  group: phoenix
  email: firebirds-mail@example.com
  members:
    - name: user1
      email: user1@example.com
