# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view apis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
  name: api-viewer-role
rules:
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - apis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - apis/status
  verbs:
  - get
