# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view remoteapisubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
  name: remoteapisubscription-viewer-role
rules:
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - remoteapisubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - remoteapisubscriptions/status
  verbs:
  - get
