# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - remoteorganizations
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - zones/status
  verbs:
  - get
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - apiexposures
  - apis
  - apisubscriptions
  - remoteapisubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - apiexposures/finalizers
  - apis/finalizers
  - apisubscriptions/finalizers
  - remoteapisubscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - api.cp.ei.telekom.de
  resources:
  - apiexposures/status
  - apis/status
  - apisubscriptions/status
  - remoteapisubscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - approval.cp.ei.telekom.de
  resources:
  - approvalrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - approval.cp.ei.telekom.de
  resources:
  - approvals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - consumeroutes
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - realms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - clients
  verbs:
  - get
  - list
  - watch
