# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: controlplane-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-operator
  namespace: controlplane-system
  labels:
    app: migration-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration-operator
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: migration-operator
        control-plane: controller-manager
    spec:
      serviceAccountName: migration-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        args:
        - --leader-elect
        - --remote-cluster-secret-name=remote-cluster-token
        - --remote-cluster-secret-namespace=controlplane-system
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
      terminationGracePeriodSeconds: 10
