# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/managed-by: kustomize
  name: discovery-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: discovery-server-role
subjects:
- kind: ServiceAccount
  name: discovery-server
  namespace: system
