# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: File manager API
  description: A simple file manager for uploading and downloading files.
  version: 0.0.1
  contact:
    name: TARDIS
    email: tadis@nop.telekom.de
    url: https://developer.telekom.de/
  license:
    name: Apache 2.0
  x-api-category: TARDIS
servers:
  - url: https://locahost:8080
    description: For local development
tags:
  - name: files
    description: Everything regarding storing and accessing files
  - name: uploading
    description: An endpoint to upload new files
  - name: downloading
    description: An endpoint to download existing files
paths:
  /v1/files/{env}/{group}/{team}:
    put:
      operationId: uploadFile
      summary: Upload a file
      description: >-
        Uploads a file to the server belonging to an environment, group and team.
      tags:
        - uploading
      parameters:
        - name: env
          in: path
          description: Name of the environment
          required: true
          schema:
            type: string
        - name: group
          in: path
          description: Name of the group
          required: true
          schema:
            type: string
        - name: team
          in: path
          description: Name of the team
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/FileUploadRequest'
      responses:
        '200':
          $ref: '#/components/responses/FileUploadResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /v1/files/{env}/{group}/{team}/{fileId}:
    get:
      operationId: downloadFile
      summary: Download a file
      description: >-
        Retrieves a file from the server at the specified path, belonging to the environment, group and team.
      tags:
        - downloading
      parameters:
        - name: env
          in: path
          description: Name of the environment
          required: true
          schema:
            type: string
        - name: group
          in: path
          description: Name of the group
          required: true
          schema:
            type: string
        - name: team
          in: path
          description: Name of the team
          required: true
          schema:
            type: string
        - name: fileId
          description: Id of the file returned after uploading
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/FileDownloadResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

components:
  requestBodies:
    FileUploadRequest:
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
  responses:
    FileUploadResponse:
      description: Successful upload of a file. Contains the assigned id.
      content:
        application/json:
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: string
    FileDownloadResponse:
      description: >-
        Successful download of a file with the specified id. Responds with the file contents.
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
    ErrorResponse:
      description: In case of any error, this object is returned
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ApiProblem'
  schemas:
    ApiProblem:
      description: Based on https://www.rfc-editor.org/rfc/rfc9457.html
      type: object
      required:
        - type
        - status
        - title
        - detail
      properties:
        type:
          type: string
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        instance:
          type: string


