# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This rule is not used by the project notification itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the notification.cp.ei.telekom.de.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/managed-by: kustomize
  name: notificationchannel-editor-role
rules:
- apiGroups:
  - notification.cp.ei.telekom.de
  resources:
  - notificationchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.cp.ei.telekom.de
  resources:
  - notificationchannels/status
  verbs:
  - get
