# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - notification.cp.ei.telekom.de
  resources:
  - notificationchannels
  - notifications
  - notificationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.cp.ei.telekom.de
  resources:
  - notificationchannels/finalizers
  - notifications/finalizers
  - notificationtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - notification.cp.ei.telekom.de
  resources:
  - notificationchannels/status
  - notifications/status
  - notificationtemplates/status
  verbs:
  - get
  - patch
  - update
