# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - approval--subscribe--updated--decider--mail--template.yaml
  - approval--subscribe--updated--requester--mail--template.yaml
  - approvalrequest--subscribe--created--decider--mail--template.yaml
  - approvalrequest--subscribe--updated--decider--mail--template.yaml
  - approvalrequest--subscribe--updated--requester--mail--template.yaml
  - onboarding-template-mail.yaml
  - team-members-changed-email-template.yaml
  - secret-rotation-completed-email-template.yaml
  - secret-rotation-expiring-email-template.yaml
  - token-rotated-email-template.yaml
