# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: file.cp.ei.telekom.de/v1
kind: ZoneServiceConfig
metadata:
  name: sample-zone
spec:
  api:
    clientID: sample-client
    clientSecret: secret-manager://sftp/sample-zone
    endpoint: https://sftp-api.example.com/base-path/
    issuer: https://issuer.example.com/auth/realms/default/protocol/openid-connect/token
  service:
    host: sftp.default.svc.cluster.local
    port: 3022
  serviceExternal:
    host: sftp.example.com
    port: 3022
