# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rover-cp.ei-telekom-de-v1-rover
  failurePolicy: Fail
  name: mrover.kb.io
  rules:
  - apiGroups:
    - rover.cp.ei.telekom.de
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rovers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rover-cp.ei-telekom-de-v1-rover
  failurePolicy: Fail
  name: vrover.kb.io
  rules:
  - apiGroups:
    - rover.cp.ei.telekom.de
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rovers
  sideEffects: None
