# Copyright 2026 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: tcp.ei.telekom.de/v1
kind: Rover
metadata:
  name: e2e-api-category-customer-blocked-subscription
spec:
  zone: dataplane1
  subscriptions:
    - basePath: /devops/e2e-api-category-infra-allowed/v1
      security:
        oauth2:
          username: test-user
          password: test-password
