# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to edit rovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rover
    app.kubernetes.io/managed-by: kustomize
  name: rover-editor-role
rules:
- apiGroups:
  - rover.cp.ei.telekom.de
  resources:
  - rovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rover.cp.ei.telekom.de
  resources:
  - rovers/status
  verbs:
  - get
