# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: admin.cp.ei.telekom.de/v1
kind: Environment
metadata:
  name: default
spec:
