# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: controlplane
---
apiVersion: admin.cp.ei.telekom.de/v1
kind: Environment
metadata:
  labels:
    cp.ei.telekom.de/environment: controlplane
  name: controlplane
  namespace: controlplane
spec:
---