# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

namespace: controlplane

labels:
  - includeSelectors: true
    pairs:
      cp.ei.telekom.de/environment: controlplane
      app.kubernetes.io/managed-by: kustomize

resources:
  - environment.yaml
  - zones
