# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admin.cp.ei.telekom.de/v1
kind: Zone
metadata:
  name: zone-a
spec:
  teamApis:
    apis: []
  identityProvider:
    admin:
      clientId: admin-cli
      userName: admin
      password: somePassword
    url: https://my-idp.example.com
  gateway:
    admin:
      clientSecret: someSecret
      url: https://my-gateway-admin.example.com/admin-api
    url: https://my-gateway.example.com
  redis:
    host: foo
    password: topsecret
    port: 6379
