# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

backend:
  type: buckets
  endpoint: "s3.amazonaws.com"
  sts_endpoint: "https://sts.amazonaws.com"
  bucket_name: "my-s3-bucket" # Replace with your actual S3 bucket name
  role_arn: "arn:aws:iam::123456789012:role/my-sample-role" # Replace with your actual IAM role ARN
  token_path: "/var/run/secrets/file-manager/file-manager-token"


security:
  enabled: false # client needs to provide the authentication token in the request header