# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

backend:
  type: kubernetes

security:
  enabled: true
  # access_config:
  # # Testing
  # - service_account_name: default
  #   deployment_name: secret-client-shell
  #   namespace: secret-manager-client
  #   allowed_access: 
  #   - secrets_read
  #   - secrets_write
  #   - onboarding_write

  # # Controlplane
  # - service_account_name: identity-controller-manager
  #   deployment_name: identity-controller-manager
  #   namespace: identity-system
  #   allowed_access: 
  #   - secrets_read
  # - service_account_name: gateway-controller-manager
  #   deployment_name: gateway-controller-manager
  #   namespace: gateway-system
  #   allowed_access: 
  #   - secrets_read
  # - service_account_name: organization-controller-manager
  #   deployment_name: organization-controller-manager
  #   namespace: organization-system
  #   allowed_access: 
  #   - onboarding_write
  #   - secrets_write
  #   - secrets_read
  # - service_account_name: rover-controller-manager
  #   deployment_name: rover-controller-manager
  #   namespace: rover-system
  #   allowed_access: 
  #   - onboarding_write
  #   - secrets_write
  #   - secrets_read