// SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0
package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"sort"

	"entgo.io/contrib/entgql"
	"github.com/go-logr/logr"
	"github.com/telekom/controlplane/controlplane-api/ent"
	"github.com/telekom/controlplane/controlplane-api/ent/api"
	"github.com/telekom/controlplane/controlplane-api/ent/apiexposure"
	"github.com/telekom/controlplane/controlplane-api/ent/apisubscription"
	"github.com/telekom/controlplane/controlplane-api/ent/approval"
	"github.com/telekom/controlplane/controlplane-api/ent/eventexposure"
	"github.com/telekom/controlplane/controlplane-api/ent/eventsubscription"
	"github.com/telekom/controlplane/controlplane-api/ent/listener"
	gqlmodel "github.com/telekom/controlplane/controlplane-api/internal/resolvers/model"
	"github.com/telekom/controlplane/controlplane-api/internal/viewer"
	"github.com/telekom/controlplane/controlplane-api/pkg/model"
)

// SpecificationURL is the resolver for the specificationUrl field.
func (r *apiResolver) SpecificationURL(ctx context.Context, obj *ent.Api) (*string, error) {
	return r.buildSpecificationURL(obj.Specification)
}

// ActiveExposure is the resolver for the activeExposure field.
// Returns the active exposure for this API, or nil if none is active.
func (r *apiResolver) ActiveExposure(ctx context.Context, obj *ent.Api) (*model.ApiExposureInfo, error) {
	// SystemContext: The exposure may belong to another tenant; privacy rules would
	// block the cross-tenant traversal. We return a reduced Info type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	exp, err := obj.QueryExposures().
		Where(apiexposure.Active(true)).
		WithOwner(func(q *ent.ApplicationQuery) {
			q.WithOwnerTeam(func(q *ent.TeamQuery) {
				q.WithGroup()
			})
		}).
		Only(sysCtx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("loading active exposure for api %d: %w", obj.ID, err)
	}

	app := exp.Edges.Owner
	team := app.Edges.OwnerTeam
	group, groupErr := team.Edges.GroupOrErr()
	if groupErr != nil {
		if !ent.IsNotFound(groupErr) && !ent.IsNotLoaded(groupErr) {
			return nil, fmt.Errorf("loading group edge for team %d: %w", team.ID, groupErr)
		}
		group = nil
	}
	return mapApiExposureInfo(exp, app, team, group), nil
}

// Owner is the resolver for the owner field.
func (r *apiResolver) Owner(ctx context.Context, obj *ent.Api) (*model.TeamInfo, error) {
	// SystemContext: The owning team may belong to a different tenant than the
	// querying viewer. We return a reduced TeamInfo type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	log := logr.FromContextOrDiscard(ctx)

	team, err := obj.Edges.OwnerOrErr()
	if ent.IsNotLoaded(err) {
		team, err = obj.QueryOwner().Only(sysCtx)
	}
	if err != nil {
		log.Info("Failed to resolve owner team for api",
			"apiID", obj.ID, "namespace", obj.Namespace, "basePath", obj.BasePath, "error", err)
		return nil, fmt.Errorf("resolving owner team for api %d: %w", obj.ID, err)
	}

	group, err := team.Edges.GroupOrErr()
	if ent.IsNotLoaded(err) {
		group, err = team.QueryGroup().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading group for team %d: %w", team.ID, err)
	}
	if ent.IsNotFound(err) {
		group = nil
	}

	return mapTeamInfo(team, group), nil
}

// Subscriptions is the resolver for the subscriptions field.
// Returns reduced ApiSubscriptionInfo types for cross-tenant safety.
func (r *apiExposureResolver) Subscriptions(ctx context.Context, obj *ent.ApiExposure) ([]*model.ApiSubscriptionInfo, error) {
	// SystemContext: Subscriptions belong to other tenants; privacy rules would
	// block the cross-tenant traversal. We return a reduced Info type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	subs, err := obj.QuerySubscriptions().
		WithOwner(func(q *ent.ApplicationQuery) {
			q.WithOwnerTeam(func(q *ent.TeamQuery) {
				q.WithGroup()
			})
		}).
		All(sysCtx)
	if err != nil {
		return nil, fmt.Errorf("loading subscriptions for api exposure %d: %w", obj.ID, err)
	}

	result := make([]*model.ApiSubscriptionInfo, len(subs))
	for i, sub := range subs {
		app := sub.Edges.Owner
		team := app.Edges.OwnerTeam
		group, groupErr := team.Edges.GroupOrErr()
		if groupErr != nil {
			if !ent.IsNotFound(groupErr) && !ent.IsNotLoaded(groupErr) {
				return nil, fmt.Errorf("loading group edge for team %d: %w", team.ID, groupErr)
			}
			group = nil
		}
		result[i] = mapApiSubscriptionInfo(sub, app, team, group)
	}
	return result, nil
}

// Listeners is the resolver for the listeners field.
func (r *apiExposureResolver) Listeners(ctx context.Context, obj *ent.ApiExposure) ([]*model.ListenerInfo, error) {
	listeners, err := withListenerInfo(obj.QueryListeners()).
		Where(listener.StatusPhaseEQ(listener.StatusPhaseReady)).
		All(viewer.SystemContext(ctx))
	if err != nil {
		return nil, fmt.Errorf("loading listeners for api exposure %d: %w", obj.ID, err)
	}
	return mapListenerInfos(listeners)
}

// Visibility is the resolver for the visibility field.
func (r *apiExposureInfoResolver) Visibility(ctx context.Context, obj *model.ApiExposureInfo) (apiexposure.Visibility, error) {
	return apiexposure.Visibility(obj.Visibility), nil
}

// Features is the resolver for the features field.
func (r *apiExposureInfoResolver) Features(ctx context.Context, obj *model.ApiExposureInfo) ([]gqlmodel.APIExposureFeature, error) {
	result := make([]gqlmodel.APIExposureFeature, len(obj.Features))
	for i, f := range obj.Features {
		result[i] = gqlmodel.APIExposureFeature(f)
	}
	return result, nil
}

// Target is the resolver for the target field.
// Returns reduced ApiExposureInfo type for cross-tenant safety.
func (r *apiSubscriptionResolver) Target(ctx context.Context, obj *ent.ApiSubscription) (*model.ApiExposureInfo, error) {
	// SystemContext: The target exposure belongs to another tenant; privacy rules
	// would block this traversal. We return a reduced Info type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)

	exposure, err := obj.Edges.TargetOrErr()
	if ent.IsNotLoaded(err) {
		exposure, err = obj.QueryTarget().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading target for api subscription %d: %w", obj.ID, err)
	}

	return loadApiExposureInfo(sysCtx, exposure)
}

// Listeners is the resolver for the listeners field.
func (r *apiSubscriptionResolver) Listeners(ctx context.Context, obj *ent.ApiSubscription) ([]*model.ListenerInfo, error) {
	listeners, err := withListenerInfo(obj.QueryListeners()).
		Where(listener.StatusPhaseEQ(listener.StatusPhaseReady)).
		All(viewer.SystemContext(ctx))
	if err != nil {
		return nil, fmt.Errorf("loading listeners for api subscription %d: %w", obj.ID, err)
	}
	return mapListenerInfos(listeners)
}

// StatusPhase is the resolver for the statusPhase field.
func (r *apiSubscriptionInfoResolver) StatusPhase(ctx context.Context, obj *model.ApiSubscriptionInfo) (*apisubscription.StatusPhase, error) {
	if obj.StatusPhase == nil {
		return nil, nil
	}
	s := apisubscription.StatusPhase(*obj.StatusPhase)
	return &s, nil
}

// OwnerTeam is the resolver for the ownerTeam field.
func (r *applicationResolver) OwnerTeam(ctx context.Context, obj *ent.Application) (*model.TeamInfo, error) {
	// SystemContext: The owning team may belong to a different tenant than the
	// querying viewer. We return a reduced TeamInfo type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	team, err := obj.Edges.OwnerTeamOrErr()
	if ent.IsNotLoaded(err) {
		team, err = obj.QueryOwnerTeam().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading owner team for application %d: %w", obj.ID, err)
	}

	group, err := team.Edges.GroupOrErr()
	if ent.IsNotLoaded(err) {
		group, err = team.QueryGroup().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading group for team %d: %w", team.ID, err)
	}
	if ent.IsNotFound(err) {
		group = nil
	}

	return mapTeamInfo(team, group), nil
}

// Listeners is the resolver for the listeners field.
func (r *applicationResolver) Listeners(ctx context.Context, obj *ent.Application, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.ListenerWhereInput) (*ent.ListenerConnection, error) {
	return withListenerInfo(obj.QueryListeners()).
		Paginate(viewer.SystemContext(ctx), after, first, before, last, ent.WithListenerFilter(where.Filter))
}

// Subscription is the resolver for the subscription field.
// Returns the related subscription as a SubscriptionInfo union (ApiSubscriptionInfo or EventSubscriptionInfo).
func (r *approvalResolver) Subscription(ctx context.Context, obj *ent.Approval) (gqlmodel.SubscriptionInfo, error) {
	// SystemContext: The subscription belongs to the requesting tenant, but the
	// traversal path (approval → subscription → owner) crosses privacy boundaries.
	// We return reduced Info types to limit exposure.
	sysCtx := viewer.SystemContext(ctx)

	// Try API subscription first.
	apiSub, err := obj.Edges.APISubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		apiSub, err = obj.QueryAPISubscription().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading api subscription for approval %d: %w", obj.ID, err)
	}
	if apiSub != nil {
		return loadApiSubscriptionInfo(sysCtx, apiSub)
	}

	// Fall back to event subscription.
	eventSub, err := obj.Edges.EventSubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		eventSub, err = obj.QueryEventSubscription().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading event subscription for approval %d: %w", obj.ID, err)
	}
	if eventSub != nil {
		return loadEventSubscriptionInfo(sysCtx, eventSub)
	}

	listenerTarget, err := obj.Edges.ListenerOrErr()
	if ent.IsNotLoaded(err) {
		listenerTarget, err = obj.QueryListener().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading listener for approval %d: %w", obj.ID, err)
	}
	if listenerTarget != nil {
		return loadListenerInfo(sysCtx, r.client, listenerTarget)
	}
	consumerListener, err := obj.Edges.ConsumerListenerOrErr()
	if ent.IsNotLoaded(err) {
		consumerListener, err = obj.QueryConsumerListener().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading consumer listener for approval %d: %w", obj.ID, err)
	}
	if consumerListener != nil {
		return loadListenerInfo(sysCtx, r.client, consumerListener)
	}

	return nil, fmt.Errorf("approval %d has no related subscription", obj.ID)
}

// Strategy is the resolver for the strategy field.
func (r *approvalConfigResolver) Strategy(ctx context.Context, obj *model.ApprovalConfig) (approval.Strategy, error) {
	return approval.Strategy(obj.Strategy), nil
}

// Subscription is the resolver for the subscription field.
// Returns the related subscription as a SubscriptionInfo union (ApiSubscriptionInfo or EventSubscriptionInfo).
func (r *approvalRequestResolver) Subscription(ctx context.Context, obj *ent.ApprovalRequest) (gqlmodel.SubscriptionInfo, error) {
	// SystemContext: Same rationale as approvalResolver.Subscription — the traversal
	// path crosses privacy boundaries; reduced Info types limit exposure.
	sysCtx := viewer.SystemContext(ctx)

	// Try API subscription first.
	apiSub, err := obj.Edges.APISubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		apiSub, err = obj.QueryAPISubscription().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading api subscription for approval request %d: %w", obj.ID, err)
	}
	if apiSub != nil {
		return loadApiSubscriptionInfo(sysCtx, apiSub)
	}

	// Fall back to event subscription.
	eventSub, err := obj.Edges.EventSubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		eventSub, err = obj.QueryEventSubscription().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading event subscription for approval request %d: %w", obj.ID, err)
	}

	if eventSub != nil {
		return loadEventSubscriptionInfo(sysCtx, eventSub)
	}

	listenerTarget, err := obj.Edges.ListenerOrErr()
	if ent.IsNotLoaded(err) {
		listenerTarget, err = obj.QueryListener().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading listener for approval request %d: %w", obj.ID, err)
	}
	if listenerTarget != nil {
		return loadListenerInfo(sysCtx, r.client, listenerTarget)
	}

	return nil, fmt.Errorf("approval request %d has no related subscription", obj.ID)
}

// Approval is the resolver for the approval field.
// Traverses ApprovalRequest → ApiSubscription/EventSubscription → Approval.
// Returns nil if no Approval exists yet (request not decided).
func (r *approvalRequestResolver) Approval(ctx context.Context, obj *ent.ApprovalRequest) (*ent.Approval, error) {
	// Try API subscription path first.
	apiSub, err := obj.Edges.APISubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		apiSub, err = obj.QueryAPISubscription().Only(ctx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading api subscription for approval request %d: %w", obj.ID, err)
	}
	if apiSub != nil {
		appr, err := apiSub.QueryApproval().Only(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, nil
			}
			return nil, fmt.Errorf("loading approval for api subscription %d: %w", apiSub.ID, err)
		}
		return appr, nil
	}

	listenerTarget, listenerErr := obj.Edges.ListenerOrErr()
	if ent.IsNotLoaded(listenerErr) {
		listenerTarget, listenerErr = obj.QueryListener().Only(ctx)
	}
	if listenerErr != nil && !ent.IsNotFound(listenerErr) {
		return nil, fmt.Errorf("loading listener for approval request %d: %w", obj.ID, listenerErr)
	}
	if listenerTarget != nil {
		var approvalQuery *ent.ApprovalQuery
		var gate string
		switch obj.Action {
		case "listen-provider":
			approvalQuery = listenerTarget.QueryProviderApproval()
			gate = "provider"
		case "listen-consumer":
			approvalQuery = listenerTarget.QueryConsumerApproval()
			gate = "consumer"
		default:
			return nil, fmt.Errorf("unknown listener approval action %q for approval request %d", obj.Action, obj.ID)
		}
		matchedApproval, err := approvalQuery.Only(ctx)
		if ent.IsNotFound(err) {
			return nil, nil
		}
		if err != nil {
			return nil, fmt.Errorf("loading %s approval for listener %d: %w", gate, listenerTarget.ID, err)
		}
		return matchedApproval, nil
	}

	// Fall back to event subscription path.
	eventSub, err := obj.Edges.EventSubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		eventSub, err = obj.QueryEventSubscription().Only(ctx)
	}
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("loading event subscription for approval request %d: %w", obj.ID, err)
	}

	appr, err := eventSub.QueryApproval().Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("loading approval for event subscription %d: %w", eventSub.ID, err)
	}
	return appr, nil
}

// Action is the resolver for the action field.
func (r *availableTransitionResolver) Action(ctx context.Context, obj *model.AvailableTransition) (gqlmodel.ApprovalAction, error) {
	return gqlmodel.ApprovalAction(obj.Action), nil
}

// ToState is the resolver for the toState field.
func (r *availableTransitionResolver) ToState(ctx context.Context, obj *model.AvailableTransition) (approval.State, error) {
	return approval.State(obj.ToState), nil
}

// Password is the resolver for the password field.
func (r *basicAuthCredentialsResolver) Password(ctx context.Context, obj *model.BasicAuthCredentials) (string, error) {
	resolved, err := r.secrets.Resolve(ctx, &obj.Password, "password")
	if err != nil {
		return "", err
	}
	if resolved == nil {
		return "", nil
	}
	return *resolved, nil
}

// ResultingState is the resolver for the resultingState field.
func (r *decisionResolver) ResultingState(ctx context.Context, obj *model.Decision) (*approval.State, error) {
	if obj.ResultingState == nil {
		return nil, nil
	}
	s := approval.State(*obj.ResultingState)
	return &s, nil
}

// Payload is the resolver for the payload field.
func (r *eventDeliveryResolver) Payload(ctx context.Context, obj *model.EventDelivery) (gqlmodel.PayloadType, error) {
	return gqlmodel.PayloadType(obj.Payload), nil
}

// Subscriptions is the resolver for the subscriptions field.
// Returns reduced EventSubscriptionInfo types for cross-tenant safety.
func (r *eventExposureResolver) Subscriptions(ctx context.Context, obj *ent.EventExposure) ([]*model.EventSubscriptionInfo, error) {
	// SystemContext: Subscriptions belong to other tenants; privacy rules would
	// block the cross-tenant traversal. We return a reduced Info type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	subs, err := obj.QuerySubscriptions().
		WithOwner(func(q *ent.ApplicationQuery) {
			q.WithOwnerTeam(func(q *ent.TeamQuery) {
				q.WithGroup()
			})
		}).
		All(sysCtx)
	if err != nil {
		return nil, fmt.Errorf("loading subscriptions for event exposure %d: %w", obj.ID, err)
	}

	result := make([]*model.EventSubscriptionInfo, len(subs))
	for i, sub := range subs {
		app := sub.Edges.Owner
		team := app.Edges.OwnerTeam
		group, groupErr := team.Edges.GroupOrErr()
		if groupErr != nil {
			if !ent.IsNotFound(groupErr) && !ent.IsNotLoaded(groupErr) {
				return nil, fmt.Errorf("loading group edge for team %d: %w", team.ID, groupErr)
			}
			group = nil
		}
		result[i] = mapEventSubscriptionInfo(sub, app, team, group)
	}
	return result, nil
}

// Visibility is the resolver for the visibility field.
func (r *eventExposureInfoResolver) Visibility(ctx context.Context, obj *model.EventExposureInfo) (eventexposure.Visibility, error) {
	return eventexposure.Visibility(obj.Visibility), nil
}

// Target is the resolver for the target field.
// Returns reduced EventExposureInfo type for cross-tenant safety.
func (r *eventSubscriptionResolver) Target(ctx context.Context, obj *ent.EventSubscription) (*model.EventExposureInfo, error) {
	// SystemContext: The target exposure belongs to another tenant; privacy rules
	// would block this traversal. We return a reduced Info type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)

	exposure, err := obj.Edges.TargetOrErr()
	if ent.IsNotLoaded(err) {
		exposure, err = obj.QueryTarget().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading target for event subscription %d: %w", obj.ID, err)
	}

	return loadEventExposureInfo(sysCtx, exposure)
}

// DeliveryType is the resolver for the deliveryType field.
func (r *eventSubscriptionInfoResolver) DeliveryType(ctx context.Context, obj *model.EventSubscriptionInfo) (eventsubscription.DeliveryType, error) {
	return eventsubscription.DeliveryType(obj.DeliveryType), nil
}

// StatusPhase is the resolver for the statusPhase field.
func (r *eventSubscriptionInfoResolver) StatusPhase(ctx context.Context, obj *model.EventSubscriptionInfo) (*eventsubscription.StatusPhase, error) {
	if obj.StatusPhase == nil {
		return nil, nil
	}
	s := eventsubscription.StatusPhase(*obj.StatusPhase)
	return &s, nil
}

// SpecificationURL is the resolver for the specificationUrl field.
func (r *eventTypeResolver) SpecificationURL(ctx context.Context, obj *ent.EventType) (*string, error) {
	return r.buildSpecificationURL(obj.Specification)
}

// ActiveExposure is the resolver for the activeExposure field.
// Returns the active exposure for this event type, or nil if none is active.
func (r *eventTypeResolver) ActiveExposure(ctx context.Context, obj *ent.EventType) (*model.EventExposureInfo, error) {
	// SystemContext: The exposure may belong to another tenant; privacy rules would
	// block the cross-tenant traversal. We return a reduced Info type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	exp, err := obj.QueryExposures().
		Where(eventexposure.Active(true)).
		WithOwner(func(q *ent.ApplicationQuery) {
			q.WithOwnerTeam(func(q *ent.TeamQuery) {
				q.WithGroup()
			})
		}).
		Only(sysCtx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("loading active exposure for event type %d: %w", obj.ID, err)
	}

	app := exp.Edges.Owner
	team := app.Edges.OwnerTeam
	group, groupErr := team.Edges.GroupOrErr()
	if groupErr != nil {
		if !ent.IsNotFound(groupErr) && !ent.IsNotLoaded(groupErr) {
			return nil, fmt.Errorf("loading group edge for team %d: %w", team.ID, groupErr)
		}
		group = nil
	}
	return mapEventExposureInfo(exp, app, team, group), nil
}

// Owner is the resolver for the owner field.
func (r *eventTypeResolver) Owner(ctx context.Context, obj *ent.EventType) (*model.TeamInfo, error) {
	// SystemContext: The owning team may belong to a different tenant than the
	// querying viewer. We return a reduced TeamInfo type to limit exposure.
	sysCtx := viewer.SystemContext(ctx)
	log := logr.FromContextOrDiscard(ctx)

	team, err := obj.Edges.OwnerOrErr()
	if ent.IsNotLoaded(err) {
		team, err = obj.QueryOwner().Only(sysCtx)
	}
	if err != nil {
		log.Info("Failed to resolve owner team for event type",
			"eventTypeID", obj.ID, "namespace", obj.Namespace, "eventType", obj.EventType, "error", err)
		return nil, fmt.Errorf("resolving owner team for event type %d: %w", obj.ID, err)
	}

	group, err := team.Edges.GroupOrErr()
	if ent.IsNotLoaded(err) {
		group, err = team.QueryGroup().Only(sysCtx)
	}
	if err != nil && !ent.IsNotFound(err) {
		return nil, fmt.Errorf("loading group for team %d: %w", team.ID, err)
	}
	if ent.IsNotFound(err) {
		group = nil
	}

	return mapTeamInfo(team, group), nil
}

// Schema is the resolver for the Schema field.
func (r *externalIdResolver) Schema(ctx context.Context, obj *model.ExternalId) (string, error) {
	return obj.Scheme, nil
}

// TokenRequest is the resolver for the tokenRequest field.
func (r *externalIdentityProviderResolver) TokenRequest(ctx context.Context, obj *model.ExternalIdentityProvider) (*gqlmodel.TokenRequestMethod, error) {
	if obj.TokenRequest == nil {
		return nil, nil
	}
	m := gqlmodel.TokenRequestMethod(*obj.TokenRequest)
	if !m.IsValid() {
		return nil, nil
	}
	return &m, nil
}

// ResourceName is the resolver for the resourceName field.
func (r *listenerResolver) ResourceName(ctx context.Context, obj *ent.Listener) (string, error) {
	sysCtx := viewer.SystemContext(ctx)
	exposure, err := obj.Edges.ExposureOrErr()
	if ent.IsNotLoaded(err) {
		exposure, err = obj.QueryExposure().Only(sysCtx)
	}
	if err != nil {
		return "", fmt.Errorf("loading exposure for listener %d: %w", obj.ID, err)
	}
	apiDefinition, err := exposure.Edges.APIOrErr()
	if ent.IsNotLoaded(err) {
		apiDefinition, err = exposure.QueryAPI().Only(sysCtx)
	}
	if err != nil {
		return "", fmt.Errorf("loading api for listener %d: %w", obj.ID, err)
	}
	if apiDefinition.Name == nil || *apiDefinition.Name == "" {
		return "", fmt.Errorf("listener %d references api %d without a projected kubernetes name", obj.ID, apiDefinition.ID)
	}
	return *apiDefinition.Name, nil
}

// Approved is the resolver for the approved field.
func (r *listenerResolver) Approved(ctx context.Context, obj *ent.Listener) (bool, error) {
	providerApproval, err := obj.Edges.ProviderApprovalOrErr()
	if ent.IsNotLoaded(err) {
		providerApproval, err = obj.QueryProviderApproval().Only(viewer.SystemContext(ctx))
	}
	if ent.IsNotFound(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("loading provider approval for listener %d: %w", obj.ID, err)
	}
	if providerApproval.State != approval.StateGranted {
		return false, nil
	}
	consumerApproval, err := obj.Edges.ConsumerApprovalOrErr()
	if ent.IsNotLoaded(err) {
		consumerApproval, err = obj.QueryConsumerApproval().Only(viewer.SystemContext(ctx))
	}
	if ent.IsNotFound(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("loading consumer approval for listener %d: %w", obj.ID, err)
	}
	return consumerApproval.State == approval.StateGranted, nil
}

// APIBasePath is the resolver for the apiBasePath field.
func (r *listenerResolver) APIBasePath(ctx context.Context, obj *ent.Listener) (string, error) {
	return obj.APIBasePath, nil
}

// RequestFilter is the resolver for the requestFilter field.
func (r *listenerResolver) RequestFilter(ctx context.Context, obj *ent.Listener) (*model.ListenerFilter, error) {
	return obj.RequestFilter, nil
}

// ResponseFilter is the resolver for the responseFilter field.
func (r *listenerResolver) ResponseFilter(ctx context.Context, obj *ent.Listener) (*model.ListenerFilter, error) {
	return obj.ResponseFilter, nil
}

// Application is the resolver for the application field.
func (r *listenerResolver) Application(ctx context.Context, obj *ent.Listener) (*model.ApplicationInfo, error) {
	sysCtx := viewer.SystemContext(ctx)
	application, err := obj.Edges.ApplicationOrErr()
	if ent.IsNotLoaded(err) {
		application, err = obj.QueryApplication().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading listener application for listener %d: %w", obj.ID, err)
	}
	return loadApplicationInfo(sysCtx, application)
}

// Consumer is the resolver for the consumer field.
func (r *listenerResolver) Consumer(ctx context.Context, obj *ent.Listener) (*model.ApplicationInfo, error) {
	sysCtx := viewer.SystemContext(ctx)
	subscription, err := obj.Edges.SubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		subscription, err = obj.QuerySubscription().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading subscription for listener %d: %w", obj.ID, err)
	}
	application, err := subscription.Edges.OwnerOrErr()
	if ent.IsNotLoaded(err) {
		application, err = subscription.QueryOwner().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading consumer application for listener %d: %w", obj.ID, err)
	}
	return loadApplicationInfo(sysCtx, application)
}

// Provider is the resolver for the provider field.
func (r *listenerResolver) Provider(ctx context.Context, obj *ent.Listener) (*model.ApplicationInfo, error) {
	sysCtx := viewer.SystemContext(ctx)
	exposure, err := obj.Edges.ExposureOrErr()
	if ent.IsNotLoaded(err) {
		exposure, err = obj.QueryExposure().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading exposure for listener %d: %w", obj.ID, err)
	}
	application, err := exposure.Edges.OwnerOrErr()
	if ent.IsNotLoaded(err) {
		application, err = exposure.QueryOwner().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading provider application for listener %d: %w", obj.ID, err)
	}
	return loadApplicationInfo(sysCtx, application)
}

// Subscription is the resolver for the subscription field.
func (r *listenerResolver) Subscription(ctx context.Context, obj *ent.Listener) (*model.ApiSubscriptionInfo, error) {
	sysCtx := viewer.SystemContext(ctx)
	subscription, err := obj.Edges.SubscriptionOrErr()
	if ent.IsNotLoaded(err) {
		subscription, err = obj.QuerySubscription().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading subscription for listener %d: %w", obj.ID, err)
	}
	return loadApiSubscriptionInfo(sysCtx, subscription)
}

// Exposure is the resolver for the exposure field.
func (r *listenerResolver) Exposure(ctx context.Context, obj *ent.Listener) (*model.ApiExposureInfo, error) {
	sysCtx := viewer.SystemContext(ctx)
	exposure, err := obj.Edges.ExposureOrErr()
	if ent.IsNotLoaded(err) {
		exposure, err = obj.QueryExposure().Only(sysCtx)
	}
	if err != nil {
		return nil, fmt.Errorf("loading exposure for listener %d: %w", obj.ID, err)
	}
	return loadApiExposureInfo(sysCtx, exposure)
}

// ProviderApproval is the resolver for the providerApproval field.
func (r *listenerResolver) ProviderApproval(ctx context.Context, obj *ent.Listener) (*ent.Approval, error) {
	providerApproval, err := obj.Edges.ProviderApprovalOrErr()
	if ent.IsNotLoaded(err) {
		providerApproval, err = obj.QueryProviderApproval().Only(ctx)
	}
	if ent.IsNotFound(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("loading provider approval for listener %d: %w", obj.ID, err)
	}
	return providerApproval, nil
}

// ConsumerApproval is the resolver for the consumerApproval field.
func (r *listenerResolver) ConsumerApproval(ctx context.Context, obj *ent.Listener) (*ent.Approval, error) {
	consumerApproval, err := obj.Edges.ConsumerApprovalOrErr()
	if ent.IsNotLoaded(err) {
		consumerApproval, err = obj.QueryConsumerApproval().Only(ctx)
	}
	if ent.IsNotFound(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("loading consumer approval for listener %d: %w", obj.ID, err)
	}
	return consumerApproval, nil
}

// Trigger is the resolver for the trigger field.
func (r *listenerFilterResolver) Trigger(ctx context.Context, obj *model.ListenerFilter) (map[string]any, error) {
	if obj.Trigger == nil {
		return nil, nil
	}
	trigger := make(map[string]any, len(obj.Trigger))
	for key, value := range obj.Trigger {
		trigger[key] = value
	}
	return trigger, nil
}

// Payload is the resolver for the payload field.
func (r *listenerFilterResolver) Payload(ctx context.Context, obj *model.ListenerFilter) ([]string, error) {
	if obj.Payload == nil {
		return []string{}, nil
	}
	return obj.Payload, nil
}

// ClientSecret is the resolver for the clientSecret field.
func (r *oAuth2ClientCredentialsResolver) ClientSecret(ctx context.Context, obj *model.OAuth2ClientCredentials) (*string, error) {
	return r.secrets.Resolve(ctx, obj.ClientSecret, "clientSecret")
}

// ClientKey is the resolver for the clientKey field.
func (r *oAuth2ClientCredentialsResolver) ClientKey(ctx context.Context, obj *model.OAuth2ClientCredentials) (*string, error) {
	return r.secrets.Resolve(ctx, obj.ClientKey, "clientKey")
}

// APICategories is the resolver for the apiCategories field.
func (r *queryResolver) APICategories(ctx context.Context) ([]*gqlmodel.APICategory, error) {
	// SystemContext: Categories are visible to all authenticated users regardless of tenant.
	sysCtx := viewer.SystemContext(ctx)
	names, err := r.client.Api.Query().
		Where(
			api.CategoryNotNil(),
			api.CategoryNEQ(""),
		).
		Unique(true).
		Select(api.FieldCategory).
		Strings(sysCtx)
	if err != nil {
		return nil, fmt.Errorf("querying distinct api categories: %w", err)
	}
	sort.Strings(names)
	categories := make([]*gqlmodel.APICategory, len(names))
	for i, name := range names {
		categories[i] = &gqlmodel.APICategory{Name: name}
	}
	return categories, nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context, where *ent.GroupWhereInput) ([]*ent.Group, error) {
	query := r.client.Group.Query()
	if where != nil {
		p, err := where.P()
		if err != nil {
			return nil, fmt.Errorf("invalid filter: %w", err)
		}
		query = query.Where(p)
	}
	return query.All(ctx)
}

// Mode is the resolver for the mode field.
func (r *responseFilterResolver) Mode(ctx context.Context, obj *model.ResponseFilter) (*gqlmodel.ResponseFilterMode, error) {
	if obj.Mode == "" {
		return nil, nil
	}
	m := gqlmodel.ResponseFilterMode(obj.Mode)
	return &m, nil
}

// Attributes is the resolver for the attributes field.
func (r *selectionFilterResolver) Attributes(ctx context.Context, obj *model.SelectionFilter) (map[string]any, error) {
	if obj.Attributes == nil {
		return nil, nil
	}
	result := make(map[string]any, len(obj.Attributes))
	for k, v := range obj.Attributes {
		result[k] = v
	}
	return result, nil
}

// TokenURL is the resolver for the tokenUrl field.
func (r *zoneResolver) TokenURL(ctx context.Context, obj *ent.Zone) (*string, error) {
	if obj.IssuerURL == nil {
		return nil, nil
	}

	tokenURL := *obj.IssuerURL + "/protocol/openid-connect/token"
	return &tokenURL, nil
}

// ApiExposureInfo returns ApiExposureInfoResolver implementation.
func (r *Resolver) ApiExposureInfo() ApiExposureInfoResolver { return &apiExposureInfoResolver{r} }

// ApiSubscriptionInfo returns ApiSubscriptionInfoResolver implementation.
func (r *Resolver) ApiSubscriptionInfo() ApiSubscriptionInfoResolver {
	return &apiSubscriptionInfoResolver{r}
}

// ApprovalConfig returns ApprovalConfigResolver implementation.
func (r *Resolver) ApprovalConfig() ApprovalConfigResolver { return &approvalConfigResolver{r} }

// AvailableTransition returns AvailableTransitionResolver implementation.
func (r *Resolver) AvailableTransition() AvailableTransitionResolver {
	return &availableTransitionResolver{r}
}

// BasicAuthCredentials returns BasicAuthCredentialsResolver implementation.
func (r *Resolver) BasicAuthCredentials() BasicAuthCredentialsResolver {
	return &basicAuthCredentialsResolver{r}
}

// Decision returns DecisionResolver implementation.
func (r *Resolver) Decision() DecisionResolver { return &decisionResolver{r} }

// EventDelivery returns EventDeliveryResolver implementation.
func (r *Resolver) EventDelivery() EventDeliveryResolver { return &eventDeliveryResolver{r} }

// EventExposureInfo returns EventExposureInfoResolver implementation.
func (r *Resolver) EventExposureInfo() EventExposureInfoResolver {
	return &eventExposureInfoResolver{r}
}

// EventSubscriptionInfo returns EventSubscriptionInfoResolver implementation.
func (r *Resolver) EventSubscriptionInfo() EventSubscriptionInfoResolver {
	return &eventSubscriptionInfoResolver{r}
}

// ExternalId returns ExternalIdResolver implementation.
func (r *Resolver) ExternalId() ExternalIdResolver { return &externalIdResolver{r} }

// ExternalIdentityProvider returns ExternalIdentityProviderResolver implementation.
func (r *Resolver) ExternalIdentityProvider() ExternalIdentityProviderResolver {
	return &externalIdentityProviderResolver{r}
}

// ListenerFilter returns ListenerFilterResolver implementation.
func (r *Resolver) ListenerFilter() ListenerFilterResolver { return &listenerFilterResolver{r} }

// OAuth2ClientCredentials returns OAuth2ClientCredentialsResolver implementation.
func (r *Resolver) OAuth2ClientCredentials() OAuth2ClientCredentialsResolver {
	return &oAuth2ClientCredentialsResolver{r}
}

// ResponseFilter returns ResponseFilterResolver implementation.
func (r *Resolver) ResponseFilter() ResponseFilterResolver { return &responseFilterResolver{r} }

// SelectionFilter returns SelectionFilterResolver implementation.
func (r *Resolver) SelectionFilter() SelectionFilterResolver { return &selectionFilterResolver{r} }

type (
	apiExposureInfoResolver          struct{ *Resolver }
	apiSubscriptionInfoResolver      struct{ *Resolver }
	approvalConfigResolver           struct{ *Resolver }
	availableTransitionResolver      struct{ *Resolver }
	basicAuthCredentialsResolver     struct{ *Resolver }
	decisionResolver                 struct{ *Resolver }
	eventDeliveryResolver            struct{ *Resolver }
	eventExposureInfoResolver        struct{ *Resolver }
	eventSubscriptionInfoResolver    struct{ *Resolver }
	externalIdResolver               struct{ *Resolver }
	externalIdentityProviderResolver struct{ *Resolver }
	listenerFilterResolver           struct{ *Resolver }
	oAuth2ClientCredentialsResolver  struct{ *Resolver }
	responseFilterResolver           struct{ *Resolver }
	selectionFilterResolver          struct{ *Resolver }
)
