// SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260425061340-097bc33cf46c DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	OAuth2Scopes oAuth2ContextKey = "OAuth2.Scopes"
)

// Defines values for AiExposureVariant.
const (
	AiExposureVariantMCP            AiExposureVariant = "MCP"
	AiExposureVariantTELECONTEXTMCP AiExposureVariant = "TELECONTEXTMCP"
)

// Valid indicates whether the value is a known member of the AiExposureVariant enum.
func (e AiExposureVariant) Valid() bool {
	switch e {
	case AiExposureVariantMCP:
		return true
	case AiExposureVariantTELECONTEXTMCP:
		return true
	default:
		return false
	}
}

// Defines values for AiExposureInfoType.
const (
	AiExposureInfoTypeAi AiExposureInfoType = "ai"
)

// Valid indicates whether the value is a known member of the AiExposureInfoType enum.
func (e AiExposureInfoType) Valid() bool {
	switch e {
	case AiExposureInfoTypeAi:
		return true
	default:
		return false
	}
}

// Defines values for AiExposureInfoVariant.
const (
	AiExposureInfoVariantMCP            AiExposureInfoVariant = "MCP"
	AiExposureInfoVariantTELECONTEXTMCP AiExposureInfoVariant = "TELECONTEXTMCP"
)

// Valid indicates whether the value is a known member of the AiExposureInfoVariant enum.
func (e AiExposureInfoVariant) Valid() bool {
	switch e {
	case AiExposureInfoVariantMCP:
		return true
	case AiExposureInfoVariantTELECONTEXTMCP:
		return true
	default:
		return false
	}
}

// Defines values for AiSubscriptionInfoType.
const (
	AiSubscriptionInfoTypeAi AiSubscriptionInfoType = "ai"
)

// Valid indicates whether the value is a known member of the AiSubscriptionInfoType enum.
func (e AiSubscriptionInfoType) Valid() bool {
	switch e {
	case AiSubscriptionInfoTypeAi:
		return true
	default:
		return false
	}
}

// Defines values for ApiExposureInfoType.
const (
	ApiExposureInfoTypeApi ApiExposureInfoType = "api"
)

// Valid indicates whether the value is a known member of the ApiExposureInfoType enum.
func (e ApiExposureInfoType) Valid() bool {
	switch e {
	case ApiExposureInfoTypeApi:
		return true
	default:
		return false
	}
}

// Defines values for ApiSubscriptionInfoType.
const (
	ApiSubscriptionInfoTypeApi ApiSubscriptionInfoType = "api"
)

// Valid indicates whether the value is a known member of the ApiSubscriptionInfoType enum.
func (e ApiSubscriptionInfoType) Valid() bool {
	switch e {
	case ApiSubscriptionInfoTypeApi:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStrategy.
const (
	AUTO     ApprovalStrategy = "AUTO"
	FOUREYES ApprovalStrategy = "FOUREYES"
	SIMPLE   ApprovalStrategy = "SIMPLE"
)

// Valid indicates whether the value is a known member of the ApprovalStrategy enum.
func (e ApprovalStrategy) Valid() bool {
	switch e {
	case AUTO:
		return true
	case FOUREYES:
		return true
	case SIMPLE:
		return true
	default:
		return false
	}
}

// Defines values for AuthenticationClientAuthMethod.
const (
	BASIC AuthenticationClientAuthMethod = "BASIC"
	NONE  AuthenticationClientAuthMethod = "NONE"
	POST  AuthenticationClientAuthMethod = "POST"
)

// Valid indicates whether the value is a known member of the AuthenticationClientAuthMethod enum.
func (e AuthenticationClientAuthMethod) Valid() bool {
	switch e {
	case BASIC:
		return true
	case NONE:
		return true
	case POST:
		return true
	default:
		return false
	}
}

// Defines values for BasicAuthType.
const (
	BasicAuthTypeBasicAuth BasicAuthType = "basicAuth"
)

// Valid indicates whether the value is a known member of the BasicAuthType enum.
func (e BasicAuthType) Valid() bool {
	switch e {
	case BasicAuthTypeBasicAuth:
		return true
	default:
		return false
	}
}

// Defines values for ClaimValueFrom.
const (
	BasePath         ClaimValueFrom = "BasePath"
	ConsumerClientId ClaimValueFrom = "ConsumerClientId"
	ProviderClientId ClaimValueFrom = "ProviderClientId"
)

// Valid indicates whether the value is a known member of the ClaimValueFrom enum.
func (e ClaimValueFrom) Valid() bool {
	switch e {
	case BasePath:
		return true
	case ConsumerClientId:
		return true
	case ProviderClientId:
		return true
	default:
		return false
	}
}

// Defines values for EventExposureInfoType.
const (
	EventExposureInfoTypeEvent EventExposureInfoType = "event"
)

// Valid indicates whether the value is a known member of the EventExposureInfoType enum.
func (e EventExposureInfoType) Valid() bool {
	switch e {
	case EventExposureInfoTypeEvent:
		return true
	default:
		return false
	}
}

// Defines values for EventSubscriptionInfoType.
const (
	EventSubscriptionInfoTypeEvent EventSubscriptionInfoType = "event"
)

// Valid indicates whether the value is a known member of the EventSubscriptionInfoType enum.
func (e EventSubscriptionInfoType) Valid() bool {
	switch e {
	case EventSubscriptionInfoTypeEvent:
		return true
	default:
		return false
	}
}

// Defines values for EventTriggerResponseFilterMode.
const (
	Exclude EventTriggerResponseFilterMode = "exclude"
	Include EventTriggerResponseFilterMode = "include"
)

// Valid indicates whether the value is a known member of the EventTriggerResponseFilterMode enum.
func (e EventTriggerResponseFilterMode) Valid() bool {
	switch e {
	case Exclude:
		return true
	case Include:
		return true
	default:
		return false
	}
}

// Defines values for GrantType.
const (
	CLIENTCREDENTIALS GrantType = "CLIENT_CREDENTIALS"
	PASSWORD          GrantType = "PASSWORD"
	REFRESHTOKEN      GrantType = "REFRESH_TOKEN"
)

// Valid indicates whether the value is a known member of the GrantType enum.
func (e GrantType) Valid() bool {
	switch e {
	case CLIENTCREDENTIALS:
		return true
	case PASSWORD:
		return true
	case REFRESHTOKEN:
		return true
	default:
		return false
	}
}

// Defines values for ListenerSubscriptionDeliveryType.
const (
	Callback        ListenerSubscriptionDeliveryType = "callback"
	ServerSentEvent ListenerSubscriptionDeliveryType = "server_sent_event"
)

// Valid indicates whether the value is a known member of the ListenerSubscriptionDeliveryType enum.
func (e ListenerSubscriptionDeliveryType) Valid() bool {
	switch e {
	case Callback:
		return true
	case ServerSentEvent:
		return true
	default:
		return false
	}
}

// Defines values for Oauth2TokenRequest.
const (
	Body   Oauth2TokenRequest = "body"
	Header Oauth2TokenRequest = "header"
)

// Valid indicates whether the value is a known member of the Oauth2TokenRequest enum.
func (e Oauth2TokenRequest) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	default:
		return false
	}
}

// Defines values for Oauth2Type.
const (
	Oauth2TypeOauth2 Oauth2Type = "oauth2"
)

// Valid indicates whether the value is a known member of the Oauth2Type enum.
func (e Oauth2Type) Valid() bool {
	switch e {
	case Oauth2TypeOauth2:
		return true
	default:
		return false
	}
}

// Defines values for OverallStatus.
const (
	OverallStatusBlocked    OverallStatus = "blocked"
	OverallStatusComplete   OverallStatus = "complete"
	OverallStatusDone       OverallStatus = "done"
	OverallStatusFailed     OverallStatus = "failed"
	OverallStatusInvalid    OverallStatus = "invalid"
	OverallStatusNone       OverallStatus = "none"
	OverallStatusPending    OverallStatus = "pending"
	OverallStatusProcessing OverallStatus = "processing"
)

// Valid indicates whether the value is a known member of the OverallStatus enum.
func (e OverallStatus) Valid() bool {
	switch e {
	case OverallStatusBlocked:
		return true
	case OverallStatusComplete:
		return true
	case OverallStatusDone:
		return true
	case OverallStatusFailed:
		return true
	case OverallStatusInvalid:
		return true
	case OverallStatusNone:
		return true
	case OverallStatusPending:
		return true
	case OverallStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for ProcessingState.
const (
	ProcessingStateDone       ProcessingState = "done"
	ProcessingStateFailed     ProcessingState = "failed"
	ProcessingStateNone       ProcessingState = "none"
	ProcessingStatePending    ProcessingState = "pending"
	ProcessingStateProcessing ProcessingState = "processing"
)

// Valid indicates whether the value is a known member of the ProcessingState enum.
func (e ProcessingState) Valid() bool {
	switch e {
	case ProcessingStateDone:
		return true
	case ProcessingStateFailed:
		return true
	case ProcessingStateNone:
		return true
	case ProcessingStatePending:
		return true
	case ProcessingStateProcessing:
		return true
	default:
		return false
	}
}

// Defines values for State.
const (
	Blocked  State = "blocked"
	Complete State = "complete"
	Invalid  State = "invalid"
	None     State = "none"
)

// Valid indicates whether the value is a known member of the State enum.
func (e State) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Complete:
		return true
	case Invalid:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for Visibility.
const (
	ENTERPRISE Visibility = "ENTERPRISE"
	WORLD      Visibility = "WORLD"
	ZONE       Visibility = "ZONE"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case ENTERPRISE:
		return true
	case WORLD:
		return true
	case ZONE:
		return true
	default:
		return false
	}
}

// Defines values for Sort.
const (
	SortName Sort = "name"
)

// Valid indicates whether the value is a known member of the Sort enum.
func (e Sort) Valid() bool {
	switch e {
	case SortName:
		return true
	default:
		return false
	}
}

// Defines values for GetAllApiSpecificationsParamsSort.
const (
	GetAllApiSpecificationsParamsSortName GetAllApiSpecificationsParamsSort = "name"
)

// Valid indicates whether the value is a known member of the GetAllApiSpecificationsParamsSort enum.
func (e GetAllApiSpecificationsParamsSort) Valid() bool {
	switch e {
	case GetAllApiSpecificationsParamsSortName:
		return true
	default:
		return false
	}
}

// Defines values for GetAllEventSpecificationsParamsSort.
const (
	GetAllEventSpecificationsParamsSortName GetAllEventSpecificationsParamsSort = "name"
)

// Valid indicates whether the value is a known member of the GetAllEventSpecificationsParamsSort enum.
func (e GetAllEventSpecificationsParamsSort) Valid() bool {
	switch e {
	case GetAllEventSpecificationsParamsSortName:
		return true
	default:
		return false
	}
}

// Defines values for GetAllRoversParamsSort.
const (
	GetAllRoversParamsSortName GetAllRoversParamsSort = "name"
)

// Valid indicates whether the value is a known member of the GetAllRoversParamsSort enum.
func (e GetAllRoversParamsSort) Valid() bool {
	switch e {
	case GetAllRoversParamsSortName:
		return true
	default:
		return false
	}
}

// Defines values for GetApplicationsInfoParamsSort.
const (
	Name GetApplicationsInfoParamsSort = "name"
)

// Valid indicates whether the value is a known member of the GetApplicationsInfoParamsSort enum.
func (e GetApplicationsInfoParamsSort) Valid() bool {
	switch e {
	case Name:
		return true
	default:
		return false
	}
}

// AiExposure defines model for AiExposure.
type AiExposure struct {
	Approval       ApprovalStrategy   `json:"approval"`
	BasePath       string             `json:"basePath"`
	CircuitBreaker CircuitBreaker     `json:"circuitBreaker,omitempty,omitzero"`
	Failover       Failover           `json:"failover,omitempty,omitzero"`
	LoadBalancing  LoadBalancing      `json:"loadBalancing,omitempty,omitzero"`
	RateLimit      RateLimitContainer `json:"rateLimit,omitempty,omitzero"`

	// RemoveHeaders Allows you to specify a list of header names that will be removed before forwarding the request to the MCP server
	RemoveHeaders []string      `json:"removeHeaders,omitempty,omitzero"`
	Security      Security      `json:"security,omitempty,omitzero"`
	TrustedTeams  []TrustedTeam `json:"trustedTeams,omitempty,omitzero"`
	Type          string        `json:"type"`
	Upstream      string        `json:"upstream,omitempty,omitzero"`

	// Variant The MCP exposure variant
	Variant    AiExposureVariant `json:"variant"`
	Visibility Visibility        `json:"visibility"`
}

// AiExposureVariant The MCP exposure variant
type AiExposureVariant string

// AiExposureInfo defines model for AiExposureInfo.
type AiExposureInfo struct {
	Approval       ApprovalStrategy   `json:"approval"`
	BasePath       string             `json:"basePath"`
	CircuitBreaker CircuitBreaker     `json:"circuitBreaker,omitempty,omitzero"`
	Failover       Failover           `json:"failover,omitempty,omitzero"`
	LoadBalancing  LoadBalancing      `json:"loadBalancing,omitempty,omitzero"`
	RateLimit      RateLimitContainer `json:"rateLimit,omitempty,omitzero"`

	// RemoveHeaders Allows you to specify a list of header names that will be removed before forwarding the request to the MCP server
	RemoveHeaders []string           `json:"removeHeaders,omitempty,omitzero"`
	Security      Security           `json:"security,omitempty,omitzero"`
	TrustedTeams  []TrustedTeam      `json:"trustedTeams,omitempty,omitzero"`
	Type          AiExposureInfoType `json:"type"`
	Upstream      string             `json:"upstream,omitempty,omitzero"`

	// Variant The MCP exposure variant
	Variant    AiExposureInfoVariant `json:"variant"`
	Visibility Visibility            `json:"visibility"`
}

// AiExposureInfoType defines model for AiExposureInfo.Type.
type AiExposureInfoType string

// AiExposureInfoVariant The MCP exposure variant
type AiExposureInfoVariant string

// AiSubscription defines model for AiSubscription.
type AiSubscription struct {
	BasePath string   `json:"basePath"`
	Failover Failover `json:"failover,omitempty,omitzero"`
	Security Security `json:"security,omitempty,omitzero"`
	Type     string   `json:"type"`
}

// AiSubscriptionInfo defines model for AiSubscriptionInfo.
type AiSubscriptionInfo struct {
	BasePath string                 `json:"basePath"`
	Failover Failover               `json:"failover,omitempty,omitzero"`
	Security Security               `json:"security,omitempty,omitzero"`
	Type     AiSubscriptionInfoType `json:"type"`
}

// AiSubscriptionInfoType defines model for AiSubscriptionInfo.Type.
type AiSubscriptionInfoType string

// ApiChangelog defines model for ApiChangelog.
type ApiChangelog struct {
	// BasePath The API basePath
	BasePath string `json:"basePath"`

	// Items List of changelog version entries
	Items []ApiChangelogItem `json:"items"`
}

// ApiChangelogCreateRequest defines model for ApiChangelogCreateRequest.
type ApiChangelogCreateRequest struct {
	// BasePath The API basePath
	BasePath string `json:"basePath"`

	// Items List of changelog version entries
	Items []ApiChangelogItem `json:"items"`

	// Team This field is only used for hub-scoped access to control the target team of the resource. For everything else, it can be ignored
	Team string `json:"team,omitempty,omitzero"`
}

// ApiChangelogItem defines model for ApiChangelogItem.
type ApiChangelogItem struct {
	// Date Release date or period
	Date string `json:"date"`

	// Description Description of changes in this version
	Description string `json:"description"`

	// Version Semantic version number
	Version string `json:"version"`

	// VersionUrl Optional URL to release notes
	VersionUrl string `json:"versionUrl,omitempty,omitzero"`
}

// ApiChangelogListResponse defines model for ApiChangelogListResponse.
type ApiChangelogListResponse struct {
	// UnderscoreLinks HATEOAS links for pagination
	UnderscoreLinks Links                  `json:"_links,omitempty,omitzero"`
	Items           []ApiChangelogResponse `json:"items,omitempty,omitzero"`
}

// ApiChangelogResponse defines model for ApiChangelogResponse.
type ApiChangelogResponse struct {
	// BasePath The API basePath
	BasePath string `json:"basePath"`

	// Id Unique id of this resource
	Id string `json:"id,omitempty,omitzero"`

	// Items List of changelog version entries
	Items []ApiChangelogItem `json:"items"`

	// Name Name of the changelog
	Name   string `json:"name,omitempty,omitzero"`
	Status Status `json:"status,omitempty,omitzero"`
}

// ApiChangelogUpdateRequest defines model for ApiChangelogUpdateRequest.
type ApiChangelogUpdateRequest = ApiChangelog

// ApiExposure defines model for ApiExposure.
type ApiExposure struct {
	Approval       ApprovalStrategy   `json:"approval"`
	BasePath       string             `json:"basePath"`
	CircuitBreaker CircuitBreaker     `json:"circuitBreaker,omitempty,omitzero"`
	Failover       Failover           `json:"failover,omitempty,omitzero"`
	LoadBalancing  LoadBalancing      `json:"loadBalancing,omitempty,omitzero"`
	RateLimit      RateLimitContainer `json:"rateLimit,omitempty,omitzero"`

	// RemoveHeaders Allows you to specify a list of header names that will be removed before forwarding the request to the provider
	RemoveHeaders []string      `json:"removeHeaders,omitempty,omitzero"`
	Security      Security      `json:"security,omitempty,omitzero"`
	TrustedTeams  []TrustedTeam `json:"trustedTeams,omitempty,omitzero"`
	Type          string        `json:"type"`
	Upstream      string        `json:"upstream,omitempty,omitzero"`
	Visibility    Visibility    `json:"visibility"`
}

// ApiExposureInfo defines model for ApiExposureInfo.
type ApiExposureInfo struct {
	Approval       ApprovalStrategy   `json:"approval"`
	BasePath       string             `json:"basePath"`
	CircuitBreaker CircuitBreaker     `json:"circuitBreaker,omitempty,omitzero"`
	Failover       Failover           `json:"failover,omitempty,omitzero"`
	LoadBalancing  LoadBalancing      `json:"loadBalancing,omitempty,omitzero"`
	RateLimit      RateLimitContainer `json:"rateLimit,omitempty,omitzero"`

	// RemoveHeaders Allows you to specify a list of header names that will be removed before forwarding the request to the provider
	RemoveHeaders []string            `json:"removeHeaders,omitempty,omitzero"`
	Security      Security            `json:"security,omitempty,omitzero"`
	TrustedTeams  []TrustedTeam       `json:"trustedTeams,omitempty,omitzero"`
	Type          ApiExposureInfoType `json:"type"`
	Upstream      string              `json:"upstream,omitempty,omitzero"`
	Visibility    Visibility          `json:"visibility"`
}

// ApiExposureInfoType defines model for ApiExposureInfo.Type.
type ApiExposureInfoType string

// ApiRoadmap defines model for ApiRoadmap.
type ApiRoadmap struct {
	// BasePath The API basePath
	BasePath string `json:"basePath"`

	// Items List of roadmap timeline entries
	Items []ApiRoadmapItem `json:"items"`
}

// ApiRoadmapCreateRequest defines model for ApiRoadmapCreateRequest.
type ApiRoadmapCreateRequest struct {
	// BasePath The API basePath
	BasePath string `json:"basePath"`

	// Items List of roadmap timeline entries
	Items []ApiRoadmapItem `json:"items"`

	// Team This field is only used for hub-scoped access to control the target team of the resource. For everything else, it can be ignored
	Team string `json:"team,omitempty,omitzero"`
}

// ApiRoadmapItem defines model for ApiRoadmapItem.
type ApiRoadmapItem struct {
	// Date Timeline date or period
	Date string `json:"date"`

	// Description Detailed description of the milestone
	Description string `json:"description"`

	// Title Milestone title
	Title string `json:"title"`

	// TitleUrl Optional URL for more information
	TitleUrl string `json:"titleUrl,omitempty,omitzero"`
}

// ApiRoadmapListResponse defines model for ApiRoadmapListResponse.
type ApiRoadmapListResponse struct {
	// UnderscoreLinks HATEOAS links for pagination
	UnderscoreLinks Links                `json:"_links,omitempty,omitzero"`
	Items           []ApiRoadmapResponse `json:"items"`
}

// ApiRoadmapResponse defines model for ApiRoadmapResponse.
type ApiRoadmapResponse struct {
	// BasePath The API basePath
	BasePath string `json:"basePath"`

	// Id Unique id of this resource
	Id string `json:"id,omitempty,omitzero"`

	// Items List of roadmap timeline entries
	Items []ApiRoadmapItem `json:"items"`

	// Name Name of the roadmap
	Name   string `json:"name,omitempty,omitzero"`
	Status Status `json:"status,omitempty,omitzero"`
}

// ApiRoadmapUpdateRequest defines model for ApiRoadmapUpdateRequest.
type ApiRoadmapUpdateRequest = ApiRoadmap

// ApiSpecification defines model for ApiSpecification.
type ApiSpecification struct {
	// Specification A valid API-specification according to the guidelines in openapi or swagger (deprecated) format
	Specification map[string]interface{} `json:"specification"`
}

// ApiSpecificationCreateRequest defines model for ApiSpecificationCreateRequest.
type ApiSpecificationCreateRequest struct {
	// Specification A valid API-specification according to the guidelines in openapi or swagger (deprecated) format
	Specification map[string]interface{} `json:"specification"`

	// Team This field is only used for hub-scoped access to control the target team of the resource. For everything else, it can be ignored
	Team string `json:"team,omitempty,omitzero"`
}

// ApiSpecificationListResponse defines model for ApiSpecificationListResponse.
type ApiSpecificationListResponse struct {
	// UnderscoreLinks HATEOAS links for pagination
	UnderscoreLinks Links                      `json:"_links,omitempty,omitzero"`
	Items           []ApiSpecificationResponse `json:"items"`
}

// ApiSpecificationResponse defines model for ApiSpecificationResponse.
type ApiSpecificationResponse struct {
	// Category Category of this api
	Category string `json:"category"`

	// Id Unique id of this resource. Can be used to directly address this specific resource
	Id string `json:"id"`

	// Name Name of the created api (subset of id)
	Name string `json:"name"`

	// Specification A valid API-specification according to the guidelines in openapi or swagger (deprecated) format
	Specification map[string]interface{} `json:"specification"`
	Status        Status                 `json:"status,omitempty,omitzero"`

	// VendorApi Whether this api is an vendor api
	VendorApi bool `json:"vendorApi"`
}

// ApiSpecificationUpdateRequest defines model for ApiSpecificationUpdateRequest.
type ApiSpecificationUpdateRequest = ApiSpecification

// ApiSubscription defines model for ApiSubscription.
type ApiSubscription struct {
	BasePath string   `json:"basePath"`
	Failover Failover `json:"failover,omitempty,omitzero"`
	Security Security `json:"security,omitempty,omitzero"`
	Type     string   `json:"type"`
}

// ApiSubscriptionInfo defines model for ApiSubscriptionInfo.
type ApiSubscriptionInfo struct {
	BasePath      string                  `json:"basePath"`
	Failover      Failover                `json:"failover,omitempty,omitzero"`
	FailoverInfos []FailoverInfo          `json:"failoverInfos,omitempty,omitzero"`
	Security      Security                `json:"security,omitempty,omitzero"`
	Type          ApiSubscriptionInfoType `json:"type"`
}

// ApiSubscriptionInfoType defines model for ApiSubscriptionInfo.Type.
type ApiSubscriptionInfoType string

// ApplicationInfo defines model for ApplicationInfo.
type ApplicationInfo struct {
	// Authorization Permission rules configured for this application
	Authorization []AuthorizationInfo `json:"authorization,omitempty,omitzero"`

	// ChevronApplication Application identifier for permission queries (equals irisClientId)
	ChevronApplication string `json:"chevronApplication,omitempty,omitzero"`

	// ChevronUrl URL to query permissions for this application
	ChevronUrl string         `json:"chevronUrl,omitempty,omitzero"`
	Errors     []Problem      `json:"errors"`
	Exposures  []ExposureInfo `json:"exposures"`

	// FailoverEnabled Indicates if failover is enabled for this application
	FailoverEnabled bool      `json:"failoverEnabled,omitempty,omitzero"`
	Infos           []Problem `json:"infos"`
	IrisClientId    string    `json:"irisClientId"`

	// IrisClientSecret Deprecated: Use secretInfo.clientSecret instead. This field will be removed in a future version.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	IrisClientSecret     string `json:"irisClientSecret"`
	IrisIssuerUrl        string `json:"irisIssuerUrl"`
	IrisTokenEndpointUrl string `json:"irisTokenEndpointUrl"`
	Name                 string `json:"name"`
	ObserverUrl          string `json:"observerUrl,omitempty,omitzero"`

	// Psiid PSI system number identifier attached to this application
	Psiid                   string     `json:"psiid,omitempty,omitzero"`
	SecretInfo              SecretInfo `json:"secretInfo,omitempty,omitzero"`
	StargateIssuerUrl       string     `json:"stargateIssuerUrl,omitempty,omitzero"`
	StargatePublishEventUrl string     `json:"stargatePublishEventUrl,omitempty,omitzero"`
	StargateUrl             string     `json:"stargateUrl,omitempty,omitzero"`

	// Status Status of this resource and all its relevant sub-resources
	Status        OverallStatus      `json:"status"`
	Subscriptions []SubscriptionInfo `json:"subscriptions"`
	Variables     []Data             `json:"variables"`
	Warnings      []Problem          `json:"warnings"`
	Zone          string             `json:"zone"`
}

// ApprovalStrategy defines model for ApprovalStrategy.
type ApprovalStrategy string

// Authentication defines model for Authentication.
type Authentication struct {
	ApplicationScope string `json:"applicationScope,omitempty,omitzero"`

	// ClientAuthMethod Configures client authentication method, according to RFC 6749.
	ClientAuthMethod       AuthenticationClientAuthMethod `json:"clientAuthMethod,omitempty,omitzero"`
	PostLogoutRedirectUrls []string                       `json:"postLogoutRedirectUrls,omitempty,omitzero"`
	PublicClient           bool                           `json:"publicClient,omitempty,omitzero"`
	RedirectUrls           []string                       `json:"redirectUrls,omitempty,omitzero"`
}

// AuthenticationClientAuthMethod Configures client authentication method, according to RFC 6749.
type AuthenticationClientAuthMethod string

// AuthorizationInfo defines model for AuthorizationInfo.
type AuthorizationInfo struct {
	Actions     []string                      `json:"actions,omitempty,omitzero"`
	Permissions []AuthorizationPermissionInfo `json:"permissions,omitempty,omitzero"`
	Resource    string                        `json:"resource,omitempty,omitzero"`
	Role        string                        `json:"role,omitempty,omitzero"`
}

// AuthorizationPermissionInfo defines model for AuthorizationPermissionInfo.
type AuthorizationPermissionInfo struct {
	Actions  []string `json:"actions,omitempty,omitzero"`
	Resource string   `json:"resource,omitempty,omitzero"`
	Role     string   `json:"role,omitempty,omitzero"`
}

// BasicAuth defines model for BasicAuth.
type BasicAuth struct {
	Password string        `json:"password"`
	Type     BasicAuthType `json:"type"`
	Username string        `json:"username"`
}

// BasicAuthType defines model for BasicAuth.Type.
type BasicAuthType string

// Category defines model for Category.
type Category = string

// CircuitBreaker defines model for CircuitBreaker.
type CircuitBreaker struct {
	// Enabled Flags if the Kong circuit breaker feature should be used
	Enabled bool `json:"enabled,omitempty,omitzero"`
}

// Claim A single claim value. Exactly one of value or valueFrom must be set.
type Claim struct {
	// Value A literal claim value.
	Value string `json:"value,omitempty,omitzero"`

	// ValueFrom A predefined source resolved into the claim value.
	ValueFrom ClaimValueFrom `json:"valueFrom,omitempty,omitzero"`
}

// ClaimValueFrom A predefined source resolved into the claim value.
type ClaimValueFrom string

// Claims Token claims written into the platform-managed LMS token. Provider-side only: honored on an API exposure's security and ignored on a subscription's security. Only valid on the LMS token (not with an external IDP tokenEndpoint or basic auth).
type Claims struct {
	// Aud A single claim value. Exactly one of value or valueFrom must be set.
	Aud Claim `json:"aud,omitempty,omitzero"`
}

// ConsumerRateLimit defines model for ConsumerRateLimit.
type ConsumerRateLimit struct {
	FaultTolerant     bool  `json:"faultTolerant,omitempty,omitzero"`
	HideClientHeaders bool  `json:"hideClientHeaders,omitempty,omitzero"`
	Hour              int32 `json:"hour,omitempty,omitzero"`

	// Id The unique ID of this consumer (their clientId)
	Id     string `json:"id,omitempty,omitzero"`
	Minute int32  `json:"minute,omitempty,omitzero"`
	Second int32  `json:"second,omitempty,omitzero"`
}

// ConsumerRateLimitContainer defines model for ConsumerRateLimitContainer.
type ConsumerRateLimitContainer struct {
	ConsumerDefault RateLimit `json:"consumerDefault,omitempty,omitzero"`

	// Consumers Rate limits for specific consumers. This will be merged with the default rate limit. This will take precedence over the default rate limit.
	Consumers []ConsumerRateLimit `json:"consumers,omitempty,omitzero"`
}

// Data defines model for Data.
type Data struct {
	Name  string `json:"name,omitempty,omitzero"`
	Value string `json:"value,omitempty,omitzero"`
}

// Error RFC-7807 conform object sent on any error
type Error struct {
	Detail    string         `json:"detail,omitempty,omitzero"`
	ErrorCode string         `json:"errorCode,omitempty,omitzero"`
	Fields    []FieldProblem `json:"fields,omitempty,omitzero"`
	Instance  string         `json:"instance,omitempty,omitzero"`
	Status    float32        `json:"status,omitempty,omitzero"`
	Title     string         `json:"title"`
	Type      string         `json:"type"`
}

// EventExposure defines model for EventExposure.
type EventExposure struct {
	AdditionalPublisherIds []string         `json:"additionalPublisherIds,omitempty,omitzero"`
	Approval               ApprovalStrategy `json:"approval"`
	EventCategory          Category         `json:"eventCategory,omitempty,omitzero"`
	EventType              string           `json:"eventType"`
	Scopes                 []EventScope     `json:"scopes,omitempty,omitzero"`
	TrustedTeams           []TrustedTeam    `json:"trustedTeams,omitempty,omitzero"`
	Type                   string           `json:"type"`
	Visibility             Visibility       `json:"visibility"`
}

// EventExposureInfo defines model for EventExposureInfo.
type EventExposureInfo struct {
	AdditionalPublisherIds []string              `json:"additionalPublisherIds,omitempty,omitzero"`
	Approval               ApprovalStrategy      `json:"approval"`
	EventCategory          Category              `json:"eventCategory,omitempty,omitzero"`
	EventType              string                `json:"eventType"`
	Scopes                 []EventScope          `json:"scopes,omitempty,omitzero"`
	TrustedTeams           []TrustedTeam         `json:"trustedTeams,omitempty,omitzero"`
	Type                   EventExposureInfoType `json:"type"`
	Visibility             Visibility            `json:"visibility"`
}

// EventExposureInfoType defines model for EventExposureInfo.Type.
type EventExposureInfoType string

// EventScope defines model for EventScope.
type EventScope struct {
	Name    string       `json:"name,omitempty,omitzero"`
	Trigger EventTrigger `json:"trigger,omitempty,omitzero"`
}

// EventSpecification defines model for EventSpecification.
type EventSpecification struct {
	Category string `json:"category,omitempty,omitzero"`

	// Description A short description for your events
	Description string `json:"description"`

	// Specification Optional JSON scheme
	Specification map[string]interface{} `json:"specification,omitempty,omitzero"`

	// Type Your event type (separated with dots)
	Type    string `json:"type"`
	Version string `json:"version"`
}

// EventSpecificationCreateRequest defines model for EventSpecificationCreateRequest.
type EventSpecificationCreateRequest struct {
	Category string `json:"category,omitempty,omitzero"`

	// Description A short description for your events
	Description string `json:"description"`

	// Specification Optional JSON scheme
	Specification map[string]interface{} `json:"specification,omitempty,omitzero"`

	// Team This field is only used for hub-scoped access to control the target team of the resource. For everything else, it can be ignored
	Team string `json:"team,omitempty,omitzero"`

	// Type Your event type (separated with dots)
	Type    string `json:"type"`
	Version string `json:"version"`
}

// EventSpecificationListResponse defines model for EventSpecificationListResponse.
type EventSpecificationListResponse struct {
	// UnderscoreLinks HATEOAS links for pagination
	UnderscoreLinks Links                        `json:"_links,omitempty,omitzero"`
	Items           []EventSpecificationResponse `json:"items,omitempty,omitzero"`
}

// EventSpecificationResponse defines model for EventSpecificationResponse.
type EventSpecificationResponse struct {
	Category string `json:"category,omitempty,omitzero"`

	// Description A short description for your events
	Description string `json:"description"`

	// Id Your event type name (separated with dashes)
	Id string `json:"id,omitempty,omitzero"`

	// Specification Optional JSON scheme
	Specification map[string]interface{} `json:"specification,omitempty,omitzero"`
	Status        Status                 `json:"status,omitempty,omitzero"`

	// Type Your event type (separated with dots)
	Type    string `json:"type"`
	Version string `json:"version"`
}

// EventSpecificationUpdateRequest defines model for EventSpecificationUpdateRequest.
type EventSpecificationUpdateRequest = EventSpecification

// EventSubscription defines model for EventSubscription.
type EventSubscription struct {
	Callback string `json:"callback,omitempty,omitzero"`

	// CircuitBreakerOptOut If your application does not need the circuit breaking feature of Horizon, you can opt out of it by setting this to true.
	CircuitBreakerOptOut bool   `json:"circuitBreakerOptOut,omitempty,omitzero"`
	DeliveryType         string `json:"deliveryType"`

	// EnforceGetHttpRequestMethodForHealthCheck If true, the health check will be performed with a GET request instead of a HEAD request
	EnforceGetHttpRequestMethodForHealthCheck bool `json:"enforceGetHttpRequestMethodForHealthCheck,omitempty,omitzero"`

	// EventRetentionTime It is possible to lower the default retention time of 7 days. See [docs](https://developer.telekom.de/docs/src/tardis_customer_handbook/horizon/feature-overview/Custom_Retention_Time/)
	EventRetentionTime string `json:"eventRetentionTime,omitempty,omitzero"`

	// EventType Unique identifier of the event type
	EventType   string `json:"eventType"`
	PayloadType string `json:"payloadType"`

	// RedeliveriesPerSecond The maximum possible number of redeliveries per second
	RedeliveriesPerSecond int `json:"redeliveriesPerSecond,omitempty,omitzero"`

	// RetryableStatusCodes List of HTTP status codes that are considered retryable.
	RetryableStatusCodes []int        `json:"retryableStatusCodes,omitempty,omitzero"`
	Scopes               []string     `json:"scopes,omitempty,omitzero"`
	Trigger              EventTrigger `json:"trigger,omitempty,omitzero"`
	Type                 string       `json:"type"`
}

// EventSubscriptionInfo defines model for EventSubscriptionInfo.
type EventSubscriptionInfo struct {
	Callback string `json:"callback,omitempty,omitzero"`

	// CircuitBreakerOptOut If your application does not need the circuit breaking feature of Horizon, you can opt out of it by setting this to true.
	CircuitBreakerOptOut bool   `json:"circuitBreakerOptOut,omitempty,omitzero"`
	DeliveryType         string `json:"deliveryType"`

	// EnforceGetHttpRequestMethodForHealthCheck If true, the health check will be performed with a GET request instead of a HEAD request
	EnforceGetHttpRequestMethodForHealthCheck bool `json:"enforceGetHttpRequestMethodForHealthCheck,omitempty,omitzero"`

	// EventRetentionTime It is possible to lower the default retention time of 7 days. See [docs](https://developer.telekom.de/docs/src/tardis_customer_handbook/horizon/feature-overview/Custom_Retention_Time/)
	EventRetentionTime string `json:"eventRetentionTime,omitempty,omitzero"`

	// EventType Unique identifier of the event type
	EventType              string `json:"eventType"`
	HorizonSubscriptionId  string `json:"horizonSubscriptionId,omitempty,omitzero"`
	HorizonSubscriptionUrl string `json:"horizonSubscriptionUrl,omitempty,omitzero"`
	PayloadType            string `json:"payloadType"`

	// RedeliveriesPerSecond The maximum possible number of redeliveries per second
	RedeliveriesPerSecond int `json:"redeliveriesPerSecond,omitempty,omitzero"`

	// RetryableStatusCodes List of HTTP status codes that are considered retryable.
	RetryableStatusCodes []int                     `json:"retryableStatusCodes,omitempty,omitzero"`
	Scopes               []string                  `json:"scopes,omitempty,omitzero"`
	Trigger              EventTrigger              `json:"trigger,omitempty,omitzero"`
	Type                 EventSubscriptionInfoType `json:"type"`
}

// EventSubscriptionInfoType defines model for EventSubscriptionInfo.Type.
type EventSubscriptionInfoType string

// EventTrigger defines model for EventTrigger.
type EventTrigger struct {
	AdvancedSelectionFilter map[string]interface{}         `json:"advancedSelectionFilter,omitempty,omitzero"`
	ResponseFilter          []string                       `json:"responseFilter,omitempty,omitzero"`
	ResponseFilterMode      EventTriggerResponseFilterMode `json:"responseFilterMode,omitempty,omitzero"`
	SelectionFilter         map[string]string              `json:"selectionFilter,omitempty,omitzero"`
}

// EventTriggerResponseFilterMode defines model for EventTrigger.ResponseFilterMode.
type EventTriggerResponseFilterMode string

// Exposure defines model for Exposure.
type Exposure struct {
	union json.RawMessage
}

// ExposureInfo defines model for ExposureInfo.
type ExposureInfo struct {
	union json.RawMessage
}

// Failover defines model for Failover.
type Failover struct {
	// Zones Provide a list of zones which you are able to use for failover
	Zones []string `json:"zones"`
}

// FailoverInfo defines model for FailoverInfo.
type FailoverInfo struct {
	IrisTokenEndpointUrl   string `json:"irisTokenEndpointUrl,omitempty,omitzero"`
	StargateApiEndpointUrl string `json:"stargateApiEndpointUrl,omitempty,omitzero"`
	Zone                   string `json:"zone,omitempty,omitzero"`
}

// FieldProblem defines model for FieldProblem.
type FieldProblem struct {
	Detail string `json:"detail,omitempty,omitzero"`
	Path   string `json:"path,omitempty,omitzero"`
	Title  string `json:"title"`
}

// GrantType defines model for GrantType.
type GrantType string

// Health defines model for Health.
type Health struct {
	HttpPath string `json:"httpPath,omitempty,omitzero"`
}

// IpRestrictions defines model for IpRestrictions.
type IpRestrictions struct {
	Allow []string `json:"allow,omitempty,omitzero"`
}

// Links HATEOAS links for pagination
type Links struct {
	// Next the URI for the next page for requested pagination, based on the requested limit value
	Next string `json:"next"`

	// Self the URI for the current page for requested pagination
	Self string `json:"self"`
}

// ListenerFilter defines model for ListenerFilter.
type ListenerFilter struct {
	// Payload Fields to include in the listener output
	Payload []string `json:"payload,omitempty,omitzero"`

	// Trigger Key-value conditions that must match for the filter to activate
	Trigger map[string]string `json:"trigger,omitempty,omitzero"`
}

// ListenerSubscription defines model for ListenerSubscription.
type ListenerSubscription struct {
	// Callback URL where listener events are delivered when deliveryType is "callback"
	Callback string `json:"callback,omitempty,omitzero"`

	// DeliveryType Delivery mechanism for listener events
	DeliveryType ListenerSubscriptionDeliveryType `json:"deliveryType,omitempty,omitzero"`
}

// ListenerSubscriptionDeliveryType Delivery mechanism for listener events
type ListenerSubscriptionDeliveryType string

// LoadBalancing defines model for LoadBalancing.
type LoadBalancing struct {
	Health Health `json:"health,omitempty,omitzero"`

	// Servers Provide a list of servers to use for loadBalancing
	Servers []Server `json:"servers"`
}

// McpSpecification defines model for McpSpecification.
type McpSpecification struct {
	Specification map[string]interface{} `json:"specification"`
}

// McpSpecificationCreateRequest defines model for McpSpecificationCreateRequest.
type McpSpecificationCreateRequest = McpSpecification

// McpSpecificationListResponse defines model for McpSpecificationListResponse.
type McpSpecificationListResponse struct {
	// UnderscoreLinks HATEOAS links for pagination
	UnderscoreLinks Links                      `json:"_links"`
	Items           []McpSpecificationResponse `json:"items"`
}

// McpSpecificationResponse defines model for McpSpecificationResponse.
type McpSpecificationResponse struct {
	Category      string                 `json:"category,omitempty,omitzero"`
	Id            string                 `json:"id"`
	Name          string                 `json:"name"`
	Specification map[string]interface{} `json:"specification"`

	// Status Response resource which contains information about the status of the resource and all its relevant sub-resources
	Status ResourceStatusResponse `json:"status"`
}

// McpSpecificationUpdateRequest defines model for McpSpecificationUpdateRequest.
type McpSpecificationUpdateRequest = McpSpecification

// Oauth2 defines model for Oauth2.
type Oauth2 struct {
	// Claims Token claims written into the platform-managed LMS token. Provider-side only: honored on an API exposure's security and ignored on a subscription's security. Only valid on the LMS token (not with an external IDP tokenEndpoint or basic auth).
	Claims        Claims    `json:"claims,omitempty,omitzero"`
	ClientId      string    `json:"clientId,omitempty,omitzero"`
	ClientKey     string    `json:"clientKey,omitempty,omitzero"`
	ClientSecret  string    `json:"clientSecret,omitempty,omitzero"`
	GrantType     GrantType `json:"grantType,omitempty,omitzero"`
	Password      string    `json:"password,omitempty,omitzero"`
	RefreshToken  string    `json:"refreshToken,omitempty,omitzero"`
	Scopes        []string  `json:"scopes,omitempty,omitzero"`
	TokenEndpoint string    `json:"tokenEndpoint,omitempty,omitzero"`

	// TokenRequest Specifies if the authentication data should be sent to the external IDP via headers or in the body of the request
	TokenRequest Oauth2TokenRequest `json:"tokenRequest,omitempty,omitzero"`
	Type         Oauth2Type         `json:"type"`
	Username     string             `json:"username,omitempty,omitzero"`
}

// Oauth2TokenRequest Specifies if the authentication data should be sent to the external IDP via headers or in the body of the request
type Oauth2TokenRequest string

// Oauth2Type defines model for Oauth2.Type.
type Oauth2Type string

// OverallStatus Status of this resource and all its relevant sub-resources
type OverallStatus string

// Problem defines model for Problem.
type Problem struct {
	Cause    string      `json:"cause"`
	Context  string      `json:"context,omitempty,omitzero"`
	Details  string      `json:"details,omitempty,omitzero"`
	Message  string      `json:"message"`
	Resource ResourceRef `json:"resource,omitempty,omitzero"`
}

// ProcessingState defines model for ProcessingState.
type ProcessingState string

// RateLimit defines model for RateLimit.
type RateLimit struct {
	FaultTolerant     bool  `json:"faultTolerant,omitempty,omitzero"`
	HideClientHeaders bool  `json:"hideClientHeaders,omitempty,omitzero"`
	Hour              int32 `json:"hour,omitempty,omitzero"`
	Minute            int32 `json:"minute,omitempty,omitzero"`
	Second            int32 `json:"second,omitempty,omitzero"`
}

// RateLimitContainer defines model for RateLimitContainer.
type RateLimitContainer struct {
	ConsumerDefault RateLimit `json:"consumerDefault,omitempty,omitzero"`

	// Consumers Rate limits for specific consumers. This will be merged with the default rate limit. This will take precedence over the default rate limit.
	Consumers []ConsumerRateLimit `json:"consumers,omitempty,omitzero"`
	Provider  RateLimit           `json:"provider,omitempty,omitzero"`
}

// ResourceRef defines model for ResourceRef.
type ResourceRef struct {
	ApiVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Namespace  string `json:"namespace"`
	Path       string `json:"path,omitempty,omitzero"`
}

// ResourceStatusResponse Response resource which contains information about the status of the resource and all its relevant sub-resources
type ResourceStatusResponse struct {
	// CreatedAt Time when the resource was created
	CreatedAt time.Time `json:"createdAt,omitempty,omitzero"`

	// Errors List of errors that resulted while processing this resource
	Errors []Problem `json:"errors,omitempty,omitzero"`

	// Infos List of infos that resulted while processing this resource
	Infos []Problem `json:"infos,omitempty,omitzero"`

	// OverallStatus Status of this resource and all its relevant sub-resources
	OverallStatus OverallStatus `json:"overallStatus"`

	// ProcessedAt Time when the resource was last processed
	ProcessedAt     time.Time       `json:"processedAt,omitempty,omitzero"`
	ProcessingState ProcessingState `json:"processingState"`
	State           State           `json:"state"`

	// Warnings List of warnings that resulted while processing this resource
	Warnings []Problem `json:"warnings,omitempty,omitzero"`
}

// Rover defines model for Rover.
type Rover struct {
	Authentication Authentication      `json:"authentication,omitempty,omitzero"`
	Authorization  []AuthorizationInfo `json:"authorization,omitempty,omitzero"`
	Exposures      []Exposure          `json:"exposures,omitempty,omitzero"`

	// FailoverEnabled Configures the DTC failover for consumers
	FailoverEnabled      bool                 `json:"failoverEnabled,omitempty,omitzero"`
	Icto                 string               `json:"icto,omitempty,omitzero"`
	Id                   string               `json:"id,omitempty,omitzero"`
	IpRestrictions       IpRestrictions       `json:"ipRestrictions,omitempty,omitzero"`
	ListenerSubscription ListenerSubscription `json:"listenerSubscription,omitempty,omitzero"`
	Listeners            []RoverListener      `json:"listeners,omitempty,omitzero"`

	// Psiid PSI system number identifier attached to this application
	Psiid         string         `json:"psiid,omitempty,omitzero"`
	Status        Status         `json:"status,omitempty,omitzero"`
	Subscriptions []Subscription `json:"subscriptions,omitempty,omitzero"`
	Zone          string         `json:"zone"`
}

// RoverCreateRequest defines model for RoverCreateRequest.
type RoverCreateRequest struct {
	Authentication Authentication      `json:"authentication,omitempty,omitzero"`
	Authorization  []AuthorizationInfo `json:"authorization,omitempty,omitzero"`
	Exposures      []Exposure          `json:"exposures,omitempty,omitzero"`

	// FailoverEnabled Configures the DTC failover for consumers
	FailoverEnabled      bool                 `json:"failoverEnabled,omitempty,omitzero"`
	Icto                 string               `json:"icto,omitempty,omitzero"`
	Id                   string               `json:"id,omitempty,omitzero"`
	IpRestrictions       IpRestrictions       `json:"ipRestrictions,omitempty,omitzero"`
	ListenerSubscription ListenerSubscription `json:"listenerSubscription,omitempty,omitzero"`
	Listeners            []RoverListener      `json:"listeners,omitempty,omitzero"`
	Name                 string               `json:"name,omitempty,omitzero"`

	// Psiid PSI system number identifier attached to this application
	Psiid         string         `json:"psiid,omitempty,omitzero"`
	Status        Status         `json:"status,omitempty,omitzero"`
	Subscriptions []Subscription `json:"subscriptions,omitempty,omitzero"`

	// Team This field is only used for hub-scoped access to control the target team of the resource. For everything else, it can be ignored
	Team string `json:"team,omitempty,omitzero"`
	Zone string `json:"zone"`
}

// RoverInfoResponse defines model for RoverInfoResponse.
type RoverInfoResponse struct {
	Applications []ApplicationInfo `json:"applications"`
	Environment  string            `json:"environment"`
	Hub          string            `json:"hub"`
	Team         string            `json:"team"`
}

// RoverListResponse defines model for RoverListResponse.
type RoverListResponse struct {
	// UnderscoreLinks HATEOAS links for pagination
	UnderscoreLinks Links           `json:"_links"`
	Items           []RoverResponse `json:"items"`
}

// RoverListener defines model for RoverListener.
type RoverListener struct {
	// ApiBasePath Base path of the API to listen on
	ApiBasePath string `json:"apiBasePath,omitempty,omitzero"`

	// Consumer ENI of the consuming application (e.g. "eni--team--app")
	Consumer    string         `json:"consumer"`
	EventFilter ListenerFilter `json:"eventFilter,omitempty,omitzero"`

	// EventType Event type to listen on (alternative to apiBasePath)
	EventType string `json:"eventType,omitempty,omitzero"`

	// Provider ENI of the providing application (e.g. "eni--other--provider")
	Provider       string         `json:"provider"`
	RequestFilter  ListenerFilter `json:"requestFilter,omitempty,omitzero"`
	ResponseFilter ListenerFilter `json:"responseFilter,omitempty,omitzero"`
}

// RoverResponse defines model for RoverResponse.
type RoverResponse struct {
	Authentication Authentication      `json:"authentication,omitempty,omitzero"`
	Authorization  []AuthorizationInfo `json:"authorization,omitempty,omitzero"`
	Exposures      []Exposure          `json:"exposures,omitempty,omitzero"`

	// FailoverEnabled Configures the DTC failover for consumers
	FailoverEnabled      bool                 `json:"failoverEnabled,omitempty,omitzero"`
	Icto                 string               `json:"icto,omitempty,omitzero"`
	Id                   string               `json:"id,omitempty,omitzero"`
	IpRestrictions       IpRestrictions       `json:"ipRestrictions,omitempty,omitzero"`
	ListenerSubscription ListenerSubscription `json:"listenerSubscription,omitempty,omitzero"`
	Listeners            []RoverListener      `json:"listeners,omitempty,omitzero"`
	Name                 string               `json:"name,omitempty,omitzero"`

	// Psiid PSI system number identifier attached to this application
	Psiid         string         `json:"psiid,omitempty,omitzero"`
	Status        Status         `json:"status,omitempty,omitzero"`
	Subscriptions []Subscription `json:"subscriptions,omitempty,omitzero"`
	Zone          string         `json:"zone"`
}

// RoverSecretRotationAcceptedResponse defines model for RoverSecretRotationAcceptedResponse.
type RoverSecretRotationAcceptedResponse struct {
	UnderscoreLinks struct {
		// Status URL to poll for the rotation status
		Status string `json:"status"`
	} `json:"_links"`

	// ClientId The clientId of the application
	ClientId string `json:"clientId"`

	// Message Human-readable message about the initiated rotation
	Message string `json:"message"`
}

// RoverSecretRotationStatusResponse defines model for RoverSecretRotationStatusResponse.
type RoverSecretRotationStatusResponse struct {
	// ClientId The clientId of the application
	ClientId string `json:"clientId"`

	// ClientSecret The current (new) client secret value
	ClientSecret string `json:"clientSecret,omitempty,omitzero"`

	// CurrentExpiresAt When the current secret will expire and should be rotated
	CurrentExpiresAt time.Time `json:"currentExpiresAt,omitempty,omitzero"`

	// OverallStatus Status of this resource and all its relevant sub-resources
	OverallStatus   OverallStatus   `json:"overallStatus"`
	ProcessingState ProcessingState `json:"processingState"`

	// RotatedClientSecret The previous (rotated) client secret value, valid until rotatedExpiresAt
	RotatedClientSecret string `json:"rotatedClientSecret,omitempty,omitzero"`

	// RotatedExpiresAt When the rotated (old) secret stops being accepted
	RotatedExpiresAt time.Time `json:"rotatedExpiresAt,omitempty,omitzero"`
}

// RoverUpdateRequest defines model for RoverUpdateRequest.
type RoverUpdateRequest struct {
	Authentication Authentication      `json:"authentication,omitempty,omitzero"`
	Authorization  []AuthorizationInfo `json:"authorization,omitempty,omitzero"`

	// ClientSecret This field is only used for migration purposes and will be ignored otherwise.
	ClientSecret string     `json:"clientSecret,omitempty,omitzero"`
	Exposures    []Exposure `json:"exposures,omitempty,omitzero"`

	// FailoverEnabled Configures the DTC failover for consumers
	FailoverEnabled      bool                 `json:"failoverEnabled,omitempty,omitzero"`
	Icto                 string               `json:"icto,omitempty,omitzero"`
	Id                   string               `json:"id,omitempty,omitzero"`
	IpRestrictions       IpRestrictions       `json:"ipRestrictions,omitempty,omitzero"`
	ListenerSubscription ListenerSubscription `json:"listenerSubscription,omitempty,omitzero"`
	Listeners            []RoverListener      `json:"listeners,omitempty,omitzero"`

	// Psiid PSI system number identifier attached to this application
	Psiid         string         `json:"psiid,omitempty,omitzero"`
	Status        Status         `json:"status,omitempty,omitzero"`
	Subscriptions []Subscription `json:"subscriptions,omitempty,omitzero"`
	Zone          string         `json:"zone"`
}

// SecretInfo defines model for SecretInfo.
type SecretInfo struct {
	// ClientSecret The current client secret value
	ClientSecret string `json:"clientSecret,omitempty,omitzero"`

	// CurrentExpiresAt When the current secret will expire and should be rotated
	CurrentExpiresAt time.Time `json:"currentExpiresAt,omitempty,omitzero"`

	// RotatedClientSecret The previous (rotated) client secret value, valid until rotatedExpiresAt
	RotatedClientSecret string `json:"rotatedClientSecret,omitempty,omitzero"`

	// RotatedExpiresAt When the rotated (old) secret stops being accepted
	RotatedExpiresAt time.Time `json:"rotatedExpiresAt,omitempty,omitzero"`
}

// Security defines model for Security.
type Security struct {
	union json.RawMessage
}

// Server defines model for Server.
type Server struct {
	Upstream string `json:"upstream"`
	Weight   int    `json:"weight,omitempty,omitzero"`
}

// State defines model for State.
type State string

// StateInfo defines model for StateInfo.
type StateInfo struct {
	Cause   string `json:"cause,omitempty,omitzero"`
	Message string `json:"message"`
}

// Status defines model for Status.
type Status struct {
	Errors          []StateInfo     `json:"errors,omitempty,omitzero"`
	Infos           []StateInfo     `json:"infos,omitempty,omitzero"`
	ProcessingState ProcessingState `json:"processingState"`
	State           State           `json:"state"`
	Warnings        []StateInfo     `json:"warnings,omitempty,omitzero"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	union json.RawMessage
}

// SubscriptionInfo defines model for SubscriptionInfo.
type SubscriptionInfo struct {
	union json.RawMessage
}

// TrustedTeam A trusted team is a team that is allowed to access the resource without explicit approval
type TrustedTeam struct {
	Team string `json:"team"`
}

// Visibility defines model for Visibility.
type Visibility string

// ApiChangelogId defines model for ApiChangelogId.
type ApiChangelogId = string

// ApiRoadmapId defines model for ApiRoadmapId.
type ApiRoadmapId = string

// ApiSpecificationId defines model for ApiSpecificationId.
type ApiSpecificationId = string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// RoverId defines model for RoverId.
type RoverId = string

// ShallowInfo defines model for ShallowInfo.
type ShallowInfo = bool

// Sort defines model for Sort.
type Sort string

// BadRequest RFC-7807 conform object sent on any error
type BadRequest = Error

// Forbidden RFC-7807 conform object sent on any error
type Forbidden = Error

// NotFound RFC-7807 conform object sent on any error
type NotFound = Error

// ServerError RFC-7807 conform object sent on any error
type ServerError = Error

// Unauthorized RFC-7807 conform object sent on any error
type Unauthorized = Error

// UnsupportedMediaType RFC-7807 conform object sent on any error
type UnsupportedMediaType = Error

// oAuth2ContextKey is the context key for OAuth2 security scheme
type oAuth2ContextKey string

// GetAllApiChangelogsParams defines parameters for GetAllApiChangelogs.
type GetAllApiChangelogsParams struct {
	// Cursor cursor for pagination
	Cursor string `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`
}

// GetAllApiRoadmapsParams defines parameters for GetAllApiRoadmaps.
type GetAllApiRoadmapsParams struct {
	// Cursor cursor for pagination
	Cursor string `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`
}

// GetAllApiSpecificationsParams defines parameters for GetAllApiSpecifications.
type GetAllApiSpecificationsParams struct {
	// Limit page size requested by the consumer; must not be larger than the maximal page size
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Cursor cursor to be used for pagination. If not provided, the first page will be returned. The cursor is a string that points to a page of data.
	Cursor Cursor `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`

	// Sort list of fields to be used for sorting. Default is name
	Sort GetAllApiSpecificationsParamsSort `form:"sort,omitempty" json:"sort,omitempty,omitzero"`
}

// GetAllApiSpecificationsParamsSort defines parameters for GetAllApiSpecifications.
type GetAllApiSpecificationsParamsSort string

// GetAllEventSpecificationsParams defines parameters for GetAllEventSpecifications.
type GetAllEventSpecificationsParams struct {
	// Limit page size requested by the consumer; must not be larger than the maximal page size
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Cursor cursor to be used for pagination. If not provided, the first page will be returned. The cursor is a string that points to a page of data.
	Cursor Cursor `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`

	// Sort list of fields to be used for sorting. Default is name
	Sort GetAllEventSpecificationsParamsSort `form:"sort,omitempty" json:"sort,omitempty,omitzero"`
}

// GetAllEventSpecificationsParamsSort defines parameters for GetAllEventSpecifications.
type GetAllEventSpecificationsParamsSort string

// GetAllMcpSpecificationsParams defines parameters for GetAllMcpSpecifications.
type GetAllMcpSpecificationsParams struct {
	// Cursor cursor to be used for pagination. If not provided, the first page will be returned. The cursor is a string that points to a page of data.
	Cursor Cursor `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`
}

// GetAllRoversParams defines parameters for GetAllRovers.
type GetAllRoversParams struct {
	// Limit page size requested by the consumer; must not be larger than the maximal page size
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Cursor cursor to be used for pagination. If not provided, the first page will be returned. The cursor is a string that points to a page of data.
	Cursor Cursor `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`

	// Sort list of fields to be used for sorting. Default is name
	Sort GetAllRoversParamsSort `form:"sort,omitempty" json:"sort,omitempty,omitzero"`
}

// GetAllRoversParamsSort defines parameters for GetAllRovers.
type GetAllRoversParamsSort string

// GetApplicationsInfoParams defines parameters for GetApplicationsInfo.
type GetApplicationsInfoParams struct {
	// Limit page size requested by the consumer; must not be larger than the maximal page size
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Cursor cursor to be used for pagination. If not provided, the first page will be returned. The cursor is a string that points to a page of data.
	Cursor Cursor `form:"cursor,omitempty" json:"cursor,omitempty,omitzero"`

	// Sort list of fields to be used for sorting. Default is name
	Sort GetApplicationsInfoParamsSort `form:"sort,omitempty" json:"sort,omitempty,omitzero"`

	// Names Filter by application names
	Names []string `form:"names,omitempty" json:"names,omitempty,omitzero"`

	// ShallowInfo If true, the status and information of all sub-resources will be omitted in the response. Only the information about the application itself will be returned. This will significantly reduce the response size and time. Default is false.
	ShallowInfo ShallowInfo `form:"shallowInfo,omitempty" json:"shallowInfo,omitempty,omitzero"`
}

// GetApplicationsInfoParamsSort defines parameters for GetApplicationsInfo.
type GetApplicationsInfoParamsSort string

// GetApplicationInfoParams defines parameters for GetApplicationInfo.
type GetApplicationInfoParams struct {
	// ShallowInfo If true, the status and information of all sub-resources will be omitted in the response. Only the information about the application itself will be returned. This will significantly reduce the response size and time. Default is false.
	ShallowInfo ShallowInfo `form:"shallowInfo,omitempty" json:"shallowInfo,omitempty,omitzero"`
}

// CreateApiChangelogJSONRequestBody defines body for CreateApiChangelog for application/json ContentType.
type CreateApiChangelogJSONRequestBody = ApiChangelogCreateRequest

// UpdateApiChangelogJSONRequestBody defines body for UpdateApiChangelog for application/json ContentType.
type UpdateApiChangelogJSONRequestBody = ApiChangelogUpdateRequest

// CreateApiRoadmapJSONRequestBody defines body for CreateApiRoadmap for application/json ContentType.
type CreateApiRoadmapJSONRequestBody = ApiRoadmapCreateRequest

// UpdateApiRoadmapJSONRequestBody defines body for UpdateApiRoadmap for application/json ContentType.
type UpdateApiRoadmapJSONRequestBody = ApiRoadmapUpdateRequest

// CreateApiSpecificationJSONRequestBody defines body for CreateApiSpecification for application/json ContentType.
type CreateApiSpecificationJSONRequestBody = ApiSpecificationCreateRequest

// UpdateApiSpecificationJSONRequestBody defines body for UpdateApiSpecification for application/json ContentType.
type UpdateApiSpecificationJSONRequestBody = ApiSpecificationUpdateRequest

// CreateEventSpecificationJSONRequestBody defines body for CreateEventSpecification for application/json ContentType.
type CreateEventSpecificationJSONRequestBody = EventSpecificationCreateRequest

// UpdateEventSpecificationJSONRequestBody defines body for UpdateEventSpecification for application/json ContentType.
type UpdateEventSpecificationJSONRequestBody = EventSpecificationUpdateRequest

// CreateMcpSpecificationJSONRequestBody defines body for CreateMcpSpecification for application/json ContentType.
type CreateMcpSpecificationJSONRequestBody = McpSpecificationCreateRequest

// UpdateMcpSpecificationJSONRequestBody defines body for UpdateMcpSpecification for application/json ContentType.
type UpdateMcpSpecificationJSONRequestBody = McpSpecificationUpdateRequest

// CreateRoverJSONRequestBody defines body for CreateRover for application/json ContentType.
type CreateRoverJSONRequestBody = RoverCreateRequest

// UpdateRoverJSONRequestBody defines body for UpdateRover for application/json ContentType.
type UpdateRoverJSONRequestBody = RoverUpdateRequest

// AsApiExposure returns the union data inside the Exposure as a ApiExposure
func (t Exposure) AsApiExposure() (ApiExposure, error) {
	var body ApiExposure
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiExposure overwrites any union data inside the Exposure as the provided ApiExposure
func (t *Exposure) FromApiExposure(v ApiExposure) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiExposure performs a merge with any union data inside the Exposure, using the provided ApiExposure
func (t *Exposure) MergeApiExposure(v ApiExposure) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventExposure returns the union data inside the Exposure as a EventExposure
func (t Exposure) AsEventExposure() (EventExposure, error) {
	var body EventExposure
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventExposure overwrites any union data inside the Exposure as the provided EventExposure
func (t *Exposure) FromEventExposure(v EventExposure) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventExposure performs a merge with any union data inside the Exposure, using the provided EventExposure
func (t *Exposure) MergeEventExposure(v EventExposure) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAiExposure returns the union data inside the Exposure as a AiExposure
func (t Exposure) AsAiExposure() (AiExposure, error) {
	var body AiExposure
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAiExposure overwrites any union data inside the Exposure as the provided AiExposure
func (t *Exposure) FromAiExposure(v AiExposure) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAiExposure performs a merge with any union data inside the Exposure, using the provided AiExposure
func (t *Exposure) MergeAiExposure(v AiExposure) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Exposure) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Exposure) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai":
		return t.AsAiExposure()
	case "api":
		return t.AsApiExposure()
	case "event":
		return t.AsEventExposure()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Exposure) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Exposure) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiExposureInfo returns the union data inside the ExposureInfo as a ApiExposureInfo
func (t ExposureInfo) AsApiExposureInfo() (ApiExposureInfo, error) {
	var body ApiExposureInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiExposureInfo overwrites any union data inside the ExposureInfo as the provided ApiExposureInfo
func (t *ExposureInfo) FromApiExposureInfo(v ApiExposureInfo) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiExposureInfo performs a merge with any union data inside the ExposureInfo, using the provided ApiExposureInfo
func (t *ExposureInfo) MergeApiExposureInfo(v ApiExposureInfo) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventExposureInfo returns the union data inside the ExposureInfo as a EventExposureInfo
func (t ExposureInfo) AsEventExposureInfo() (EventExposureInfo, error) {
	var body EventExposureInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventExposureInfo overwrites any union data inside the ExposureInfo as the provided EventExposureInfo
func (t *ExposureInfo) FromEventExposureInfo(v EventExposureInfo) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventExposureInfo performs a merge with any union data inside the ExposureInfo, using the provided EventExposureInfo
func (t *ExposureInfo) MergeEventExposureInfo(v EventExposureInfo) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAiExposureInfo returns the union data inside the ExposureInfo as a AiExposureInfo
func (t ExposureInfo) AsAiExposureInfo() (AiExposureInfo, error) {
	var body AiExposureInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAiExposureInfo overwrites any union data inside the ExposureInfo as the provided AiExposureInfo
func (t *ExposureInfo) FromAiExposureInfo(v AiExposureInfo) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAiExposureInfo performs a merge with any union data inside the ExposureInfo, using the provided AiExposureInfo
func (t *ExposureInfo) MergeAiExposureInfo(v AiExposureInfo) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExposureInfo) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ExposureInfo) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai":
		return t.AsAiExposureInfo()
	case "api":
		return t.AsApiExposureInfo()
	case "event":
		return t.AsEventExposureInfo()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ExposureInfo) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExposureInfo) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOauth2 returns the union data inside the Security as a Oauth2
func (t Security) AsOauth2() (Oauth2, error) {
	var body Oauth2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOauth2 overwrites any union data inside the Security as the provided Oauth2
func (t *Security) FromOauth2(v Oauth2) error {
	v.Type = "oauth2"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOauth2 performs a merge with any union data inside the Security, using the provided Oauth2
func (t *Security) MergeOauth2(v Oauth2) error {
	v.Type = "oauth2"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBasicAuth returns the union data inside the Security as a BasicAuth
func (t Security) AsBasicAuth() (BasicAuth, error) {
	var body BasicAuth
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBasicAuth overwrites any union data inside the Security as the provided BasicAuth
func (t *Security) FromBasicAuth(v BasicAuth) error {
	v.Type = "basicAuth"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBasicAuth performs a merge with any union data inside the Security, using the provided BasicAuth
func (t *Security) MergeBasicAuth(v BasicAuth) error {
	v.Type = "basicAuth"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Security) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Security) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basicAuth":
		return t.AsBasicAuth()
	case "oauth2":
		return t.AsOauth2()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Security) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Security) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiSubscription returns the union data inside the Subscription as a ApiSubscription
func (t Subscription) AsApiSubscription() (ApiSubscription, error) {
	var body ApiSubscription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSubscription overwrites any union data inside the Subscription as the provided ApiSubscription
func (t *Subscription) FromApiSubscription(v ApiSubscription) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiSubscription performs a merge with any union data inside the Subscription, using the provided ApiSubscription
func (t *Subscription) MergeApiSubscription(v ApiSubscription) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventSubscription returns the union data inside the Subscription as a EventSubscription
func (t Subscription) AsEventSubscription() (EventSubscription, error) {
	var body EventSubscription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventSubscription overwrites any union data inside the Subscription as the provided EventSubscription
func (t *Subscription) FromEventSubscription(v EventSubscription) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventSubscription performs a merge with any union data inside the Subscription, using the provided EventSubscription
func (t *Subscription) MergeEventSubscription(v EventSubscription) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAiSubscription returns the union data inside the Subscription as a AiSubscription
func (t Subscription) AsAiSubscription() (AiSubscription, error) {
	var body AiSubscription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAiSubscription overwrites any union data inside the Subscription as the provided AiSubscription
func (t *Subscription) FromAiSubscription(v AiSubscription) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAiSubscription performs a merge with any union data inside the Subscription, using the provided AiSubscription
func (t *Subscription) MergeAiSubscription(v AiSubscription) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Subscription) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Subscription) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai":
		return t.AsAiSubscription()
	case "api":
		return t.AsApiSubscription()
	case "event":
		return t.AsEventSubscription()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Subscription) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Subscription) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiSubscriptionInfo returns the union data inside the SubscriptionInfo as a ApiSubscriptionInfo
func (t SubscriptionInfo) AsApiSubscriptionInfo() (ApiSubscriptionInfo, error) {
	var body ApiSubscriptionInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSubscriptionInfo overwrites any union data inside the SubscriptionInfo as the provided ApiSubscriptionInfo
func (t *SubscriptionInfo) FromApiSubscriptionInfo(v ApiSubscriptionInfo) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApiSubscriptionInfo performs a merge with any union data inside the SubscriptionInfo, using the provided ApiSubscriptionInfo
func (t *SubscriptionInfo) MergeApiSubscriptionInfo(v ApiSubscriptionInfo) error {
	v.Type = "api"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventSubscriptionInfo returns the union data inside the SubscriptionInfo as a EventSubscriptionInfo
func (t SubscriptionInfo) AsEventSubscriptionInfo() (EventSubscriptionInfo, error) {
	var body EventSubscriptionInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventSubscriptionInfo overwrites any union data inside the SubscriptionInfo as the provided EventSubscriptionInfo
func (t *SubscriptionInfo) FromEventSubscriptionInfo(v EventSubscriptionInfo) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventSubscriptionInfo performs a merge with any union data inside the SubscriptionInfo, using the provided EventSubscriptionInfo
func (t *SubscriptionInfo) MergeEventSubscriptionInfo(v EventSubscriptionInfo) error {
	v.Type = "event"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAiSubscriptionInfo returns the union data inside the SubscriptionInfo as a AiSubscriptionInfo
func (t SubscriptionInfo) AsAiSubscriptionInfo() (AiSubscriptionInfo, error) {
	var body AiSubscriptionInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAiSubscriptionInfo overwrites any union data inside the SubscriptionInfo as the provided AiSubscriptionInfo
func (t *SubscriptionInfo) FromAiSubscriptionInfo(v AiSubscriptionInfo) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAiSubscriptionInfo performs a merge with any union data inside the SubscriptionInfo, using the provided AiSubscriptionInfo
func (t *SubscriptionInfo) MergeAiSubscriptionInfo(v AiSubscriptionInfo) error {
	v.Type = "ai"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SubscriptionInfo) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SubscriptionInfo) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai":
		return t.AsAiSubscriptionInfo()
	case "api":
		return t.AsApiSubscriptionInfo()
	case "event":
		return t.AsEventSubscriptionInfo()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SubscriptionInfo) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SubscriptionInfo) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3fbtrLoX8HiOR/SvSnJSdu97/b9ch1bbnWb2D6S3HafJNcLIkcSTkiABUA5apf/",
	"+1148A1KlPxI4uhTHBGPwWBmMC8M/vICFieMApXCO/7LWwIOges/fx+DSCN5ylIq1f9DEAEniSSMesfe",
	"SSBTHCGaxjPgiM0RkRALxEGmnEKICEVyCYiDSBgVgGYsXKM540guiUAJXkDf8z0RLCHGavSYUBKnsXd8",
	"5HtynYB37BEqYQHcu7vzvd+nTOKoBRb9rQFKjGWwJHSBAk4kcIJ3mPDO9xLMcQzSIuMkIadLTBcQscUo",
	"dICwBJRS8kcKiIQKBr1MDoKlPAA0Z1HEbhUwCikJlhI4RQvO0qTXk4DjXm+GBVxhufR8j6gRE/M3xbEC",
	"DVfn9z0Of6SEQ+gdS55CeWF2MUJyQhcaeScJGTMcxjj5TKAXs+8M+CSBgMxJgBW0jwN+1vZCwdu2hDoc",
	"uy3kNOWC8Sbwgf4dSYZmgFIBoWaRBC8I1RP10WiOKJMo4WxFQgh9vYw54UJqJkK3JIpU54zx+kghxI5L",
	"BMLIgIHkEkuUMEKlUPNh053NUYilZg297j9S4Oti4WYcb/Pi3pCYOLhSjy/Inwq2P1IQEkI0W2v4A0ZF",
	"GgP/3yhOhdQLnAGKMF+AEhDYyI4YfyIxjlA+UAuQkZ6/DGMIc5xG0jt+deR7c8ZjLA17f//K8z09ruJ8",
	"9TUXAy+dcmfMVsA/F9lxO/lutDZZYjX3iM5ZE+zRHOkRNFhCYpkKhKkS1wZNhFG1GBxFSKSzHEaR0xmL",
	"iZRN+d5HlzQym1seCs9YKvWvOEkiyz2ISAHR3Em6xM4kyIJqdqMyWiMOYRpA9UDRlKVAlySGPjozW65I",
	"fo4jAW0ULUrYcZKM7p3TwoyxCDA1iGXcQeYREVKhbE4gCkWdlQXjktBFBT5a2vA6dGqKMlhAFW2+M98/",
	"+I3tvlO0YTCiz6nXOBwbblP/CxiVYE7MEv4HCWezCOK//49QK/irNN1/cph7x95/DAqtYGC+isGQc2bP",
	"xioGXp+c3YyH/3U9nEy9O987Z3xGwhDo00Fwfjl+PTo7G16o+S+YPGcpDZ9u+ovL6c355fXFmZp+AnwF",
	"3LR9Mggmw/Gvw/HNcDy+HCsgrilO5ZJx8ic8IR6uL06upz9fjkf/PTwzUIg0SRiXEL6FkOCpJt6ng2Zy",
	"fXV1OZ4Oz27eDs9GJ9N/Xw01I9uuWq8jw08JEynXgCWcJcAlMbyEE3Xq4mgbBCe23URyLGGxVkvPVaKm",
	"iPa9gPAgJfI1B/wR+LbhT6ut73xvjkmkjoZtPc+zdne+FzEcvsYRpoECYkvHN5XGSsZgCfkxv6nnOGt4",
	"yqjEhJrJOcRsBT8XtkXNllASWaA1S5X4FFrTWiOMMtFqjBItN4XRY4qjQw0cohnMGVenLr/FPMyOXat3",
	"qEHVf9+eXiGhuVNJX2UjOHfH/oA5x3orBQQpJ3K9bemTrJ0ag6dK35kCNpPks20aYFp0csEhLfc0AE4T",
	"Ibnq5Pq4wpxgp9FkMQKW/lHW0s8PnbenV57vTYdvhqeXF9Ph71P1Q/MQ8r0VEWRGog5I+rVoac6uTK95",
	"Z0b1C66rDFviqGJNBShs9j8QSAVKwdCZAoSj6HLuHb/bwsSFILjz65IgQ32GGEycZ7Ebnkk6K+G9PvRG",
	"QbEPo+9Frm7Scm9QDvH25e66BRVUPew2lOznzZvQ5JKTqxEqUR98wnESqeEHQMlAgpA9nJDB6qXnYI2c",
	"86vjvrGiLciAQivgQinHQCVXYPndhEbFMSFBS46Y0JHp+7IuRmpbWrbcdY9tuDvlgCWUVMyOW1tGv2Nj",
	"rfSq414p80qtVlozU/ZFrlcv01lPBCyBEOEgAKEVb6VXcBZpYS+VMSmRGtlYZ5AbZ310zjiCFfC11A4i",
	"UBo/IhIFmKpThSwoUwjyHQxRw86HGn70FjToK8QSmusbQwRYgDLAASmzHzhhYYXCXh29+qF39H3v5Y8u",
	"2qoMVx/9rPhfQWjC2G1EZORWmS0TCWhOPoGxCxPg2pqjASASK8kMsfYVuk4BO2QDlAnEmEoS5DRuXHWV",
	"uV/2X/W/93zPmsresff/3r8P//7+fb/0z39umPaaR82ZL/UfOELX4zeKQrhFOWVSs1gx/1LKRBwPBvaX",
	"fsDigW0tBqsMutyXkHLiJI8yc+ldL9BS3a9tjKYExNhadk2CuokI/bhVNrzRjcpCaGeRkoNw55AkGxdQ",
	"Bv5BhARxeGGuWz0wlc2t+F1wQnrWBOeAw0sarTO3SoO2jFlen/UCx5AJlVyAVybcZQ7jhdl6XJtWLhFU",
	"pToSZu4E3yHea5t0nYT3F+d20IMh9a0YUtYZ/U2ZUU9p4bScDXsaNslOlk2yk05tAztfkkbNDUjaLRwR",
	"Cnso1Fm46tHUaTvB/sp0hvevSJUuqVprrenSHfTr8o501K6n2f5vUK//6yVSGvYeurXEJIIQhVUlW0et",
	"SARCMlrVQEaUSIKjXAG9JXKJAi1qAcuUg1OjlkRGjqW9zaZApkF5ore/XiFrWLSOuF1VVnQRK+hKwZyt",
	"6nK8SvZUkbNldFCQLSV8XvXYArFROa7oZB2EwV76crscuIe2HK97Sib04rXVmON1z0rVh9GZi8Eqk+4w",
	"x7115grq99eCc/x/cGQrNOlS1D/jMCSG7a5KDc2ia6odWuGIhOro7FWGUUKbWVXNqGeLlIRa9GlrnyVA",
	"cUKUBBS3eLEAjl6EkHAIsITwO2T5tYGiGglXQW8h5cry9z/dqlj8Vs64yqo/r3yrgPIwUs49ZGNliigX",
	"jK+b23tqv+SyS6mqZZT/dHNyNXIqjDuJwj46NduqiUcyFBIOgYzWCIch16Sjmmf80FGEAiW9OWO91ffe",
	"fm4GzUyhWjR6IdKZAK3skvC7yrybp/maxM+uMt73VkBDxk8S0sTkb0uQS+A53ejEKIpMD0tIjoSPNrdK",
	"TqTlSevozRfQhSH2P4FqsjKTJd9UzCm5T9Ap2RZ1yhCixu0uRc9LvTa5IfYzvPOkiWyxNYebTf7AbvPl",
	"CnhMhPbE8zQCoU7COVmk3J6Wlk3ySTqbzuVp2xYeLGHFGS2tweHHKieLhUAlmRPgJjeygP2PFJRhj17A",
	"HymOBCKciNOIAJUjLRab7kIztdP8sQECnY9VmkS0IWSzmeN7wDnj3cnlyuS+uBCWBei7D1ZxFDlGzCh6",
	"SPEsAsfpOKKhWqmS4HOUtVZCE0yPNqTUZajvkZ2YZgMWypvrlFtFgwkEHGzGQ3bQuE+1s/z7MboWgITu",
	"qdDWD0pDIUKFBJwlKBods+45JRRhNE+lTqUwIZ++UxvhRIyESIFbOnS2mLKPQIc01Am7bQ0ztaHxgc1M",
	"nktbx0QQl1J0NRkhsRYS4iyZvsR8WEocLI1K5Nj6Qge5mox6L4++//Ff/6iG89Tv7456//rw1z/unIG8",
	"AvsdzpGspVEU+AJL2IzVrNVVOouIWA5X0I7YrO2G7x1Uk8sVcBxFhYYiSgdNd6ZonG0O7tAZMbNoBxlx",
	"hiV2jXSLOSV08SA8+yejrUd81cAvH/lWyfrTuNAsqmsCwMHudc5q4aP6LpTlaxmPuQQvoSQTZy1ncjV2",
	"VTrbT66nl57vTUZvr94MPd87v7weD/89nDhzqdQhqpiuzYdQYruJsmjdgTGNGTXUW5BL5uD10+zIF8g0",
	"RrgyMYp1R7+q34/PT9E//vnDv/qlLLGLywu1qKvLydTzvdcnk9Gpc2EJE/INW7BUjsHYVNc8qtLZ1iBS",
	"opg3MPte6lA6cPieYzvD2Q19prkbQZOZt6+iUC+6W+VlWAoFrk0g5FapCx7Ooha+3IyC2rQPg4yHgvQ1",
	"FiRQ4DbhSrAQt4yHG+ApmHWWj+Mi4lQAbzl23ZZL3sEvwHDJj9OS46Mx62kjzl0YN9WlQptKdx7hhVbn",
	"lIn+C6MLZIPnaGZGzQIRSCxZGoWZB8RlGddTDrJJneuyV33G5cB3N9Os6NLNvV26kjM6y/062V0j9EIu",
	"gXAr7ZwWwp0jl6LTmooYfdOhZdueZfdLuq857+uIdqp2SF98MhZK7o7K+5Rv08wAxcAXEJq4kyIBe98F",
	"8XygcgeJPwJSujGEQANAWv9v6fa+s33YpIVOYlirKg3Etiq/KxylXYVGfk2jht3z094//9fRP7VhzHiM",
	"TA8k1DnJKMJ0jbR6oLi6GovUkUEnXLrDKQvdUJvrQ93dC6r5JnOJColpi1Qt1Ff7yebjlSOOrXKyk9Qz",
	"w7h4R+vdG1KFCo+k0dOBj8JdThTfMyLARuyVennn3ysDCRTEZfG8kcSzdlnHaVu6iQ5H7GDTq8GMwufy",
	"Jj1losxT5MIUuNtKRLv5+6r0tz0hRgPS2TNX2qXuAktyslhsd7jqsae2rVua6dk3hyDLAZZuGCuR9NaY",
	"jAMC7ZLemE1xolQOLivJFOpMW7NUx91MunHhYDih5lekEGBdUYD+SEnwURnu0kQgHjgAkqdH/N/J5QXS",
	"uAFX1CKjn2rvf+dLMUC/EJBgriM6+kQOmRTVSE4IfQkRfGRxHyjpF6vru7OiSsnX5aTqo/7R1iQMy4rd",
	"85Sbu7xnrNdFLt9CtLe57s8Y720Cs1vS94b+D0sILp2/zlhKyDa5C4sl1PirEaENoWcZTgdrC4braYb7",
	"LGncDc4sRR4rTOrchj2Dim0y3Py+MbAY4Cia4eBjh2Tty0ReptJZoEDL/XK9gJCB0EUiKEBowuFl21Vx",
	"aWa8sjn6mXHyJ6O+ToNWTMsSiVhq4uUSzdZIgJQmtZlo0aB21JgxTX9SCBFRwqBVjwNlIQTwE8ifpUws",
	"to3X7ZzxnwFHcnm6BIOUDcUYlrolClTT3Gqz128yQsbop+E0z8a2UQldrwH9PDw5y760LEWzyRgkUDX/",
	"lLhyDka6QkHChCCzCBRyInZbt/2yIXSOrZr+nyjEa9FHEwD0LmSB+PAiSxAMYQWRopH8OAthoJoMBA8G",
	"EvOQiJsgFZLFwG+WmIYzxj4OlmYTB3Zfe8oAXRG4HZzqpjf5Mm7UOgbfvafOIFxZA29JAMkDHPYgKISJ",
	"a8QEryOGw1Zq4GAJhoC4Aj6BgNEWV4UtQ1IguyhgVB5F0QASehy9yE0FS9T8kq/xLAIjaJS5uSFX+ufp",
	"9CqrAhKopuZSAOamRAsJgUOI8jFrpn5z9kbOf9PG2eoP3Esb3tE8LeiixuDVDW7XffZON2gK0eY5Z2m/",
	"Monbd+lo2RayegC7ZlrsTN1oX2EaQDiBCLQL+JxE0jRsjJRVKyma7OQqLvV9a10peeUWj9AgSrXmn62y",
	"9Msn89cHZ+CxAbfbMGiHsZQ12UReydsRErVTMaFYGsdTjJPEXiTCpMPldF9ninS462GpvKsdnG3p+sJU",
	"otGruPM9RmGPSya7WeBd7+V/2IDcvNzRPRFsCwN1Q7Jt3B3RWbjmoZBtx9sB4Z161NCh1b/zUl5Ylf3/",
	"ZNR1yFyZW2Kl62e6IbpdkmCplTN1zmCrZqTCmPJ5+lnpoHFdwLEc6Hb3bUxTNeC6aKmSs9VYZltaRhfL",
	"QGcTqH3bsWsWQd/S8K7VPiktruwxbt6hafdbJ22Zgm2+4vqZ2+oL/onjQj3LRPbVyWTy2+X4zPO90zej",
	"4cX05nQ8PBteTEcnbyae742H5+Ph5Oeb6eUvwwunODc6d3ONSiVtSXt0ie1RMgb1vQhq1k69KGK39w0x",
	"v8kM+yrv/HwyHV6eTJC2+2s1ARsxBwqfHIaU0mWvx6PcP6ZamVJ66peiJF8xsK/v5IWI0fKlTwhNnAeZ",
	"uMr2zDcB0Xw7OEHKuVK0N0K063UiPbVvEPLBiW0hgQIvzvl6oFgrf47oaV7czWoUWf27yI6oDMwklTvd",
	"iC1pup3VjSpYv8C6p7dFqetmBKvC67qKugJqjvG5XrSu/RhIsrI3r7arLxnSupv+zczK2yXwErKMU1fL",
	"f6t+Kwt3CRSVtXFlib7PB37vdaC9urVe6IYmIe5GAJU35rxuJgOaviiGYIkpEbFGXQ3oknKZL9l3jP7B",
	"7yJj3tQvk9ckVi7JNp3WVt7dZWB0Oott0/LRW73Z3jGma8rdbb0bkkHm4sq3QfKQ96bue4+pDk7Dt/0F",
	"wfYZ3cZ1UHa8JuRn0HVZZrf7Qi0Xf7qnzd5nK7s6gMc2zmD8MwXSNlw32eFeSR1xDRfwZ6TdS5zK5SvH",
	"Fm7K6jYff4H1hq9FvnejwaKsYW7alkIVvfM354txmHMQS20JdA3sb1cFynaFvnSy5aDTHUr7Wiu4ZDYD",
	"8oSvWm5niCUu5XnptBZ7ews+SeAUR2h0doVWBNuaIQIxnuk8upR7HjYzIBSnovrq+baQvFM/r7uimCGM",
	"B0i3c5JdJQu7iSrj/WwUcMY01FWQiRT60v4KU1ktiVxxM+nbcUYzD0AIc4DOdZEAz/dmEQs+6r8SoKH5",
	"qIgwAq2EhSbVmap/XFhotdoCnIqWBGBGpTULHEqSsvXchBmDEHjR5tsuMjW7iLgxzBvblI3vW9hdO3aV",
	"41BtToVUqMFUgUU3vsM2TFayEOvXvNJITlkEHLflFi9JCCb3uFSBx9GMpbzCw1nh8abDPCY0NSvs0Fjk",
	"wYStjV26pjtbsWMOSHvGY9N/nZcH6p7r6PY6lwnJkQdPfi1yHho7/ZHQHU9/XRUpwS05c0mr42DTXYYS",
	"kBak/FQvptu09Jqa4KghaMuh54LLuNcCsz+ipRq7KEk92FHo1USQuZh8It0VWIxVV5nkFovsOnPZolOK",
	"Sk+SGDbfpnMHssx3Y/py/WyJNihJpItVWQnRKHlx7ztp2eU2N1D681PDxOrH3U43lCxgO+9nhIVEeefO",
	"25o0Jf2WZVeaW6UbuiRdQP1yk3vPshZPu211XVoa50wdPfXddQoOt48eN24VbbtsUmp95zdvFD/cheD9",
	"77fudbe1dPFJkfHZ9LS44TpnvEigd99nDSSr5tipX3ovX33/w4/V6476d33f0V221BinpRyydPbDK1Oj",
	"8lWvF69x0qkSDml4qTdhrubTvvO9qMW7t9lj4OhTGqv7TmpqzYZzXpX6Mm+q7lia4v4XPzddryyVHb0V",
	"W33kf1Z145rk2DORc2wrQbTlPJfz7gxhN63CrzrNs56+Z2+v1p5tqSFbScR211aJancp3lMtDeGSt3RF",
	"OKNx9QplKakknbl9Fu7amFs04PJsZmw7kl9dYCuSPqOLU8/f2a9pQdlU+rEq7lwmzevWupnqC1JWSEbK",
	"J1cjnZ+nh0PMmQCXHWbN4YYXo7y2kG6kmKCcdPkC+os+eq9LCuWVk5P33netiXZFVK3L4WFbb87SGxaZ",
	"veWlohc40m4qSVb6Swlz37UomrlJ2ooH02gjHphcAu/1suFasGGdYvvio5kitUv/GlXmFFBCQitp7p64",
	"fW/Bf6eTS/Qwxo87ZlIj/iQIIJEQduH9mle7xdVnS7wkLIryoCi3s6G8zsBuAed2Rbzs1m4mf2ZfM9pz",
	"1lFxuuVqiQJpjGlPCWCdSGPblSx9oguPKhsmW6rn7yjCg6LqQuG+2xC9cWxm043RHgO4N7KCRhWYxoA2",
	"+eAFhdvvsvoHpvxInubQHNZ0Gn5KCAfhMpB/y2zjbHw7pM7mBt1Pu1gKz7vekx0M5gex7u9hblt4T7di",
	"OOGwIiwV6IXt4kSzb6vKpVSSKENGgWCXaK23ad8E2xS9YFH4XTatkCwRaAZaylsJ0xH73blkb7t9zxsb",
	"bUJ4GyO0q9YxWXAjF5OUJ0zY10CyawlWOUb6OLwlonp7oiraJ5WqPrsBWHDSV8Sj3ziPNCh7UioOuCk7",
	"tyi80ULmRYUPP4sZtkk+8/W+ibb5MJubFXA5oxg2Q6ZB/BvfG7gFslhK1y2LmgaSj+KcuiV+VsQri8hk",
	"Ho90xc30QC083BqDbI8lbhGlWce2JaUOpW/HenvFgjb59e8/1Of0cN8X+i271DzlMr+1lg3Ozas5GfdN",
	"1q+Msy1Zv9Z4e7J+3e9232T9xnWf3S8I7fJs3jbE3/emRGOsXTag840JV9W7h9yI7jcndu7lQJFxD5Z5",
	"6c73yvU3HEURbE0P477UL7nrv3RgSv03ititcXJn3s9KVI7IpbIB4ZOylYhEpUob7vv1W/Jr2s6YXyvV",
	"QLKDZngxHY6vxqPJ0PO93y7Hb8483/vvy4uhOzE2KyA80XUVNFiXJ1m6WK0Qg/7dako3AQft+MeRQPOI",
	"3So9JWK3Je3ytGhhHhXOsrPM3dNjHMaEHuMoUkhXf5ecyTiKUDn0XenCZvNU2OKitmfxU9dBFFHk3dV/",
	"tndcprMMXHdTcyHYulqLPhV4L7dC2jKKBXi8AVRHT5EmwFdEMJ4NUCkCvjv2FDl2wYJ1NZd77YUHxzid",
	"MVHtmwrgFvIqDnYcorKMykj7rUkP6tqcjgvMkhL11Sbn+zBKmx5wwFEszD+DQcKZZAGLBiwBSsJewCiF",
	"QA70SBVzwqrid1Y9y54Rx4FWkiHWt5e887evb6Yn47PR5GZinh7/P8W18+KZfdPE8720Auyed9XtI+eD",
	"5v2Mk6vcuWymzMNTSYQp9NFvphwbEejkalRULIgxxQswhRC0cS98VK/1bn6yD5AIH52TCKoNtB3brOYg",
	"+nmBrmPjdkCmfn1eQsb73taN+aQfSyxyrL0RnXMsJE8DaePvtr6/7WRf8FxqATvACcmfR9S/LFym8Dmx",
	"WUflVwUtZU0Niao9wdk9aO8nkCdRVGmtp+U4Bqmjz+/qcwQpF4w3L1IR9VHX/C6Iw7T1/NL78/UD60Ph",
	"pNfrenV0tOFd+93es299BNTxxP3lL2oLfjCzuwbNoRy8xmHmV9JdXm7vck2zrA8ITafvt3c6Z3xGwhCo",
	"6fHD9h4XTJ6zlJopXv7YBS7LcRC+hZDgLG37xy54MNa4qft3V3m64F2hc7xrKgeuc7txJDdPyuaB5ThE",
	"PiiCEmkcY81kbobQHRUbvas+Zv3BltZ1ZLroWD7CiMJtZawGR5mWtSY2ivWahetHIe5qqsHd3d1dg6te",
	"PcrEmzjq5PR0eDUdnh346qn5qsFDOcfU2GMTWbdwyJ1fO4wGf+Hyo93hneEe7f9yvPanfkeYbmYi06zW",
	"pHYquXBYNKk+5h56jnPmBwd4wzfDA8V+yRTbSkCtAn2DokQRfCJC16/aSI5KS3pcWjx6cul80Heer77T",
	"Ttftak/arvUwjlIdTa2zHUp1AncIQYS5SSC6up72G/xjYrEPz0KPq1RVI8hfilKVBREPzPuFK1WtXHMf",
	"3WpQJGTtfq5pJwYHmXKqryXleVobT7tJ1urLPfNaL4IfTr3DqddK9ZuZ0L6g3M3XlrkOu3jasrbPy8/m",
	"ekv8wH/foJetRN4lBsse997uYaOlQcq3Alu8bOPSQ+ePog7aCZ7aw9Z4Fv/gX/uK/Wtlom5jjNq5o1U/",
	"+3UXp1oxS4tLrWiws0KXg3Nwpz1Hd9oWAt3BldZGhMa0eCwKPHpiAXxQZr4VY2IrZzjdZ9e5+d+FN3In",
	"2QOyx2NqRE/tHjtoRM/hwNnGE3uoRvv4xDIDYxePmO2zvz/siQ6vgzfscIDtSu+b2K5SjrKLP+xqhGrZ",
	"cx3cYtUeO7NX8bjtloanxlXWoeWEcfnoamZ7CVo3v2bVIDUsv/fGuqpS75SltPU9XNth8LtpbNre+d7v",
	"vSmTOOrYWbe1fe8OUuMLkBqN1PnWFPFdBE0tvb2TAGpNCm9majtypFtzsTd4GRvSoiTAqgWwqx7HLBXb",
	"/TBlxV1TGaaP9Dd9jZOGJrCn/lNkbxOBsFjTYMkZZanwbfFAItDtcl0uFEgEWpAVUISFmglTcWtLyaOr",
	"y8l0cHWdP0vmI0FoAIjUXhJbYlm9oSIZmkFWCRAtsXnibQ0SzQBoUU0O2Y76sTE7gql5SPJCgn00mpfh",
	"xXMJ3HwkjKqGxJR4APS+VF/0vedXYdJl82eA/kiBk+zVtZ+GUwWsAF39Ti6Bq8WVyhgiker0+HkaRWvE",
	"eN7MXEoc5EXlMAd0y4mUQLNiugbgHP4M5IENw2rIA8Y5BNLPqpRkRejsYrNb2QJ0FV97pbOPLrPb2erX",
	"97Y66nuvj2zN21dHL1EMmArf7M4t5Nd9y7V9NfFIXcBfwU8ZEmudeE8CtVYBMabqb7NYH81M5QkO5vG9",
	"IEjNqy665JpdtdmfYil9NNUQZCtZstsahhDRDwPmQNk6EJwlnChE5YWd2t3uk1od7UcyNTcUj398g7Ol",
	"JPvB7PwazM7mybPJNV8n5w2niVMp1hZppeUWl/3f/jaKFdYwlcd/+xua6ichI8gkbMgoVI6TaK0ED1CR",
	"cpf8VwIUBzLFSmiaOUNfP0ahL8TYAj3mwUvbxdRAMGIgALIChNEPRz/kJ0Ifofe04h6urE8XqWiJMNSx",
	"ubOhXMPkIdrwbLmwncC26XSdXT31UV2unXsan91I9uizHE4HH8/BWvt81tpmVtxstHUPqRxMtYOpdjDV",
	"WsKJj6SNPb6999QBxoO995w1zQ4nx0MZfvsEJCtj7BSWrPTcPzj5pArsIUT5fNTXp9ZSd9Uzu8Q8Xbxu",
	"3ijdMfbpKBGyNfjp6PNthD+bCz8EQA8y6WBSbw2AuiVGJs+aX/cMgjYHOtjWB9v6YFtbFnHw2eMYxs2J",
	"njQU2pz+YBw/22Cok6g3niwtuvLgL2i0fm5B0SY+WsOiTrxuvP+rlp9S8kcKiISNR5Wzi8D6LdX8HrAL",
	"5V65+Kw58He5JXwItD6zQOvuHN412OocuWHxfrWccPSZTtSDC+xgbn4REdx9JEfXKO7B1jzYmgdbszWO",
	"+zUdmk9hAD9pbPhgAH+L0eHHtoR3jhI35+weJ272bYsUP3PV+xB5PqjdX73avTWk3Sqe4iBpDWm7YtNv",
	"g+Sekeks4PyYTF2H8lCF7lu89/4TSB0dfXt6hURbcLROKpXQqCvK0+jwOCpufZonjfDUJz+ot8+k6lyD",
	"FTZzgvOEGPyVqXuN8I0r0OHkl20RhQuGTi0hH8jqy68VtyNZ+a0axnZiOfosQu6gIDxbBWEP6r2HhYzm",
	"LIrYrVLjtfcTSwmcogVnadLrKUh7vaytforVaVEXAnhXO9q6310uxc+k2Dyp5+6g2DzT4nEPrtg0vXFb",
	"D6vcg3ZwVh0OrEc7sEoxJDb/to4vxbVcP9m6/eKFedp1610L0+zbuF6h13q4UfEg4uvgOv+qLkjkbJ4J",
	"Rv3DXtcgzFiHZJRDMsohGcUyhWGmxzEX9dhP6vzWMx4Mw2d6owFlxFo/CQrlckDonLVqmGPAIVIttG4Z",
	"RahEadv0zVLLkZrji1E7/aYeHSkpMluXl4eU/i5anhzLvhVMRiTEwqHI+9kPmHO8VpSwHcolVnaHRtrj",
	"68hqmoOOfNCRvwkdubs82yAx/9L/PqvrXHqVqGf0Jg4xW4HqyXU5+wGapLN8bQIN0PBTwhSgovXGV3bw",
	"7CbyjUA6lLx8/jexWjWTrtetsv4NvePBKe/o6ZTtgyP7cCx+EVmX7dzZ9UrTwXF0cBwdHEfllIOHOJge",
	"yeX0pGkJB5fTN3KHqIPzKTeldnFD5QHgsvW2xQW1lwcq572v0Gdz4J2DHvmZ3SttfNpJHggIuBEFCZbB",
	"sikTRpRIde4KNZFujDiTRtuaW39ISQD0tQsmb0EEWmIaRhCimdEz1V4Job7dwmzJ2EerioYQkBBErlFJ",
	"hhLgc8ZjhNGC4wDmaVQM/IJFYQ4PxJhQgVY4IiEKU64VYdNJDUJY+J1SYDCijPaaY82wUj6ZUUL+ZBRQ",
	"wOicLFIj5voO78sYhDWBJwaBD2gIP7AKYAAc28WeWL1vo2KQ6Ya9xo4TSw3hcxN8R//agPWEs1kE8d93",
	"vNFthVwDv6eMziMSSNRz8JSy1CIlDdZKLU44W3AQ4vkrNppAjdkXRASoNHSrZYx+uWVP0bbtBvRY33AU",
	"ZuKUc6CysSfWMGmC4iubLUpDJXAyweWSVsYszTbTL1uXyhwOGF0BX0DoZyYY4hDBClOJ4FNC+FrbxELi",
	"OBEucfRTRRhlvL5nne6n89G5wP2m9K0vjysdWklbvmhXJunMrzuWKjDBlM7VCQzFfckscUjEPtgdX6H/",
	"emuhgJzrd8C7mVlvmiuj/ORqpA5RbhyZQuT+XO0pXEHYRxNDLALFLG/WEwFLQPQ930t55B17SykTcTwY",
	"/LVkQt4ZmTRYfe/53gpzgmeRYfNlns85x2kkvWMPJ6QvIYKPLO6H4PmOjPeJxHyhdBrV29de5XchC8SH",
	"F9msIawgUoKqNNRANRkIHgwMTm6CVEgWA79RhtSMsY8DNfBPWMLNkK4IZzQGKm8uV4rg4HbwH8LO28M0",
	"7BFOxHdahjSS8gHHPYVH7RKGFSgtA3CMYrzWEW+cShZjSQIcRWvj7RUZThmNTOueQawy+4jQYWytwAqm",
	"htBGn8ZpL5DRFqzjhDxDtH/I2aCO/7eY4gU435m22U+NNyOam2gHcddqt8M46nS0DuQqxWGHaVz7aB3k",
	"dInpAiK2KPXOf2vvludT2y5GbLQ2P0nImOEwxkkVZfZH7+7D3f8PAAD//x6tI/ktLwEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
