# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This kustomization is for use when the ApprovalRequest CRD is already installed
# (e.g., when deploying alongside the approval operator)

# Adds namespace to all resources.
namespace: controlplane-system

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    domain: migration
  fields:
    - path: spec/selector/matchLabels
      create: true
      kind: ServiceMonitor
      group: monitoring.coreos.com

# Value of this field is prepended to the
# names of all resources
namePrefix: migration-operator-

resources:
# NOTE: CRDs are NOT included here - they should come from the approval module
- ../rbac
- ../manager
# [METRICS] Expose the controller manager metrics service.
- metrics_service.yaml

# Patches to enable metrics endpoint using HTTPS
patches:
# [METRICS] The following patch will enable the metrics endpoint using HTTPS and the port :8443.
# More info: https://book.kubebuilder.io/reference/metrics
- path: manager_metrics_patch.yaml
  target:
    kind: Deployment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
