# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
appVersion: 0.1.0
description: A helm chart to deploy a generic common-server instance
name: common-server
type: application
version: 0.1.0
