# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xdsdemo.componentName" (dict "root" . "component" "envoy") }}
  labels:
    {{- include "xdsdemo.labels" . | nindent 4 }}
    {{- include "xdsdemo.selectorLabels" (dict "root" . "component" "envoy") | nindent 4 }}
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      {{- include "xdsdemo.selectorLabels" (dict "root" . "component" "envoy") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/envoy-bootstrap: {{ tpl (.Files.Get "files/envoy-bootstrap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "xdsdemo.selectorLabels" (dict "root" . "component" "envoy") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: envoy
          image: {{ include "xdsdemo.image" .Values.envoy.image | quote }}
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          args:
            - -c
            - /etc/envoy/envoy-bootstrap.yaml
            - --service-node
            - poc-gateway-node
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: proxy
              containerPort: 10000
            - name: admin
              containerPort: 9901
          readinessProbe:
            httpGet:
              path: /ready
              port: admin
          livenessProbe:
            tcpSocket:
              port: admin
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
          volumeMounts:
            - name: envoy-bootstrap
              mountPath: /etc/envoy/envoy-bootstrap.yaml
              subPath: envoy-bootstrap.yaml
              readOnly: true
      volumes:
        - name: envoy-bootstrap
          configMap:
            name: {{ include "xdsdemo.componentName" (dict "root" . "component" "envoy-bootstrap") }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xdsdemo.componentName" (dict "root" . "component" "envoy") }}
  labels:
    {{- include "xdsdemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.envoy.service.type }}
  selector:
    {{- include "xdsdemo.selectorLabels" (dict "root" . "component" "envoy") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.envoy.service.port }}
      targetPort: proxy
