{
 "title": "Controller-Overview-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total, namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reconciliation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of workers in use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{job=~\"$job\", namespace=~\"$namespace\"}) by (namespace, controller)",
     "legendFormat": "{{controller}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Total Reconciliation Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliations per controller",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Reconciliation Error Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  { "title": "Work Queue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "WorkQueue Depth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=~\"$job\", namespace=~\"$namespace\"}) by (namespace, controller)"
    }
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Unfinished Seconds",
   "type": "gauge",
   "description": "How many seconds of work has done that is in progress and hasn't been observed by work_duration.\nLarge values indicate stuck threads.\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_unfinished_work_seconds{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (namespace, controller)"
    }
   ]
  },
  {
   "title": "Seconds Processing Items From WorkQueue (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Work Queue Retries Rate",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=~\"$job\", namespace=~\"$namespace\"}[5m])) by (name)",
     "legendFormat": "{{name}} {{instance}} "
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Success - Total Request Count Per Controller",
   "type": "timeseries",
   "description": "Total number of HTTP requests per controller with status successful (200s)",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", code=~\"2.*\"}[5m])) by (namespace, method, code)",
     "legendFormat": "{{namespace}} {{method}} {{code}} "
    }
   ]
  },
  {
   "title": "Client Error - Total Request Count Per Controller",
   "type": "timeseries",
   "description": "Total number of HTTP requests per controller with status client error (400s)",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", code=~\"4.*\"}[5m])) by (namespace, method, code)",
     "legendFormat": "{{namespace}} {{method}} {{code}} "
    }
   ]
  },
  {
   "title": "Server Error - Total Request Count Per Controller",
   "type": "timeseries",
   "description": "Total number of HTTP requests per controller with status server error (500s)",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", code=~\"5.*\"}[5m])) by (namespace, method, code)",
     "legendFormat": "{{namespace}} {{method}} {{code}} "
    }
   ]
  },
  {
   "title": "Redirect - Total Request Count Per Controller",
   "type": "timeseries",
   "description": "Total number of HTTP requests per controller with status redirect (300s)",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"$job\", namespace=~\"$namespace\", code=~\"3.*\"}[5m])) by (namespace, method, code)",
     "legendFormat": "{{namespace}} {{method}} {{code}} "
    }
   ]
  },
  { "title": "Webhook Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Success - Total number of admission requests",
   "type": "piechart",
   "description": "Total number of admission requests per controller with status successful (200s)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_total{job=~\"$job\", namespace=~\"$namespace\", code=~\"2.*\"}[5m]) by (namespace, webhook, code)",
     "legendFormat": "{{namespace}} | {{webhook}} | {{code}}"
    }
   ]
  },
  {
   "title": "Server Error - Total number of admission requests",
   "type": "piechart",
   "description": "Total number of admission requests per controller with status server error (500s)",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_total{job=~\"$job\", namespace=~\"$namespace\", code=~\"5.*\"}[5m]) by (namespace, webhook, code)",
     "legendFormat": "{{namespace}} | {{webhook}} | {{code}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(process_cpu_seconds_total{namespace=~\"$namespace\", job=~\"$job\"}[5m]) * 100)",
     "legendFormat": "Job: {{job}}"
    }
   ]
  },
  {
   "title": "Controller Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (process_resident_memory_bytes{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Job: {{job}}"
    }
   ]
  }
 ]
}