# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rover-server
  namespace: system
  labels:
    control-plane: rover-server
    app.kubernetes.io/name: rover-server
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: rover-server
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: rover-server
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - args: []
          env: []
          envFrom:
            - configMapRef:
                name: rover-server-env
          image: ghcr.io/telekom/controlplane/rover-server:stable
          name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts: []
      volumes: []
      serviceAccountName: rover-server
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: rover-server
    app.kubernetes.io/name: rover-server
    app.kubernetes.io/managed-by: kustomize
  name: rover-server-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: rover-server
