# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rover.cp.ei.telekom.de/v1
kind: Rover
metadata:
  labels:
    app.kubernetes.io/name: rover
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: poc
  name: rover-sample-remote
spec:
  zone: dataplane1
  subscriptions:
    - api:
        basePath: /eni/foo/v2
        organization: esp
        oauth2Scopes: 
          - read
          - write