// SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApisColumns holds the columns for the "apis" table.
	ApisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "base_path", Type: field.TypeString, Size: 2147483647},
		{Name: "version", Type: field.TypeString, Size: 2147483647},
		{Name: "category", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "oauth2_scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "x_vendor", Type: field.TypeBool, Default: false},
		{Name: "specification", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "active", Type: field.TypeBool, Default: false},
		{Name: "team_apis", Type: field.TypeInt},
	}
	// ApisTable holds the schema information for the "apis" table.
	ApisTable = &schema.Table{
		Name:       "apis",
		Columns:    ApisColumns,
		PrimaryKey: []*schema.Column{ApisColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "apis_teams_apis",
				Columns:    []*schema.Column{ApisColumns[13]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_base_path_team_apis",
				Unique:  true,
				Columns: []*schema.Column{ApisColumns[6], ApisColumns[13]},
			},
		},
	}
	// APIExposuresColumns holds the columns for the "api_exposures" table.
	APIExposuresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "base_path", Type: field.TypeString, Size: 2147483647},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"WORLD", "ZONE", "ENTERPRISE"}, Default: "ENTERPRISE"},
		{Name: "active", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "features", Type: field.TypeJSON},
		{Name: "upstreams", Type: field.TypeJSON},
		{Name: "approval_config", Type: field.TypeJSON},
		{Name: "api_version", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "api_exposures", Type: field.TypeInt, Nullable: true},
		{Name: "application_exposed_apis", Type: field.TypeInt},
	}
	// APIExposuresTable holds the schema information for the "api_exposures" table.
	APIExposuresTable = &schema.Table{
		Name:       "api_exposures",
		Columns:    APIExposuresColumns,
		PrimaryKey: []*schema.Column{APIExposuresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_exposures_apis_exposures",
				Columns:    []*schema.Column{APIExposuresColumns[14]},
				RefColumns: []*schema.Column{ApisColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_exposures_applications_exposed_apis",
				Columns:    []*schema.Column{APIExposuresColumns[15]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apiexposure_base_path_application_exposed_apis",
				Unique:  true,
				Columns: []*schema.Column{APIExposuresColumns[7], APIExposuresColumns[15]},
			},
		},
	}
	// APISubscriptionsColumns holds the columns for the "api_subscriptions" table.
	APISubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "base_path", Type: field.TypeString, Size: 2147483647},
		{Name: "m2m_auth_method", Type: field.TypeEnum, Enums: []string{"NONE", "BASIC_AUTH", "OAUTH2_CLIENT", "SCOPES_ONLY"}, Default: "NONE"},
		{Name: "approved_scopes", Type: field.TypeJSON},
		{Name: "api_subscription_target", Type: field.TypeInt, Nullable: true},
		{Name: "application_subscribed_apis", Type: field.TypeInt},
	}
	// APISubscriptionsTable holds the schema information for the "api_subscriptions" table.
	APISubscriptionsTable = &schema.Table{
		Name:       "api_subscriptions",
		Columns:    APISubscriptionsColumns,
		PrimaryKey: []*schema.Column{APISubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_subscriptions_api_exposures_target",
				Columns:    []*schema.Column{APISubscriptionsColumns[11]},
				RefColumns: []*schema.Column{APIExposuresColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_subscriptions_applications_subscribed_apis",
				Columns:    []*schema.Column{APISubscriptionsColumns[12]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apisubscription_namespace_name",
				Unique:  true,
				Columns: []*schema.Column{APISubscriptionsColumns[6], APISubscriptionsColumns[7]},
			},
			{
				Name:    "apisubscription_base_path_application_subscribed_apis",
				Unique:  true,
				Columns: []*schema.Column{APISubscriptionsColumns[8], APISubscriptionsColumns[12]},
			},
		},
	}
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "client_secret", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "rotated_client_secret", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "rotated_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "current_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "secret_rotation_phase", Type: field.TypeEnum, Enums: []string{"DONE", "ROTATING", "GRACE_PERIOD_ACTIVE", "GRACE_PERIOD_EXPIRING", "FAILED"}, Default: "DONE"},
		{Name: "secret_rotation_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "team_applications", Type: field.TypeInt},
		{Name: "zone_applications", Type: field.TypeInt},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "applications_teams_applications",
				Columns:    []*schema.Column{ApplicationsColumns[15]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "applications_zones_applications",
				Columns:    []*schema.Column{ApplicationsColumns[16]},
				RefColumns: []*schema.Column{ZonesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "application_name_team_applications",
				Unique:  true,
				Columns: []*schema.Column{ApplicationsColumns[7], ApplicationsColumns[15]},
			},
		},
	}
	// ApprovalsColumns holds the columns for the "approvals" table.
	ApprovalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "action", Type: field.TypeString, Size: 2147483647},
		{Name: "strategy", Type: field.TypeEnum, Enums: []string{"AUTO", "SIMPLE", "FOUR_EYES"}, Default: "AUTO"},
		{Name: "requester", Type: field.TypeJSON},
		{Name: "decider", Type: field.TypeJSON},
		{Name: "decider_team_name", Type: field.TypeString, Size: 2147483647},
		{Name: "decisions", Type: field.TypeJSON},
		{Name: "available_transitions", Type: field.TypeJSON, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"PENDING", "SEMIGRANTED", "GRANTED", "REJECTED", "SUSPENDED", "EXPIRED"}, Default: "PENDING"},
		{Name: "api_subscription_approval", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "event_subscription_approval", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// ApprovalsTable holds the schema information for the "approvals" table.
	ApprovalsTable = &schema.Table{
		Name:       "approvals",
		Columns:    ApprovalsColumns,
		PrimaryKey: []*schema.Column{ApprovalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "approvals_api_subscriptions_approval",
				Columns:    []*schema.Column{ApprovalsColumns[16]},
				RefColumns: []*schema.Column{APISubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "approvals_event_subscriptions_approval",
				Columns:    []*schema.Column{ApprovalsColumns[17]},
				RefColumns: []*schema.Column{EventSubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "approval_namespace_name",
				Unique:  true,
				Columns: []*schema.Column{ApprovalsColumns[6], ApprovalsColumns[14]},
			},
		},
	}
	// ApprovalRequestsColumns holds the columns for the "approval_requests" table.
	ApprovalRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "action", Type: field.TypeString, Size: 2147483647},
		{Name: "strategy", Type: field.TypeEnum, Enums: []string{"AUTO", "SIMPLE", "FOUR_EYES"}, Default: "AUTO"},
		{Name: "requester", Type: field.TypeJSON},
		{Name: "decider", Type: field.TypeJSON},
		{Name: "decider_team_name", Type: field.TypeString, Size: 2147483647},
		{Name: "decisions", Type: field.TypeJSON},
		{Name: "available_transitions", Type: field.TypeJSON, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"PENDING", "SEMIGRANTED", "GRANTED", "REJECTED"}, Default: "PENDING"},
		{Name: "api_subscription_approval_requests", Type: field.TypeInt, Nullable: true},
		{Name: "event_subscription_approval_requests", Type: field.TypeInt, Nullable: true},
	}
	// ApprovalRequestsTable holds the schema information for the "approval_requests" table.
	ApprovalRequestsTable = &schema.Table{
		Name:       "approval_requests",
		Columns:    ApprovalRequestsColumns,
		PrimaryKey: []*schema.Column{ApprovalRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "approval_requests_api_subscriptions_approval_requests",
				Columns:    []*schema.Column{ApprovalRequestsColumns[16]},
				RefColumns: []*schema.Column{APISubscriptionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "approval_requests_event_subscriptions_approval_requests",
				Columns:    []*schema.Column{ApprovalRequestsColumns[17]},
				RefColumns: []*schema.Column{EventSubscriptionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "approvalrequest_namespace_name",
				Unique:  true,
				Columns: []*schema.Column{ApprovalRequestsColumns[6], ApprovalRequestsColumns[14]},
			},
		},
	}
	// EventExposuresColumns holds the columns for the "event_exposures" table.
	EventExposuresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "event_type", Type: field.TypeString, Size: 2147483647},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"WORLD", "ZONE", "ENTERPRISE"}, Default: "ENTERPRISE"},
		{Name: "active", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "event_scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "approval_config", Type: field.TypeJSON},
		{Name: "application_exposed_events", Type: field.TypeInt},
		{Name: "event_type_exposures", Type: field.TypeInt, Nullable: true},
	}
	// EventExposuresTable holds the schema information for the "event_exposures" table.
	EventExposuresTable = &schema.Table{
		Name:       "event_exposures",
		Columns:    EventExposuresColumns,
		PrimaryKey: []*schema.Column{EventExposuresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "event_exposures_applications_exposed_events",
				Columns:    []*schema.Column{EventExposuresColumns[12]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "event_exposures_event_types_exposures",
				Columns:    []*schema.Column{EventExposuresColumns[13]},
				RefColumns: []*schema.Column{EventTypesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "eventexposure_event_type_application_exposed_events",
				Unique:  true,
				Columns: []*schema.Column{EventExposuresColumns[7], EventExposuresColumns[12]},
			},
		},
	}
	// EventSubscriptionsColumns holds the columns for the "event_subscriptions" table.
	EventSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "event_type", Type: field.TypeString, Size: 2147483647},
		{Name: "delivery_type", Type: field.TypeEnum, Enums: []string{"CALLBACK", "SERVER_SENT_EVENT"}, Default: "CALLBACK"},
		{Name: "trigger", Type: field.TypeJSON, Nullable: true},
		{Name: "delivery", Type: field.TypeJSON},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "callback_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "application_subscribed_events", Type: field.TypeInt},
		{Name: "event_subscription_target", Type: field.TypeInt, Nullable: true},
	}
	// EventSubscriptionsTable holds the schema information for the "event_subscriptions" table.
	EventSubscriptionsTable = &schema.Table{
		Name:       "event_subscriptions",
		Columns:    EventSubscriptionsColumns,
		PrimaryKey: []*schema.Column{EventSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "event_subscriptions_applications_subscribed_events",
				Columns:    []*schema.Column{EventSubscriptionsColumns[14]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "event_subscriptions_event_exposures_target",
				Columns:    []*schema.Column{EventSubscriptionsColumns[15]},
				RefColumns: []*schema.Column{EventExposuresColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "eventsubscription_namespace_name",
				Unique:  true,
				Columns: []*schema.Column{EventSubscriptionsColumns[6], EventSubscriptionsColumns[7]},
			},
			{
				Name:    "eventsubscription_event_type_application_subscribed_events",
				Unique:  true,
				Columns: []*schema.Column{EventSubscriptionsColumns[8], EventSubscriptionsColumns[14]},
			},
		},
	}
	// EventTypesColumns holds the columns for the "event_types" table.
	EventTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "event_type", Type: field.TypeString, Size: 2147483647},
		{Name: "version", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "specification", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "active", Type: field.TypeBool, Default: false},
		{Name: "team_event_types", Type: field.TypeInt},
	}
	// EventTypesTable holds the schema information for the "event_types" table.
	EventTypesTable = &schema.Table{
		Name:       "event_types",
		Columns:    EventTypesColumns,
		PrimaryKey: []*schema.Column{EventTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "event_types_teams_event_types",
				Columns:    []*schema.Column{EventTypesColumns[11]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "eventtype_event_type_team_event_types",
				Unique:  true,
				Columns: []*schema.Column{EventTypesColumns[6], EventTypesColumns[11]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "display_name", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// MembersColumns holds the columns for the "members" table.
	MembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "email", Type: field.TypeString, Size: 2147483647},
		{Name: "team_members", Type: field.TypeInt, Nullable: true},
	}
	// MembersTable holds the schema information for the "members" table.
	MembersTable = &schema.Table{
		Name:       "members",
		Columns:    MembersColumns,
		PrimaryKey: []*schema.Column{MembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "members_teams_members",
				Columns:    []*schema.Column{MembersColumns[4]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "member_email_team_members",
				Unique:  true,
				Columns: []*schema.Column{MembersColumns[3], MembersColumns[4]},
			},
			{
				Name:    "member_email",
				Unique:  false,
				Columns: []*schema.Column{MembersColumns[3]},
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_modified_at", Type: field.TypeTime},
		{Name: "status_phase", Type: field.TypeEnum, Nullable: true, Enums: []string{"READY", "PENDING", "ERROR", "UNKNOWN"}},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "namespace", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "email", Type: field.TypeString, Size: 2147483647},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"CUSTOMER", "INFRASTRUCTURE"}, Default: "CUSTOMER"},
		{Name: "team_token", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "group_teams", Type: field.TypeInt, Nullable: true},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "teams_groups_teams",
				Columns:    []*schema.Column{TeamsColumns[11]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ZonesColumns holds the columns for the "zones" table.
	ZonesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "environment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "gateway_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "issuer_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"WORLD", "ENTERPRISE"}, Default: "ENTERPRISE"},
		{Name: "api_subscription_failover_zones", Type: field.TypeInt, Nullable: true},
	}
	// ZonesTable holds the schema information for the "zones" table.
	ZonesTable = &schema.Table{
		Name:       "zones",
		Columns:    ZonesColumns,
		PrimaryKey: []*schema.Column{ZonesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "zones_api_subscriptions_failover_zones",
				Columns:    []*schema.Column{ZonesColumns[6]},
				RefColumns: []*schema.Column{APISubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApisTable,
		APIExposuresTable,
		APISubscriptionsTable,
		ApplicationsTable,
		ApprovalsTable,
		ApprovalRequestsTable,
		EventExposuresTable,
		EventSubscriptionsTable,
		EventTypesTable,
		GroupsTable,
		MembersTable,
		TeamsTable,
		ZonesTable,
	}
)

func init() {
	ApisTable.ForeignKeys[0].RefTable = TeamsTable
	APIExposuresTable.ForeignKeys[0].RefTable = ApisTable
	APIExposuresTable.ForeignKeys[1].RefTable = ApplicationsTable
	APISubscriptionsTable.ForeignKeys[0].RefTable = APIExposuresTable
	APISubscriptionsTable.ForeignKeys[1].RefTable = ApplicationsTable
	ApplicationsTable.ForeignKeys[0].RefTable = TeamsTable
	ApplicationsTable.ForeignKeys[1].RefTable = ZonesTable
	ApprovalsTable.ForeignKeys[0].RefTable = APISubscriptionsTable
	ApprovalsTable.ForeignKeys[1].RefTable = EventSubscriptionsTable
	ApprovalRequestsTable.ForeignKeys[0].RefTable = APISubscriptionsTable
	ApprovalRequestsTable.ForeignKeys[1].RefTable = EventSubscriptionsTable
	EventExposuresTable.ForeignKeys[0].RefTable = ApplicationsTable
	EventExposuresTable.ForeignKeys[1].RefTable = EventTypesTable
	EventSubscriptionsTable.ForeignKeys[0].RefTable = ApplicationsTable
	EventSubscriptionsTable.ForeignKeys[1].RefTable = EventExposuresTable
	EventTypesTable.ForeignKeys[0].RefTable = TeamsTable
	MembersTable.ForeignKeys[0].RefTable = TeamsTable
	TeamsTable.ForeignKeys[0].RefTable = GroupsTable
	ZonesTable.ForeignKeys[0].RefTable = APISubscriptionsTable
}
