# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: application-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-viewer-role
rules:
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications/status
  verbs:
  - get
