# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - application.cp.ei.telekom.de
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - consumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - realms
  verbs:
  - get
  - list
  - watch
