# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

package: api
generate:
  fiber-server: false
  strict-server: false
  models: true
  client: false
  embedded-spec: false
output: ../pkg/api/model.gen.go