# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-server
  namespace: system
  labels:
    control-plane: organization-server
    app.kubernetes.io/name: organization-server
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: organization-server
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: server
      labels:
        control-plane: organization-server
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - args: []
          env: []
          envFrom:
            - configMapRef:
                name: controlplane-env
                optional: true
            - configMapRef:
                name: organization-server-env
                optional: true
          image: ghcr.io/telekom/controlplane/organization-server:stable
          name: server
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 8443
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /readyz
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 30m
              memory: 128Mi
          volumeMounts:
            - name: controlplane-trust-bundle
              mountPath: /var/run/secrets/trust-bundle
              readOnly: true
            - name: cert-volume
              mountPath: /etc/tls
              readOnly: true
      volumes:
        - name: controlplane-trust-bundle
          configMap:
            name: controlplane-trust-bundle
        - name: cert-volume
          secret:
            secretName: organization-server-cert
      serviceAccountName: organization-server
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: organization-server
    app.kubernetes.io/name: organization-server
    app.kubernetes.io/managed-by: kustomize
  name: organization-server-service
  namespace: system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: organization-server
