# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: gateway.cp.ei.telekom.de/v1
kind: ConsumeRoute
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: default
    gateway: stargate
    path: foo-v1
  name: consumeroute-sample
spec:
  gateway: stargate
  path: /foo/v1