# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: identity.cp.ei.telekom.de/v1
kind: Realm
metadata:
  labels:
    app.kubernetes.io/name: identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: default
spec:
  identityProvider:
    name: iris