# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: identity.cp.ei.telekom.de/v1
kind: IdentityProvider
metadata:
  labels:
    app.kubernetes.io/name: identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: identityprovider-keycloak
spec:
  Type: keycloak
  AdminUrl: "https://iris-distcp1-dataplane1.dev.dhei.telekom.de/auth/admin/master"
  AdminClientId: "admin-cli"
  AdminUserName: ""
  AdminPassword: ""
  ConsoleUrl: "https://iris-distcp1-dataplane1.dev.dhei.telekom.de/auth/admin/master/console"