# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: test-env
---
apiVersion: admin.cp.ei.telekom.de/v1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: test-env
  name: test-env
  namespace: test-env
spec:
