// SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/telekom/controlplane/controlplane-api/ent/apiexposure"
	"github.com/telekom/controlplane/controlplane-api/ent/apisubscription"
	"github.com/telekom/controlplane/controlplane-api/ent/application"
	"github.com/telekom/controlplane/controlplane-api/ent/approval"
	"github.com/telekom/controlplane/controlplane-api/ent/approvalrequest"
	"github.com/telekom/controlplane/controlplane-api/ent/environment"
	"github.com/telekom/controlplane/controlplane-api/ent/group"
	"github.com/telekom/controlplane/controlplane-api/ent/member"
	"github.com/telekom/controlplane/controlplane-api/ent/team"
	"github.com/telekom/controlplane/controlplane-api/ent/teamenvironment"
	"github.com/telekom/controlplane/controlplane-api/ent/zone"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ApiExposureQuery) CollectFields(ctx context.Context, satisfies ...string) (*ApiExposureQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ApiExposureQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(apiexposure.Columns))
		selectedFields = []string{apiexposure.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "owner":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApplicationClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, applicationImplementors)...); err != nil {
				return err
			}
			_q.withOwner = query

		case "subscriptions":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApiSubscriptionClient{config: _q.config}).Query()
			)
			args := newApiSubscriptionPaginateArgs(fieldArgs(ctx, new(ApiSubscriptionWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newApiSubscriptionPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					_q.loadTotal = append(_q.loadTotal, func(ctx context.Context, nodes []*ApiExposure) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"api_subscription_target"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(apiexposure.SubscriptionsColumn), ids...))
						})
						if err := query.GroupBy(apiexposure.SubscriptionsColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[1] == nil {
								nodes[i].Edges.totalCount[1] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[1][alias] = n
						}
						return nil
					})
				} else {
					_q.loadTotal = append(_q.loadTotal, func(_ context.Context, nodes []*ApiExposure) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Subscriptions)
							if nodes[i].Edges.totalCount[1] == nil {
								nodes[i].Edges.totalCount[1] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[1][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, false, opCtx, *field, path, mayAddCondition(satisfies, apisubscriptionImplementors)...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				if oneNode {
					pager.applyOrder(query.Limit(limit))
				} else {
					modify := entgql.LimitPerRow(apiexposure.SubscriptionsColumn, limit, pager.orderExpr(query))
					query.modifiers = append(query.modifiers, modify)
				}
			} else {
				query = pager.applyOrder(query)
			}
			_q.WithNamedSubscriptions(alias, func(wq *ApiSubscriptionQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[apiexposure.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldCreatedAt)
				fieldSeen[apiexposure.FieldCreatedAt] = struct{}{}
			}
		case "lastModifiedAt":
			if _, ok := fieldSeen[apiexposure.FieldLastModifiedAt]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldLastModifiedAt)
				fieldSeen[apiexposure.FieldLastModifiedAt] = struct{}{}
			}
		case "statusPhase":
			if _, ok := fieldSeen[apiexposure.FieldStatusPhase]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldStatusPhase)
				fieldSeen[apiexposure.FieldStatusPhase] = struct{}{}
			}
		case "statusMessage":
			if _, ok := fieldSeen[apiexposure.FieldStatusMessage]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldStatusMessage)
				fieldSeen[apiexposure.FieldStatusMessage] = struct{}{}
			}
		case "basePath":
			if _, ok := fieldSeen[apiexposure.FieldBasePath]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldBasePath)
				fieldSeen[apiexposure.FieldBasePath] = struct{}{}
			}
		case "visibility":
			if _, ok := fieldSeen[apiexposure.FieldVisibility]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldVisibility)
				fieldSeen[apiexposure.FieldVisibility] = struct{}{}
			}
		case "active":
			if _, ok := fieldSeen[apiexposure.FieldActive]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldActive)
				fieldSeen[apiexposure.FieldActive] = struct{}{}
			}
		case "features":
			if _, ok := fieldSeen[apiexposure.FieldFeatures]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldFeatures)
				fieldSeen[apiexposure.FieldFeatures] = struct{}{}
			}
		case "upstreams":
			if _, ok := fieldSeen[apiexposure.FieldUpstreams]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldUpstreams)
				fieldSeen[apiexposure.FieldUpstreams] = struct{}{}
			}
		case "approvalConfig":
			if _, ok := fieldSeen[apiexposure.FieldApprovalConfig]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldApprovalConfig)
				fieldSeen[apiexposure.FieldApprovalConfig] = struct{}{}
			}
		case "apiVersion":
			if _, ok := fieldSeen[apiexposure.FieldAPIVersion]; !ok {
				selectedFields = append(selectedFields, apiexposure.FieldAPIVersion)
				fieldSeen[apiexposure.FieldAPIVersion] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type apiexposurePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ApiExposurePaginateOption
}

func newApiExposurePaginateArgs(rv map[string]any) *apiexposurePaginateArgs {
	args := &apiexposurePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case map[string]any:
			var (
				err1, err2 error
				order      = &ApiExposureOrder{Field: &ApiExposureOrderField{}, Direction: entgql.OrderDirectionAsc}
			)
			if d, ok := v[directionField]; ok {
				err1 = order.Direction.UnmarshalGQL(d)
			}
			if f, ok := v[fieldField]; ok {
				err2 = order.Field.UnmarshalGQL(f)
			}
			if err1 == nil && err2 == nil {
				args.opts = append(args.opts, WithApiExposureOrder(order))
			}
		case *ApiExposureOrder:
			if v != nil {
				args.opts = append(args.opts, WithApiExposureOrder(v))
			}
		}
	}
	if v, ok := rv[whereField].(*ApiExposureWhereInput); ok {
		args.opts = append(args.opts, WithApiExposureFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ApiSubscriptionQuery) CollectFields(ctx context.Context, satisfies ...string) (*ApiSubscriptionQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ApiSubscriptionQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(apisubscription.Columns))
		selectedFields = []string{apisubscription.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "owner":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApplicationClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, applicationImplementors)...); err != nil {
				return err
			}
			_q.withOwner = query

		case "target":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApiExposureClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, apiexposureImplementors)...); err != nil {
				return err
			}
			_q.withTarget = query

		case "failoverZones":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ZoneClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, zoneImplementors)...); err != nil {
				return err
			}
			_q.WithNamedFailoverZones(alias, func(wq *ZoneQuery) {
				*wq = *query
			})

		case "approval":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApprovalClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, approvalImplementors)...); err != nil {
				return err
			}
			_q.withApproval = query

		case "approvalRequest":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApprovalRequestClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, approvalrequestImplementors)...); err != nil {
				return err
			}
			_q.withApprovalRequest = query
		case "createdAt":
			if _, ok := fieldSeen[apisubscription.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldCreatedAt)
				fieldSeen[apisubscription.FieldCreatedAt] = struct{}{}
			}
		case "lastModifiedAt":
			if _, ok := fieldSeen[apisubscription.FieldLastModifiedAt]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldLastModifiedAt)
				fieldSeen[apisubscription.FieldLastModifiedAt] = struct{}{}
			}
		case "statusPhase":
			if _, ok := fieldSeen[apisubscription.FieldStatusPhase]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldStatusPhase)
				fieldSeen[apisubscription.FieldStatusPhase] = struct{}{}
			}
		case "statusMessage":
			if _, ok := fieldSeen[apisubscription.FieldStatusMessage]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldStatusMessage)
				fieldSeen[apisubscription.FieldStatusMessage] = struct{}{}
			}
		case "basePath":
			if _, ok := fieldSeen[apisubscription.FieldBasePath]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldBasePath)
				fieldSeen[apisubscription.FieldBasePath] = struct{}{}
			}
		case "m2mAuthMethod":
			if _, ok := fieldSeen[apisubscription.FieldM2mAuthMethod]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldM2mAuthMethod)
				fieldSeen[apisubscription.FieldM2mAuthMethod] = struct{}{}
			}
		case "approvedScopes":
			if _, ok := fieldSeen[apisubscription.FieldApprovedScopes]; !ok {
				selectedFields = append(selectedFields, apisubscription.FieldApprovedScopes)
				fieldSeen[apisubscription.FieldApprovedScopes] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type apisubscriptionPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ApiSubscriptionPaginateOption
}

func newApiSubscriptionPaginateArgs(rv map[string]any) *apisubscriptionPaginateArgs {
	args := &apisubscriptionPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case map[string]any:
			var (
				err1, err2 error
				order      = &ApiSubscriptionOrder{Field: &ApiSubscriptionOrderField{}, Direction: entgql.OrderDirectionAsc}
			)
			if d, ok := v[directionField]; ok {
				err1 = order.Direction.UnmarshalGQL(d)
			}
			if f, ok := v[fieldField]; ok {
				err2 = order.Field.UnmarshalGQL(f)
			}
			if err1 == nil && err2 == nil {
				args.opts = append(args.opts, WithApiSubscriptionOrder(order))
			}
		case *ApiSubscriptionOrder:
			if v != nil {
				args.opts = append(args.opts, WithApiSubscriptionOrder(v))
			}
		}
	}
	if v, ok := rv[whereField].(*ApiSubscriptionWhereInput); ok {
		args.opts = append(args.opts, WithApiSubscriptionFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ApplicationQuery) CollectFields(ctx context.Context, satisfies ...string) (*ApplicationQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ApplicationQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(application.Columns))
		selectedFields = []string{application.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "zone":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ZoneClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, zoneImplementors)...); err != nil {
				return err
			}
			_q.withZone = query

		case "exposedApis":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApiExposureClient{config: _q.config}).Query()
			)
			args := newApiExposurePaginateArgs(fieldArgs(ctx, new(ApiExposureWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newApiExposurePager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					_q.loadTotal = append(_q.loadTotal, func(ctx context.Context, nodes []*Application) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"application_exposed_apis"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(application.ExposedApisColumn), ids...))
						})
						if err := query.GroupBy(application.ExposedApisColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[1] == nil {
								nodes[i].Edges.totalCount[1] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[1][alias] = n
						}
						return nil
					})
				} else {
					_q.loadTotal = append(_q.loadTotal, func(_ context.Context, nodes []*Application) error {
						for i := range nodes {
							n := len(nodes[i].Edges.ExposedApis)
							if nodes[i].Edges.totalCount[1] == nil {
								nodes[i].Edges.totalCount[1] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[1][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, false, opCtx, *field, path, mayAddCondition(satisfies, apiexposureImplementors)...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				if oneNode {
					pager.applyOrder(query.Limit(limit))
				} else {
					modify := entgql.LimitPerRow(application.ExposedApisColumn, limit, pager.orderExpr(query))
					query.modifiers = append(query.modifiers, modify)
				}
			} else {
				query = pager.applyOrder(query)
			}
			_q.WithNamedExposedApis(alias, func(wq *ApiExposureQuery) {
				*wq = *query
			})

		case "subscribedApis":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApiSubscriptionClient{config: _q.config}).Query()
			)
			args := newApiSubscriptionPaginateArgs(fieldArgs(ctx, new(ApiSubscriptionWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newApiSubscriptionPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					_q.loadTotal = append(_q.loadTotal, func(ctx context.Context, nodes []*Application) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"application_subscribed_apis"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(application.SubscribedApisColumn), ids...))
						})
						if err := query.GroupBy(application.SubscribedApisColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[2] == nil {
								nodes[i].Edges.totalCount[2] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[2][alias] = n
						}
						return nil
					})
				} else {
					_q.loadTotal = append(_q.loadTotal, func(_ context.Context, nodes []*Application) error {
						for i := range nodes {
							n := len(nodes[i].Edges.SubscribedApis)
							if nodes[i].Edges.totalCount[2] == nil {
								nodes[i].Edges.totalCount[2] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[2][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, false, opCtx, *field, path, mayAddCondition(satisfies, apisubscriptionImplementors)...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				if oneNode {
					pager.applyOrder(query.Limit(limit))
				} else {
					modify := entgql.LimitPerRow(application.SubscribedApisColumn, limit, pager.orderExpr(query))
					query.modifiers = append(query.modifiers, modify)
				}
			} else {
				query = pager.applyOrder(query)
			}
			_q.WithNamedSubscribedApis(alias, func(wq *ApiSubscriptionQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[application.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, application.FieldCreatedAt)
				fieldSeen[application.FieldCreatedAt] = struct{}{}
			}
		case "lastModifiedAt":
			if _, ok := fieldSeen[application.FieldLastModifiedAt]; !ok {
				selectedFields = append(selectedFields, application.FieldLastModifiedAt)
				fieldSeen[application.FieldLastModifiedAt] = struct{}{}
			}
		case "statusPhase":
			if _, ok := fieldSeen[application.FieldStatusPhase]; !ok {
				selectedFields = append(selectedFields, application.FieldStatusPhase)
				fieldSeen[application.FieldStatusPhase] = struct{}{}
			}
		case "statusMessage":
			if _, ok := fieldSeen[application.FieldStatusMessage]; !ok {
				selectedFields = append(selectedFields, application.FieldStatusMessage)
				fieldSeen[application.FieldStatusMessage] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[application.FieldName]; !ok {
				selectedFields = append(selectedFields, application.FieldName)
				fieldSeen[application.FieldName] = struct{}{}
			}
		case "clientID":
			if _, ok := fieldSeen[application.FieldClientID]; !ok {
				selectedFields = append(selectedFields, application.FieldClientID)
				fieldSeen[application.FieldClientID] = struct{}{}
			}
		case "issuerURL":
			if _, ok := fieldSeen[application.FieldIssuerURL]; !ok {
				selectedFields = append(selectedFields, application.FieldIssuerURL)
				fieldSeen[application.FieldIssuerURL] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type applicationPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ApplicationPaginateOption
}

func newApplicationPaginateArgs(rv map[string]any) *applicationPaginateArgs {
	args := &applicationPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case []*ApplicationOrder:
			args.opts = append(args.opts, WithApplicationOrder(v))
		case []any:
			var orders []*ApplicationOrder
			for i := range v {
				mv, ok := v[i].(map[string]any)
				if !ok {
					continue
				}
				var (
					err1, err2 error
					order      = &ApplicationOrder{Field: &ApplicationOrderField{}, Direction: entgql.OrderDirectionAsc}
				)
				if d, ok := mv[directionField]; ok {
					err1 = order.Direction.UnmarshalGQL(d)
				}
				if f, ok := mv[fieldField]; ok {
					err2 = order.Field.UnmarshalGQL(f)
				}
				if err1 == nil && err2 == nil {
					orders = append(orders, order)
				}
			}
			args.opts = append(args.opts, WithApplicationOrder(orders))
		}
	}
	if v, ok := rv[whereField].(*ApplicationWhereInput); ok {
		args.opts = append(args.opts, WithApplicationFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ApprovalQuery) CollectFields(ctx context.Context, satisfies ...string) (*ApprovalQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ApprovalQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(approval.Columns))
		selectedFields = []string{approval.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "apiSubscription":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApiSubscriptionClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, apisubscriptionImplementors)...); err != nil {
				return err
			}
			_q.withAPISubscription = query
		case "createdAt":
			if _, ok := fieldSeen[approval.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, approval.FieldCreatedAt)
				fieldSeen[approval.FieldCreatedAt] = struct{}{}
			}
		case "lastModifiedAt":
			if _, ok := fieldSeen[approval.FieldLastModifiedAt]; !ok {
				selectedFields = append(selectedFields, approval.FieldLastModifiedAt)
				fieldSeen[approval.FieldLastModifiedAt] = struct{}{}
			}
		case "statusPhase":
			if _, ok := fieldSeen[approval.FieldStatusPhase]; !ok {
				selectedFields = append(selectedFields, approval.FieldStatusPhase)
				fieldSeen[approval.FieldStatusPhase] = struct{}{}
			}
		case "statusMessage":
			if _, ok := fieldSeen[approval.FieldStatusMessage]; !ok {
				selectedFields = append(selectedFields, approval.FieldStatusMessage)
				fieldSeen[approval.FieldStatusMessage] = struct{}{}
			}
		case "action":
			if _, ok := fieldSeen[approval.FieldAction]; !ok {
				selectedFields = append(selectedFields, approval.FieldAction)
				fieldSeen[approval.FieldAction] = struct{}{}
			}
		case "state":
			if _, ok := fieldSeen[approval.FieldState]; !ok {
				selectedFields = append(selectedFields, approval.FieldState)
				fieldSeen[approval.FieldState] = struct{}{}
			}
		case "strategy":
			if _, ok := fieldSeen[approval.FieldStrategy]; !ok {
				selectedFields = append(selectedFields, approval.FieldStrategy)
				fieldSeen[approval.FieldStrategy] = struct{}{}
			}
		case "requester":
			if _, ok := fieldSeen[approval.FieldRequester]; !ok {
				selectedFields = append(selectedFields, approval.FieldRequester)
				fieldSeen[approval.FieldRequester] = struct{}{}
			}
		case "decider":
			if _, ok := fieldSeen[approval.FieldDecider]; !ok {
				selectedFields = append(selectedFields, approval.FieldDecider)
				fieldSeen[approval.FieldDecider] = struct{}{}
			}
		case "decisions":
			if _, ok := fieldSeen[approval.FieldDecisions]; !ok {
				selectedFields = append(selectedFields, approval.FieldDecisions)
				fieldSeen[approval.FieldDecisions] = struct{}{}
			}
		case "availableTransitions":
			if _, ok := fieldSeen[approval.FieldAvailableTransitions]; !ok {
				selectedFields = append(selectedFields, approval.FieldAvailableTransitions)
				fieldSeen[approval.FieldAvailableTransitions] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type approvalPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ApprovalPaginateOption
}

func newApprovalPaginateArgs(rv map[string]any) *approvalPaginateArgs {
	args := &approvalPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case []*ApprovalOrder:
			args.opts = append(args.opts, WithApprovalOrder(v))
		case []any:
			var orders []*ApprovalOrder
			for i := range v {
				mv, ok := v[i].(map[string]any)
				if !ok {
					continue
				}
				var (
					err1, err2 error
					order      = &ApprovalOrder{Field: &ApprovalOrderField{}, Direction: entgql.OrderDirectionAsc}
				)
				if d, ok := mv[directionField]; ok {
					err1 = order.Direction.UnmarshalGQL(d)
				}
				if f, ok := mv[fieldField]; ok {
					err2 = order.Field.UnmarshalGQL(f)
				}
				if err1 == nil && err2 == nil {
					orders = append(orders, order)
				}
			}
			args.opts = append(args.opts, WithApprovalOrder(orders))
		}
	}
	if v, ok := rv[whereField].(*ApprovalWhereInput); ok {
		args.opts = append(args.opts, WithApprovalFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ApprovalRequestQuery) CollectFields(ctx context.Context, satisfies ...string) (*ApprovalRequestQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ApprovalRequestQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(approvalrequest.Columns))
		selectedFields = []string{approvalrequest.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "apiSubscription":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApiSubscriptionClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, apisubscriptionImplementors)...); err != nil {
				return err
			}
			_q.withAPISubscription = query
		case "createdAt":
			if _, ok := fieldSeen[approvalrequest.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldCreatedAt)
				fieldSeen[approvalrequest.FieldCreatedAt] = struct{}{}
			}
		case "lastModifiedAt":
			if _, ok := fieldSeen[approvalrequest.FieldLastModifiedAt]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldLastModifiedAt)
				fieldSeen[approvalrequest.FieldLastModifiedAt] = struct{}{}
			}
		case "statusPhase":
			if _, ok := fieldSeen[approvalrequest.FieldStatusPhase]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldStatusPhase)
				fieldSeen[approvalrequest.FieldStatusPhase] = struct{}{}
			}
		case "statusMessage":
			if _, ok := fieldSeen[approvalrequest.FieldStatusMessage]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldStatusMessage)
				fieldSeen[approvalrequest.FieldStatusMessage] = struct{}{}
			}
		case "action":
			if _, ok := fieldSeen[approvalrequest.FieldAction]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldAction)
				fieldSeen[approvalrequest.FieldAction] = struct{}{}
			}
		case "state":
			if _, ok := fieldSeen[approvalrequest.FieldState]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldState)
				fieldSeen[approvalrequest.FieldState] = struct{}{}
			}
		case "strategy":
			if _, ok := fieldSeen[approvalrequest.FieldStrategy]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldStrategy)
				fieldSeen[approvalrequest.FieldStrategy] = struct{}{}
			}
		case "requester":
			if _, ok := fieldSeen[approvalrequest.FieldRequester]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldRequester)
				fieldSeen[approvalrequest.FieldRequester] = struct{}{}
			}
		case "decider":
			if _, ok := fieldSeen[approvalrequest.FieldDecider]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldDecider)
				fieldSeen[approvalrequest.FieldDecider] = struct{}{}
			}
		case "decisions":
			if _, ok := fieldSeen[approvalrequest.FieldDecisions]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldDecisions)
				fieldSeen[approvalrequest.FieldDecisions] = struct{}{}
			}
		case "availableTransitions":
			if _, ok := fieldSeen[approvalrequest.FieldAvailableTransitions]; !ok {
				selectedFields = append(selectedFields, approvalrequest.FieldAvailableTransitions)
				fieldSeen[approvalrequest.FieldAvailableTransitions] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type approvalrequestPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ApprovalRequestPaginateOption
}

func newApprovalRequestPaginateArgs(rv map[string]any) *approvalrequestPaginateArgs {
	args := &approvalrequestPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case []*ApprovalRequestOrder:
			args.opts = append(args.opts, WithApprovalRequestOrder(v))
		case []any:
			var orders []*ApprovalRequestOrder
			for i := range v {
				mv, ok := v[i].(map[string]any)
				if !ok {
					continue
				}
				var (
					err1, err2 error
					order      = &ApprovalRequestOrder{Field: &ApprovalRequestOrderField{}, Direction: entgql.OrderDirectionAsc}
				)
				if d, ok := mv[directionField]; ok {
					err1 = order.Direction.UnmarshalGQL(d)
				}
				if f, ok := mv[fieldField]; ok {
					err2 = order.Field.UnmarshalGQL(f)
				}
				if err1 == nil && err2 == nil {
					orders = append(orders, order)
				}
			}
			args.opts = append(args.opts, WithApprovalRequestOrder(orders))
		}
	}
	if v, ok := rv[whereField].(*ApprovalRequestWhereInput); ok {
		args.opts = append(args.opts, WithApprovalRequestFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *EnvironmentQuery) CollectFields(ctx context.Context, satisfies ...string) (*EnvironmentQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *EnvironmentQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(environment.Columns))
		selectedFields = []string{environment.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "teamEnvironments":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&TeamEnvironmentClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, teamenvironmentImplementors)...); err != nil {
				return err
			}
			_q.WithNamedTeamEnvironments(alias, func(wq *TeamEnvironmentQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[environment.FieldName]; !ok {
				selectedFields = append(selectedFields, environment.FieldName)
				fieldSeen[environment.FieldName] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type environmentPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []EnvironmentPaginateOption
}

func newEnvironmentPaginateArgs(rv map[string]any) *environmentPaginateArgs {
	args := &environmentPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*EnvironmentWhereInput); ok {
		args.opts = append(args.opts, WithEnvironmentFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *GroupQuery) CollectFields(ctx context.Context, satisfies ...string) (*GroupQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *GroupQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(group.Columns))
		selectedFields = []string{group.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "teams":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&TeamClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, teamImplementors)...); err != nil {
				return err
			}
			_q.WithNamedTeams(alias, func(wq *TeamQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[group.FieldName]; !ok {
				selectedFields = append(selectedFields, group.FieldName)
				fieldSeen[group.FieldName] = struct{}{}
			}
		case "displayName":
			if _, ok := fieldSeen[group.FieldDisplayName]; !ok {
				selectedFields = append(selectedFields, group.FieldDisplayName)
				fieldSeen[group.FieldDisplayName] = struct{}{}
			}
		case "description":
			if _, ok := fieldSeen[group.FieldDescription]; !ok {
				selectedFields = append(selectedFields, group.FieldDescription)
				fieldSeen[group.FieldDescription] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type groupPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []GroupPaginateOption
}

func newGroupPaginateArgs(rv map[string]any) *groupPaginateArgs {
	args := &groupPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*GroupWhereInput); ok {
		args.opts = append(args.opts, WithGroupFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *MemberQuery) CollectFields(ctx context.Context, satisfies ...string) (*MemberQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *MemberQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(member.Columns))
		selectedFields = []string{member.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "team":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&TeamClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, teamImplementors)...); err != nil {
				return err
			}
			_q.withTeam = query
		case "name":
			if _, ok := fieldSeen[member.FieldName]; !ok {
				selectedFields = append(selectedFields, member.FieldName)
				fieldSeen[member.FieldName] = struct{}{}
			}
		case "email":
			if _, ok := fieldSeen[member.FieldEmail]; !ok {
				selectedFields = append(selectedFields, member.FieldEmail)
				fieldSeen[member.FieldEmail] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type memberPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []MemberPaginateOption
}

func newMemberPaginateArgs(rv map[string]any) *memberPaginateArgs {
	args := &memberPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*MemberWhereInput); ok {
		args.opts = append(args.opts, WithMemberFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *TeamQuery) CollectFields(ctx context.Context, satisfies ...string) (*TeamQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *TeamQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(team.Columns))
		selectedFields = []string{team.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "group":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&GroupClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, groupImplementors)...); err != nil {
				return err
			}
			_q.withGroup = query

		case "members":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&MemberClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, memberImplementors)...); err != nil {
				return err
			}
			_q.WithNamedMembers(alias, func(wq *MemberQuery) {
				*wq = *query
			})

		case "teamEnvironments":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&TeamEnvironmentClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, teamenvironmentImplementors)...); err != nil {
				return err
			}
			_q.WithNamedTeamEnvironments(alias, func(wq *TeamEnvironmentQuery) {
				*wq = *query
			})

		case "applications":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApplicationClient{config: _q.config}).Query()
			)
			args := newApplicationPaginateArgs(fieldArgs(ctx, new(ApplicationWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newApplicationPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					_q.loadTotal = append(_q.loadTotal, func(ctx context.Context, nodes []*Team) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"team_applications"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(team.ApplicationsColumn), ids...))
						})
						if err := query.GroupBy(team.ApplicationsColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[3] == nil {
								nodes[i].Edges.totalCount[3] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[3][alias] = n
						}
						return nil
					})
				} else {
					_q.loadTotal = append(_q.loadTotal, func(_ context.Context, nodes []*Team) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Applications)
							if nodes[i].Edges.totalCount[3] == nil {
								nodes[i].Edges.totalCount[3] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[3][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, false, opCtx, *field, path, mayAddCondition(satisfies, applicationImplementors)...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				if oneNode {
					pager.applyOrder(query.Limit(limit))
				} else {
					modify := entgql.LimitPerRow(team.ApplicationsColumn, limit, pager.orderExpr(query))
					query.modifiers = append(query.modifiers, modify)
				}
			} else {
				query = pager.applyOrder(query)
			}
			_q.WithNamedApplications(alias, func(wq *ApplicationQuery) {
				*wq = *query
			})
		case "createdAt":
			if _, ok := fieldSeen[team.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, team.FieldCreatedAt)
				fieldSeen[team.FieldCreatedAt] = struct{}{}
			}
		case "lastModifiedAt":
			if _, ok := fieldSeen[team.FieldLastModifiedAt]; !ok {
				selectedFields = append(selectedFields, team.FieldLastModifiedAt)
				fieldSeen[team.FieldLastModifiedAt] = struct{}{}
			}
		case "statusPhase":
			if _, ok := fieldSeen[team.FieldStatusPhase]; !ok {
				selectedFields = append(selectedFields, team.FieldStatusPhase)
				fieldSeen[team.FieldStatusPhase] = struct{}{}
			}
		case "statusMessage":
			if _, ok := fieldSeen[team.FieldStatusMessage]; !ok {
				selectedFields = append(selectedFields, team.FieldStatusMessage)
				fieldSeen[team.FieldStatusMessage] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[team.FieldName]; !ok {
				selectedFields = append(selectedFields, team.FieldName)
				fieldSeen[team.FieldName] = struct{}{}
			}
		case "email":
			if _, ok := fieldSeen[team.FieldEmail]; !ok {
				selectedFields = append(selectedFields, team.FieldEmail)
				fieldSeen[team.FieldEmail] = struct{}{}
			}
		case "category":
			if _, ok := fieldSeen[team.FieldCategory]; !ok {
				selectedFields = append(selectedFields, team.FieldCategory)
				fieldSeen[team.FieldCategory] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type teamPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []TeamPaginateOption
}

func newTeamPaginateArgs(rv map[string]any) *teamPaginateArgs {
	args := &teamPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case []*TeamOrder:
			args.opts = append(args.opts, WithTeamOrder(v))
		case []any:
			var orders []*TeamOrder
			for i := range v {
				mv, ok := v[i].(map[string]any)
				if !ok {
					continue
				}
				var (
					err1, err2 error
					order      = &TeamOrder{Field: &TeamOrderField{}, Direction: entgql.OrderDirectionAsc}
				)
				if d, ok := mv[directionField]; ok {
					err1 = order.Direction.UnmarshalGQL(d)
				}
				if f, ok := mv[fieldField]; ok {
					err2 = order.Field.UnmarshalGQL(f)
				}
				if err1 == nil && err2 == nil {
					orders = append(orders, order)
				}
			}
			args.opts = append(args.opts, WithTeamOrder(orders))
		}
	}
	if v, ok := rv[whereField].(*TeamWhereInput); ok {
		args.opts = append(args.opts, WithTeamFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *TeamEnvironmentQuery) CollectFields(ctx context.Context, satisfies ...string) (*TeamEnvironmentQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *TeamEnvironmentQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(teamenvironment.Columns))
		selectedFields = []string{teamenvironment.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "team":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&TeamClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, teamImplementors)...); err != nil {
				return err
			}
			_q.withTeam = query

		case "environment":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&EnvironmentClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, environmentImplementors)...); err != nil {
				return err
			}
			_q.withEnvironment = query
		case "roverTokenRef":
			if _, ok := fieldSeen[teamenvironment.FieldRoverTokenRef]; !ok {
				selectedFields = append(selectedFields, teamenvironment.FieldRoverTokenRef)
				fieldSeen[teamenvironment.FieldRoverTokenRef] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type teamenvironmentPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []TeamEnvironmentPaginateOption
}

func newTeamEnvironmentPaginateArgs(rv map[string]any) *teamenvironmentPaginateArgs {
	args := &teamenvironmentPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*TeamEnvironmentWhereInput); ok {
		args.opts = append(args.opts, WithTeamEnvironmentFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ZoneQuery) CollectFields(ctx context.Context, satisfies ...string) (*ZoneQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ZoneQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(zone.Columns))
		selectedFields = []string{zone.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "applications":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ApplicationClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, applicationImplementors)...); err != nil {
				return err
			}
			_q.WithNamedApplications(alias, func(wq *ApplicationQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[zone.FieldName]; !ok {
				selectedFields = append(selectedFields, zone.FieldName)
				fieldSeen[zone.FieldName] = struct{}{}
			}
		case "gatewayURL":
			if _, ok := fieldSeen[zone.FieldGatewayURL]; !ok {
				selectedFields = append(selectedFields, zone.FieldGatewayURL)
				fieldSeen[zone.FieldGatewayURL] = struct{}{}
			}
		case "visibility":
			if _, ok := fieldSeen[zone.FieldVisibility]; !ok {
				selectedFields = append(selectedFields, zone.FieldVisibility)
				fieldSeen[zone.FieldVisibility] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type zonePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ZonePaginateOption
}

func newZonePaginateArgs(rv map[string]any) *zonePaginateArgs {
	args := &zonePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*ZoneWhereInput); ok {
		args.opts = append(args.opts, WithZoneFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
