// SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/telekom/controlplane/controlplane-api/ent/environment"
	"github.com/telekom/controlplane/controlplane-api/ent/predicate"
	"github.com/telekom/controlplane/controlplane-api/ent/team"
	"github.com/telekom/controlplane/controlplane-api/ent/teamenvironment"
)

// TeamEnvironmentUpdate is the builder for updating TeamEnvironment entities.
type TeamEnvironmentUpdate struct {
	config
	hooks    []Hook
	mutation *TeamEnvironmentMutation
}

// Where appends a list predicates to the TeamEnvironmentUpdate builder.
func (_u *TeamEnvironmentUpdate) Where(ps ...predicate.TeamEnvironment) *TeamEnvironmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoverTokenRef sets the "rover_token_ref" field.
func (_u *TeamEnvironmentUpdate) SetRoverTokenRef(v string) *TeamEnvironmentUpdate {
	_u.mutation.SetRoverTokenRef(v)
	return _u
}

// SetNillableRoverTokenRef sets the "rover_token_ref" field if the given value is not nil.
func (_u *TeamEnvironmentUpdate) SetNillableRoverTokenRef(v *string) *TeamEnvironmentUpdate {
	if v != nil {
		_u.SetRoverTokenRef(*v)
	}
	return _u
}

// ClearRoverTokenRef clears the value of the "rover_token_ref" field.
func (_u *TeamEnvironmentUpdate) ClearRoverTokenRef() *TeamEnvironmentUpdate {
	_u.mutation.ClearRoverTokenRef()
	return _u
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (_u *TeamEnvironmentUpdate) SetTeamID(id int) *TeamEnvironmentUpdate {
	_u.mutation.SetTeamID(id)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamEnvironmentUpdate) SetTeam(v *Team) *TeamEnvironmentUpdate {
	return _u.SetTeamID(v.ID)
}

// SetEnvironmentID sets the "environment" edge to the Environment entity by ID.
func (_u *TeamEnvironmentUpdate) SetEnvironmentID(id int) *TeamEnvironmentUpdate {
	_u.mutation.SetEnvironmentID(id)
	return _u
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_u *TeamEnvironmentUpdate) SetEnvironment(v *Environment) *TeamEnvironmentUpdate {
	return _u.SetEnvironmentID(v.ID)
}

// Mutation returns the TeamEnvironmentMutation object of the builder.
func (_u *TeamEnvironmentUpdate) Mutation() *TeamEnvironmentMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamEnvironmentUpdate) ClearTeam() *TeamEnvironmentUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearEnvironment clears the "environment" edge to the Environment entity.
func (_u *TeamEnvironmentUpdate) ClearEnvironment() *TeamEnvironmentUpdate {
	_u.mutation.ClearEnvironment()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamEnvironmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamEnvironmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamEnvironmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamEnvironmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamEnvironmentUpdate) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamEnvironment.team"`)
	}
	if _u.mutation.EnvironmentCleared() && len(_u.mutation.EnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamEnvironment.environment"`)
	}
	return nil
}

func (_u *TeamEnvironmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamenvironment.Table, teamenvironment.Columns, sqlgraph.NewFieldSpec(teamenvironment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoverTokenRef(); ok {
		_spec.SetField(teamenvironment.FieldRoverTokenRef, field.TypeString, value)
	}
	if _u.mutation.RoverTokenRefCleared() {
		_spec.ClearField(teamenvironment.FieldRoverTokenRef, field.TypeString)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.TeamTable,
			Columns: []string{teamenvironment.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.TeamTable,
			Columns: []string{teamenvironment.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.EnvironmentTable,
			Columns: []string{teamenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.EnvironmentTable,
			Columns: []string{teamenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamenvironment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamEnvironmentUpdateOne is the builder for updating a single TeamEnvironment entity.
type TeamEnvironmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamEnvironmentMutation
}

// SetRoverTokenRef sets the "rover_token_ref" field.
func (_u *TeamEnvironmentUpdateOne) SetRoverTokenRef(v string) *TeamEnvironmentUpdateOne {
	_u.mutation.SetRoverTokenRef(v)
	return _u
}

// SetNillableRoverTokenRef sets the "rover_token_ref" field if the given value is not nil.
func (_u *TeamEnvironmentUpdateOne) SetNillableRoverTokenRef(v *string) *TeamEnvironmentUpdateOne {
	if v != nil {
		_u.SetRoverTokenRef(*v)
	}
	return _u
}

// ClearRoverTokenRef clears the value of the "rover_token_ref" field.
func (_u *TeamEnvironmentUpdateOne) ClearRoverTokenRef() *TeamEnvironmentUpdateOne {
	_u.mutation.ClearRoverTokenRef()
	return _u
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (_u *TeamEnvironmentUpdateOne) SetTeamID(id int) *TeamEnvironmentUpdateOne {
	_u.mutation.SetTeamID(id)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamEnvironmentUpdateOne) SetTeam(v *Team) *TeamEnvironmentUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetEnvironmentID sets the "environment" edge to the Environment entity by ID.
func (_u *TeamEnvironmentUpdateOne) SetEnvironmentID(id int) *TeamEnvironmentUpdateOne {
	_u.mutation.SetEnvironmentID(id)
	return _u
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_u *TeamEnvironmentUpdateOne) SetEnvironment(v *Environment) *TeamEnvironmentUpdateOne {
	return _u.SetEnvironmentID(v.ID)
}

// Mutation returns the TeamEnvironmentMutation object of the builder.
func (_u *TeamEnvironmentUpdateOne) Mutation() *TeamEnvironmentMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamEnvironmentUpdateOne) ClearTeam() *TeamEnvironmentUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearEnvironment clears the "environment" edge to the Environment entity.
func (_u *TeamEnvironmentUpdateOne) ClearEnvironment() *TeamEnvironmentUpdateOne {
	_u.mutation.ClearEnvironment()
	return _u
}

// Where appends a list predicates to the TeamEnvironmentUpdate builder.
func (_u *TeamEnvironmentUpdateOne) Where(ps ...predicate.TeamEnvironment) *TeamEnvironmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamEnvironmentUpdateOne) Select(field string, fields ...string) *TeamEnvironmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamEnvironment entity.
func (_u *TeamEnvironmentUpdateOne) Save(ctx context.Context) (*TeamEnvironment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamEnvironmentUpdateOne) SaveX(ctx context.Context) *TeamEnvironment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamEnvironmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamEnvironmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamEnvironmentUpdateOne) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamEnvironment.team"`)
	}
	if _u.mutation.EnvironmentCleared() && len(_u.mutation.EnvironmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamEnvironment.environment"`)
	}
	return nil
}

func (_u *TeamEnvironmentUpdateOne) sqlSave(ctx context.Context) (_node *TeamEnvironment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamenvironment.Table, teamenvironment.Columns, sqlgraph.NewFieldSpec(teamenvironment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamEnvironment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamenvironment.FieldID)
		for _, f := range fields {
			if !teamenvironment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamenvironment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoverTokenRef(); ok {
		_spec.SetField(teamenvironment.FieldRoverTokenRef, field.TypeString, value)
	}
	if _u.mutation.RoverTokenRefCleared() {
		_spec.ClearField(teamenvironment.FieldRoverTokenRef, field.TypeString)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.TeamTable,
			Columns: []string{teamenvironment.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.TeamTable,
			Columns: []string{teamenvironment.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvironmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.EnvironmentTable,
			Columns: []string{teamenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamenvironment.EnvironmentTable,
			Columns: []string{teamenvironment.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamEnvironment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamenvironment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
