# Copyright 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controlplane-root-ca
  namespace: system
spec:
  isCA: true
  commonName: Control Plane Root CA
  secretName: controlplane-root-ca
  duration: 43800h
  renewBefore: 8760h
  usages:
  - cert sign
  - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: controlplane-bootstrap-issuer
    kind: Issuer
