// SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by ent, DO NOT EDIT.

package listener

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the listener type in the database.
	Label = "listener"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastModifiedAt holds the string denoting the last_modified_at field in the database.
	FieldLastModifiedAt = "last_modified_at"
	// FieldStatusPhase holds the string denoting the status_phase field in the database.
	FieldStatusPhase = "status_phase"
	// FieldStatusMessage holds the string denoting the status_message field in the database.
	FieldStatusMessage = "status_message"
	// FieldEnvironment holds the string denoting the environment field in the database.
	FieldEnvironment = "environment"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAPIBasePath holds the string denoting the api_base_path field in the database.
	FieldAPIBasePath = "api_base_path"
	// FieldRequestFilter holds the string denoting the request_filter field in the database.
	FieldRequestFilter = "request_filter"
	// FieldResponseFilter holds the string denoting the response_filter field in the database.
	FieldResponseFilter = "response_filter"
	// EdgeApplication holds the string denoting the application edge name in mutations.
	EdgeApplication = "application"
	// EdgeSubscription holds the string denoting the subscription edge name in mutations.
	EdgeSubscription = "subscription"
	// EdgeExposure holds the string denoting the exposure edge name in mutations.
	EdgeExposure = "exposure"
	// EdgeProviderApproval holds the string denoting the provider_approval edge name in mutations.
	EdgeProviderApproval = "provider_approval"
	// EdgeConsumerApproval holds the string denoting the consumer_approval edge name in mutations.
	EdgeConsumerApproval = "consumer_approval"
	// EdgeApprovalRequests holds the string denoting the approval_requests edge name in mutations.
	EdgeApprovalRequests = "approval_requests"
	// Table holds the table name of the listener in the database.
	Table = "listeners"
	// ApplicationTable is the table that holds the application relation/edge.
	ApplicationTable = "listeners"
	// ApplicationInverseTable is the table name for the Application entity.
	// It exists in this package in order to avoid circular dependency with the "application" package.
	ApplicationInverseTable = "applications"
	// ApplicationColumn is the table column denoting the application relation/edge.
	ApplicationColumn = "application_listeners"
	// SubscriptionTable is the table that holds the subscription relation/edge.
	SubscriptionTable = "listeners"
	// SubscriptionInverseTable is the table name for the ApiSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "apisubscription" package.
	SubscriptionInverseTable = "api_subscriptions"
	// SubscriptionColumn is the table column denoting the subscription relation/edge.
	SubscriptionColumn = "api_subscription_listeners"
	// ExposureTable is the table that holds the exposure relation/edge.
	ExposureTable = "listeners"
	// ExposureInverseTable is the table name for the ApiExposure entity.
	// It exists in this package in order to avoid circular dependency with the "apiexposure" package.
	ExposureInverseTable = "api_exposures"
	// ExposureColumn is the table column denoting the exposure relation/edge.
	ExposureColumn = "api_exposure_listeners"
	// ProviderApprovalTable is the table that holds the provider_approval relation/edge.
	ProviderApprovalTable = "approvals"
	// ProviderApprovalInverseTable is the table name for the Approval entity.
	// It exists in this package in order to avoid circular dependency with the "approval" package.
	ProviderApprovalInverseTable = "approvals"
	// ProviderApprovalColumn is the table column denoting the provider_approval relation/edge.
	ProviderApprovalColumn = "listener_provider_approval"
	// ConsumerApprovalTable is the table that holds the consumer_approval relation/edge.
	ConsumerApprovalTable = "approvals"
	// ConsumerApprovalInverseTable is the table name for the Approval entity.
	// It exists in this package in order to avoid circular dependency with the "approval" package.
	ConsumerApprovalInverseTable = "approvals"
	// ConsumerApprovalColumn is the table column denoting the consumer_approval relation/edge.
	ConsumerApprovalColumn = "listener_consumer_approval"
	// ApprovalRequestsTable is the table that holds the approval_requests relation/edge.
	ApprovalRequestsTable = "approval_requests"
	// ApprovalRequestsInverseTable is the table name for the ApprovalRequest entity.
	// It exists in this package in order to avoid circular dependency with the "approvalrequest" package.
	ApprovalRequestsInverseTable = "approval_requests"
	// ApprovalRequestsColumn is the table column denoting the approval_requests relation/edge.
	ApprovalRequestsColumn = "listener_approval_requests"
)

// Columns holds all SQL columns for listener fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldLastModifiedAt,
	FieldStatusPhase,
	FieldStatusMessage,
	FieldEnvironment,
	FieldNamespace,
	FieldName,
	FieldAPIBasePath,
	FieldRequestFilter,
	FieldResponseFilter,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "listeners"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"api_exposure_listeners",
	"api_subscription_listeners",
	"application_listeners",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/telekom/controlplane/controlplane-api/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultLastModifiedAt holds the default value on creation for the "last_modified_at" field.
	DefaultLastModifiedAt func() time.Time
	// UpdateDefaultLastModifiedAt holds the default value on update for the "last_modified_at" field.
	UpdateDefaultLastModifiedAt func() time.Time
	// NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	NamespaceValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// APIBasePathValidator is a validator for the "api_base_path" field. It is called by the builders before save.
	APIBasePathValidator func(string) error
)

// StatusPhase defines the type for the "status_phase" enum field.
type StatusPhase string

// StatusPhase values.
const (
	StatusPhaseReady   StatusPhase = "READY"
	StatusPhasePending StatusPhase = "PENDING"
	StatusPhaseError   StatusPhase = "ERROR"
	StatusPhaseUnknown StatusPhase = "UNKNOWN"
)

func (sp StatusPhase) String() string {
	return string(sp)
}

// StatusPhaseValidator is a validator for the "status_phase" field enum values. It is called by the builders before save.
func StatusPhaseValidator(sp StatusPhase) error {
	switch sp {
	case StatusPhaseReady, StatusPhasePending, StatusPhaseError, StatusPhaseUnknown:
		return nil
	default:
		return fmt.Errorf("listener: invalid enum value for status_phase field: %q", sp)
	}
}

// OrderOption defines the ordering options for the Listener queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastModifiedAt orders the results by the last_modified_at field.
func ByLastModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastModifiedAt, opts...).ToFunc()
}

// ByStatusPhase orders the results by the status_phase field.
func ByStatusPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusPhase, opts...).ToFunc()
}

// ByStatusMessage orders the results by the status_message field.
func ByStatusMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusMessage, opts...).ToFunc()
}

// ByEnvironment orders the results by the environment field.
func ByEnvironment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironment, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAPIBasePath orders the results by the api_base_path field.
func ByAPIBasePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIBasePath, opts...).ToFunc()
}

// ByApplicationField orders the results by application field.
func ByApplicationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApplicationStep(), sql.OrderByField(field, opts...))
	}
}

// BySubscriptionField orders the results by subscription field.
func BySubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByExposureField orders the results by exposure field.
func ByExposureField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExposureStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderApprovalField orders the results by provider_approval field.
func ByProviderApprovalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderApprovalStep(), sql.OrderByField(field, opts...))
	}
}

// ByConsumerApprovalField orders the results by consumer_approval field.
func ByConsumerApprovalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsumerApprovalStep(), sql.OrderByField(field, opts...))
	}
}

// ByApprovalRequestsCount orders the results by approval_requests count.
func ByApprovalRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newApprovalRequestsStep(), opts...)
	}
}

// ByApprovalRequests orders the results by approval_requests terms.
func ByApprovalRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApprovalRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newApplicationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApplicationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ApplicationTable, ApplicationColumn),
	)
}
func newSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
	)
}
func newExposureStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExposureInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExposureTable, ExposureColumn),
	)
}
func newProviderApprovalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderApprovalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ProviderApprovalTable, ProviderApprovalColumn),
	)
}
func newConsumerApprovalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsumerApprovalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ConsumerApprovalTable, ConsumerApprovalColumn),
	)
}
func newApprovalRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApprovalRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ApprovalRequestsTable, ApprovalRequestsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e StatusPhase) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *StatusPhase) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = StatusPhase(str)
	if err := StatusPhaseValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid StatusPhase", str)
	}
	return nil
}
