# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: approval.cp.ei.telekom.de/v1
kind: Approval
metadata:
  labels:
    app.kubernetes.io/name: approval
    app.kubernetes.io/managed-by: kustomize
  name: approval-sample
spec:
  action: ""
  approvedRequest:
    name: foo-bar-v1--my-app
    namespace: env--group--team
  decider: {}
  requester:
    email: max.mustermann@telekom.de
    name: Max
    properties:
      basePath: /foo/bar/v1
      scopes: null
    reason: I need access to this API!
  state: Granted
  strategy: Simple
  target:
    apiVersion: stargate.cp.ei.telekom.de/v1
    kind: ApiSubscription
    name: my-app--foo-bar-v1
    namespace: env--group--team
