# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: tcp.ei.telekom.de/v1
kind: Rover
metadata:
  name: basic-rover
spec:
  zone: dataplane1
  exposures:
  - basePath: /api/basic-auth-service
    visibility: ENTERPRISE
    approval: AUTO
    upstream: https://backend-service.example.com
    security:
      tokenEndpoint: https://auth.example.com/oauth2/token
      clientId: foo
      clientSecret: bar
  subscriptions:
  - basePath: /api/basic-auth-service
    security:
      username: user
      password: pass