# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: tcp.ei.telekom.de/v1
kind: Rover
metadata:
  name: basic-rover
spec:
  zone: dataplane1
  exposures:
  - basePath: /api/basic-auth-service
    visibility: ENTERPRISE
    approval: SIMPLE
    trustedTeams:
      - team: eni--hyperion
      - team: eni--pandora
    upstream: https://backend-service.example.com
    security:
      tokenEndpoint: https://auth.example.com/oauth2/token
      clientId: foo
      clientSecret: bar
    rateLimit:
      provider:
        second: 50
        minute: 100
        hour: 200
        hideClientHeaders: false
      consumerDefault:
        second: 5
        minute: 10
        hour: 20
        hideClientHeaders: false
      consumers:
        - id: 'hub1--team2--application-name'
          second: 10
          minute: 20
          hour: 50
          hideClientHeaders: true
        - id: 'hub2--team1--application-name2'
          second: 15
          minute: 35
          hour: 175
          hideClientHeaders: false
  subscriptions:
  - basePath: /api/basic-auth-service
    security:
      username: user
      password: pass