# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.0
info:
  title: Test API 
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/basic-auth-service
    description: Local server for testing