# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to edit remoteorganizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/managed-by: kustomize
  name: remoteorganization-editor-role
rules:
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - remoteorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - remoteorganizations/status
  verbs:
  - get
