# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - environments
  - remoteorganizations
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - environments/finalizers
  - remoteorganizations/finalizers
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - admin.cp.ei.telekom.de
  resources:
  - environments/status
  - remoteorganizations/status
  - zones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.cp.ei.telekom.de
  resources:
  - consumers
  - gateways
  - realms
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.cp.ei.telekom.de
  resources:
  - clients
  - identityproviders
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
