# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: api.cp.ei.telekom.de/v1
kind: RemoteApiSubscription
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: poc
  name: remoteapisubscription-distr-sub
  namespace: poc--ger
spec:
  apiBasePath: /eni/distr/v1
  requester:
    application: distr-sub
    team:
      name: distr-test
      email: unknown@telekom.de
  sourceOrganization: ger
  targetOrganization: esp
