# Copyright 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: api.cp.ei.telekom.de/v1
kind: ApiSubscription
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: poc
    cp.ei.telekom.de/zone: dataplane1
    cp.ei.telekom.de/basepath: eni-elmar-myapi-v1
  name: my-app--eni-elmar-myapi-v1
  namespace: poc--eni--hyperion
spec:
  apiBasePath: "/eni/elmar/myapi/v1"
  organization: esp-cp
  requestor: 
    application:
      name: rover-sample
      namespace: poc--eni--hyperion
  zone: 
    name: dataplane1
    namespace: poc
---
apiVersion: api.cp.ei.telekom.de/v1
kind: ApiSubscription
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
    cp.ei.telekom.de/environment: poc
    cp.ei.telekom.de/zone: dataplane1
    cp.ei.telekom.de/basepath: eni-elmar-myapi-v1
  name: my-other-app--eni-elmar-myapi-v1
  namespace: poc--eni--hyperion
spec:
  apiBasePath: "/eni/elmar/myapi/v1"
  organization: esp-cp
  requestor: 
    application:
      name: rover-sample
      namespace: poc--eni--hyperion
  zone: 
    name: dataplane2
    namespace: poc
